// @generated DO NOT EDIT — regenerated by build.rs from config_surface.toml
//
// Mechanical scalar config accessors for the TypeScript `Config` class.
// `include!`-d into `config_class.rs`, which keeps the divergent accessors
// (enum-parsing, string, `Option`-widened, policy-aware) hand-written and
// owns the `bigint_to_u64` / `invalid_parameter_err` helpers used below.

#[napi]
impl Config {
    /// Set the reconnect delay (ms) honoured for generic transient
    /// disconnects (TimedOut, ServerRestarting, Unspecified, …).
    /// Plumbed through to the streaming I/O loop at connect time.
    /// Default `250`.
    ///
    /// Accepts a `bigint` for parity with the other bindings, which use a 64-bit unsigned integer.
    #[napi(js_name = "setReconnectWaitMs")]
    pub fn set_reconnect_wait_ms(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setReconnectWaitMs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.reconnect.wait_ms = value;
        Ok(())
    }

    /// Current reconnect `wait_ms` value (default `250`).
    #[napi(getter, js_name = "reconnectWaitMs")]
    pub fn reconnect_wait_ms(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.reconnect.wait_ms))
    }

    /// Set the reconnect delay (ms) honoured for `TooManyRequests`
    /// rate-limited disconnects. Default `130_000`.
    #[napi(js_name = "setReconnectWaitRateLimitedMs")]
    pub fn set_reconnect_wait_rate_limited_ms(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setReconnectWaitRateLimitedMs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.reconnect.wait_rate_limited_ms = value;
        Ok(())
    }

    /// Current reconnect `wait_rate_limited_ms` value (default `130_000`).
    #[napi(getter, js_name = "reconnectWaitRateLimitedMs")]
    pub fn reconnect_wait_rate_limited_ms(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.reconnect.wait_rate_limited_ms))
    }

    /// Set the cap (ms) on the exponential generic-transient reconnect
    /// ladder. The ladder starts at `reconnectWaitMs` and doubles per
    /// consecutive attempt up to this value. Default `30_000n`.
    #[napi(js_name = "setReconnectWaitMaxMs")]
    pub fn set_reconnect_wait_max_ms(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setReconnectWaitMaxMs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.reconnect.wait_max_ms = value;
        Ok(())
    }

    /// Current reconnect `wait_max_ms` value (default `30_000n`).
    #[napi(getter, js_name = "reconnectWaitMaxMs")]
    pub fn reconnect_wait_max_ms(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.reconnect.wait_max_ms))
    }

    /// Set the flat reconnect cadence (ms) for `ServerRestarting`
    /// disconnects. Default `5_000n`.
    #[napi(js_name = "setReconnectWaitServerRestartMs")]
    pub fn set_reconnect_wait_server_restart_ms(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setReconnectWaitServerRestartMs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.reconnect.wait_server_restart_ms = value;
        Ok(())
    }

    /// Current reconnect `wait_server_restart_ms` value (default `5_000n`).
    #[napi(getter, js_name = "reconnectWaitServerRestartMs")]
    pub fn reconnect_wait_server_restart_ms(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.reconnect.wait_server_restart_ms))
    }

    /// Set the subscription-replay burst size used after an
    /// auto-reconnect: frames are written in bursts of this many, each
    /// burst flushed and followed by a jittered `replayPaceMs` pause.
    /// Minimum `1` (validated at connect). Default `50`.
    #[napi(js_name = "setReconnectReplayBurstSize")]
    pub fn set_reconnect_replay_burst_size(&self, n: f64) -> napi::Result<()> {
        let value = crate::validate_u32_arg_min1("reconnectReplayBurstSize", n)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.reconnect.replay_burst_size = value;
        Ok(())
    }

    /// Current `replay_burst_size` value (default `50`).
    #[napi(getter, js_name = "reconnectReplayBurstSize")]
    pub fn reconnect_replay_burst_size(&self) -> napi::Result<u32> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.reconnect.replay_burst_size)
    }

    /// Set the pause (ms) between subscription-replay bursts after an
    /// auto-reconnect. `0n` removes the pause. Default `5n`.
    #[napi(js_name = "setReconnectReplayPaceMs")]
    pub fn set_reconnect_replay_pace_ms(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setReconnectReplayPaceMs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.reconnect.replay_pace_ms = value;
        Ok(())
    }

    /// Current `replay_pace_ms` value (default `5n`).
    #[napi(getter, js_name = "reconnectReplayPaceMs")]
    pub fn reconnect_replay_pace_ms(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.reconnect.replay_pace_ms))
    }

    /// Set the streaming read timeout (ms): the no-frames deadline after which the streaming I/O loop declares the session dead and reconnects. Default `10_000n`; validated to `[100, 60_000]` at connect.
    #[napi(js_name = "setStreamingTimeoutMs")]
    pub fn set_streaming_timeout_ms(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setStreamingTimeoutMs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.streaming.timeout_ms = value;
        Ok(())
    }

    /// Current `streaming.timeout_ms` value (default `10_000n`).
    #[napi(getter, js_name = "streamingTimeoutMs")]
    pub fn streaming_timeout_ms(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.streaming.timeout_ms))
    }

    /// Set the per-server connect timeout (ms) for the streaming connection. Default `2_000n`; validated to `[1_000, 60_000]` at connect.
    #[napi(js_name = "setStreamingConnectTimeoutMs")]
    pub fn set_streaming_connect_timeout_ms(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setStreamingConnectTimeoutMs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.streaming.connect_timeout_ms = value;
        Ok(())
    }

    /// Current `streaming.connect_timeout_ms` value (default `2_000n`).
    #[napi(getter, js_name = "streamingConnectTimeoutMs")]
    pub fn streaming_connect_timeout_ms(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.streaming.connect_timeout_ms))
    }

    /// Set the streaming heartbeat ping interval (ms). Default `100n`; validated to `[100, 300_000]` at connect.
    #[napi(js_name = "setStreamingPingIntervalMs")]
    pub fn set_streaming_ping_interval_ms(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setStreamingPingIntervalMs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.streaming.ping_interval_ms = value;
        Ok(())
    }

    /// Current `streaming.ping_interval_ms` value (default `100n`).
    #[napi(getter, js_name = "streamingPingIntervalMs")]
    pub fn streaming_ping_interval_ms(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.streaming.ping_interval_ms))
    }

    /// Set the per-iteration blocking-read slice (ms) for the streaming I/O loop. Default `25n`; validated to `[10, 500]` at connect.
    #[napi(js_name = "setStreamingIoReadSliceMs")]
    pub fn set_streaming_io_read_slice_ms(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setStreamingIoReadSliceMs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.streaming.io_read_slice_ms = value;
        Ok(())
    }

    /// Current `streaming.io_read_slice_ms` value (default `25n`).
    #[napi(getter, js_name = "streamingIoReadSliceMs")]
    pub fn streaming_io_read_slice_ms(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.streaming.io_read_slice_ms))
    }

    /// Set the TCP keepalive idle time (seconds) before the first kernel probe on a silent streaming socket. Default `5n`; validated to `[1, 7_200]` at connect.
    #[napi(js_name = "setStreamingKeepaliveIdleSecs")]
    pub fn set_streaming_keepalive_idle_secs(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setStreamingKeepaliveIdleSecs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.streaming.keepalive_idle_secs = value;
        Ok(())
    }

    /// Current `streaming.keepalive_idle_secs` value (default `5n`).
    #[napi(getter, js_name = "streamingKeepaliveIdleSecs")]
    pub fn streaming_keepalive_idle_secs(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.streaming.keepalive_idle_secs))
    }

    /// Set the interval (seconds) between TCP keepalive probes. Default `2n`; validated to `[1, 75]` at connect.
    #[napi(js_name = "setStreamingKeepaliveIntervalSecs")]
    pub fn set_streaming_keepalive_interval_secs(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setStreamingKeepaliveIntervalSecs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.streaming.keepalive_interval_secs = value;
        Ok(())
    }

    /// Current `streaming.keepalive_interval_secs` value (default `2n`).
    #[napi(getter, js_name = "streamingKeepaliveIntervalSecs")]
    pub fn streaming_keepalive_interval_secs(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.streaming.keepalive_interval_secs))
    }

    /// Set the number of unanswered TCP keepalive probes after which
    /// the kernel declares the streaming connection dead (where the
    /// platform exposes the knob). Default `2`; validated to `[1, 10]`
    /// at connect.
    #[napi(js_name = "setStreamingKeepaliveRetries")]
    pub fn set_streaming_keepalive_retries(&self, n: f64) -> napi::Result<()> {
        let value = crate::validate_u32_arg("streamingKeepaliveRetries", n)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.streaming.keepalive_retries = value;
        Ok(())
    }

    /// Current `streaming.keepalive_retries` value (default `2`).
    #[napi(getter, js_name = "streamingKeepaliveRetries")]
    pub fn streaming_keepalive_retries(&self) -> napi::Result<u32> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.streaming.keepalive_retries)
    }

    /// Current `streaming.ring_size` value (returned as a `BigInt`; default
    /// `131_072`).
    #[napi(getter, js_name = "streamingRingSize")]
    pub fn streaming_ring_size(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.streaming.ring_size as u64))
    }

    /// Set how the streaming consumer waits when the event ring is empty.
    /// Accepts `"spin"` (default), `"busyspin"`, `"park"`, or `"backoff"`
    /// (case-insensitive). `"spin"` and `"busyspin"` both hold ~100% of one core
    /// and differ only in jitter; only `"park"` and `"backoff"` lower idle CPU.
    /// The park / backoff sleep length is `parkIntervalUs`.
    #[napi(js_name = "setWaitMode")]
    pub fn set_wait_mode(&self, mode: String) -> napi::Result<()> {
        let parsed = config::WaitMode::parse(&mode).ok_or_else(|| {
            crate::invalid_parameter_err(format!(
                "setWaitMode: unknown mode {mode:?}; expected \"spin\", \"busyspin\", \"park\" or \"backoff\""
            ))
        })?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.streaming.wait_mode = parsed;
        Ok(())
    }

    /// Current streaming consumer wait mode as a lowercase string.
    #[napi(getter, js_name = "waitMode")]
    pub fn wait_mode(&self) -> napi::Result<&'static str> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.streaming.wait_mode.as_str())
    }

    /// Set the park / backoff idle sleep length in microseconds for the streaming
    /// consumer. Used only when the wait mode is `"park"` or `"backoff"`. Validated
    /// `[50, 1000000]` at connect time. Default `1000` (= 1 ms).
    ///
    /// Accepts a `bigint` for parity with the other bindings, which use a 64-bit unsigned integer.
    #[napi(js_name = "setParkIntervalUs")]
    pub fn set_park_interval_us(&self, us: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setParkIntervalUs", &us)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.streaming.park_interval_us = value;
        Ok(())
    }

    /// Current streaming `park_interval_us` value in microseconds (returned as a
    /// `BigInt`; default `1000`, = 1 ms).
    #[napi(getter, js_name = "parkIntervalUs")]
    pub fn park_interval_us(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.streaming.park_interval_us))
    }

    /// Set the wall-clock envelope (seconds) for one
    /// market-data-channel retry sequence, measured from the first
    /// attempt. `0n` disables the envelope (attempt budget only).
    /// Default `300n`.
    #[napi(js_name = "setRetryMaxElapsedSecs")]
    pub fn set_retry_max_elapsed_secs(&self, secs: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setRetryMaxElapsedSecs", &secs)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.retry.max_elapsed = std::time::Duration::from_secs(value);
        Ok(())
    }

    /// Current `retry.max_elapsed` value in seconds (default `300n`;
    /// `0n` = disabled).
    #[napi(getter, js_name = "retryMaxElapsedSecs")]
    pub fn retry_max_elapsed_secs(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.retry.max_elapsed.as_secs()))
    }

    /// Toggle AWS-style full jitter on the flatfile retry ladder.
    /// Default `true`; `false` gives the deterministic schedule,
    /// useful for tests that assert exact timings.
    #[napi(js_name = "setFlatfilesJitter")]
    pub fn set_flatfiles_jitter(&self, jitter: bool) -> napi::Result<()> {
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.flatfiles.jitter = jitter;
        Ok(())
    }

    /// Current `flatfiles.jitter` value (default `true`).
    #[napi(getter, js_name = "flatfilesJitter")]
    pub fn flatfiles_jitter(&self) -> napi::Result<bool> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.flatfiles.jitter)
    }

    /// Set the initial backoff delay (ms) for the market-data-channel retry policy.
    /// Default `250n`. Subsequent retries double from here, capped at
    /// `retryMaxDelayMs`.
    #[napi(js_name = "setRetryInitialDelayMs")]
    pub fn set_retry_initial_delay_ms(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setRetryInitialDelayMs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.retry.initial_delay = std::time::Duration::from_millis(value);
        Ok(())
    }

    /// Set the upper-bound backoff delay (ms) for the market-data retry
    /// policy. Default `30_000n` (30 s).
    #[napi(js_name = "setRetryMaxDelayMs")]
    pub fn set_retry_max_delay_ms(&self, ms: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setRetryMaxDelayMs", &ms)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.retry.max_delay = std::time::Duration::from_millis(value);
        Ok(())
    }

    /// Set the total attempt budget for the market-data-channel retry policy. `1`
    /// disables retry; higher values permit retries up to
    /// `maxAttempts - 1` after the initial call. Default `20`.
    #[napi(js_name = "setRetryMaxAttempts")]
    pub fn set_retry_max_attempts(&self, n: f64) -> napi::Result<()> {
        let value = crate::validate_u32_arg_min1("retryMaxAttempts", n)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.retry.max_attempts = value;
        Ok(())
    }

    /// Current `retry.max_attempts` value.
    #[napi(getter, js_name = "retryMaxAttempts")]
    pub fn retry_max_attempts(&self) -> napi::Result<u32> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.retry.max_attempts)
    }

    /// Toggle AWS-style full-jitter on the market-data-channel retry policy. Default
    /// `true`. `false` gives the deterministic backoff schedule
    /// `min(max_delay, initial * 2^attempt)`, useful for tests that
    /// need to assert exact timings.
    #[napi(js_name = "setRetryJitter")]
    pub fn set_retry_jitter(&self, jitter: bool) -> napi::Result<()> {
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.retry.jitter = jitter;
        Ok(())
    }

    /// Current `retry.jitter` value.
    #[napi(getter, js_name = "retryJitter")]
    pub fn retry_jitter(&self) -> napi::Result<bool> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.retry.jitter)
    }

    /// Set the total attempt budget for the flatfile driver retry
    /// loop. `1` disables retry (single call only); higher values
    /// permit retries up to `maxAttempts - 1` after the initial call.
    /// Default `10`. Validated to the range `[1, 100]` at connect time.
    #[napi(js_name = "setFlatfilesMaxAttempts")]
    pub fn set_flatfiles_max_attempts(&self, n: f64) -> napi::Result<()> {
        let value = crate::validate_u32_arg_min1("flatfilesMaxAttempts", n)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.flatfiles.max_attempts = value;
        Ok(())
    }

    /// Current `flatfiles.max_attempts` value.
    #[napi(getter, js_name = "flatfilesMaxAttempts")]
    pub fn flatfiles_max_attempts(&self) -> napi::Result<u32> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.flatfiles.max_attempts)
    }

    /// Set the initial backoff delay (seconds) for the flatfile
    /// driver retry loop. Doubles per attempt up to
    /// `flatfilesMaxBackoffSecs`. Default `1n`.
    ///
    /// Accepts a `bigint` for parity with the other bindings, which
    /// use a 64-bit unsigned integer.
    #[napi(js_name = "setFlatfilesInitialBackoffSecs")]
    pub fn set_flatfiles_initial_backoff_secs(&self, secs: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setFlatfilesInitialBackoffSecs", &secs)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.flatfiles.initial_backoff = std::time::Duration::from_secs(value);
        Ok(())
    }

    /// Current `flatfiles.initial_backoff` value (seconds, returned as BigInt).
    #[napi(getter, js_name = "flatfilesInitialBackoffSecs")]
    pub fn flatfiles_initial_backoff_secs(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.flatfiles.initial_backoff.as_secs()))
    }

    /// Set the upper-bound backoff delay (seconds) for the flatfile
    /// driver retry loop. The doubling schedule never exceeds this
    /// value regardless of attempt number. Default `30n`. Must be
    /// greater than or equal to `flatfilesInitialBackoffSecs`
    /// (rejected at connect-time validate otherwise).
    ///
    /// Accepts a `bigint` for parity with the other bindings, which
    /// use a 64-bit unsigned integer.
    #[napi(js_name = "setFlatfilesMaxBackoffSecs")]
    pub fn set_flatfiles_max_backoff_secs(&self, secs: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setFlatfilesMaxBackoffSecs", &secs)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.flatfiles.max_backoff = std::time::Duration::from_secs(value);
        Ok(())
    }

    /// Current `flatfiles.max_backoff` value (seconds, returned as BigInt).
    #[napi(getter, js_name = "flatfilesMaxBackoffSecs")]
    pub fn flatfiles_max_backoff_secs(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.flatfiles.max_backoff.as_secs()))
    }

    /// Set the TCP + TLS connect timeout (seconds) for one flatfile-host
    /// attempt. Bounds the connect/auth handshake before the attempt is
    /// abandoned and the next host (or the retry ladder) takes over.
    /// Default `10n`.
    ///
    /// Accepts a `bigint` for parity with the other bindings, which
    /// use a 64-bit unsigned integer.
    #[napi(js_name = "setFlatfilesConnectTimeoutSecs")]
    pub fn set_flatfiles_connect_timeout_secs(&self, secs: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setFlatfilesConnectTimeoutSecs", &secs)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.flatfiles.connect_timeout_secs = value;
        Ok(())
    }

    /// Current `flatfiles.connect_timeout_secs` value (seconds, returned as BigInt).
    #[napi(getter, js_name = "flatfilesConnectTimeoutSecs")]
    pub fn flatfiles_connect_timeout_secs(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.flatfiles.connect_timeout_secs))
    }

    /// Set the read timeout (seconds) for a single flatfile response
    /// frame. Bounds the wait for the next chunk once streaming has begun
    /// so a mid-stream stall fails over instead of blocking forever.
    /// Default `60n`.
    ///
    /// Accepts a `bigint` for parity with the other bindings, which
    /// use a 64-bit unsigned integer.
    #[napi(js_name = "setFlatfilesReadTimeoutSecs")]
    pub fn set_flatfiles_read_timeout_secs(&self, secs: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setFlatfilesReadTimeoutSecs", &secs)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.flatfiles.read_timeout_secs = value;
        Ok(())
    }

    /// Current `flatfiles.read_timeout_secs` value (seconds, returned as BigInt).
    #[napi(getter, js_name = "flatfilesReadTimeoutSecs")]
    pub fn flatfiles_read_timeout_secs(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.flatfiles.read_timeout_secs))
    }

    /// Override the market-data gRPC port. Companion to `setMarketDataHost` —
    /// same test-only rationale. Rejects values outside the `0..=65535`
    /// port range.
    #[napi(js_name = "setMarketDataPort")]
    pub fn set_market_data_port(&self, port: u32) -> napi::Result<()> {
        let value = u16::try_from(port).map_err(|_| {
            crate::invalid_parameter_err(format!(
                "setMarketDataPort: port must be in the u16 range 0..=65535; got {port}"
            ))
        })?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.market_data.port = value;
        Ok(())
    }

    /// Current market-data gRPC port.
    #[napi(getter, js_name = "marketDataPort")]
    pub fn market_data_port(&self) -> napi::Result<u32> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(u32::from(guard.market_data.port))
    }

    /// Set the warning threshold (in bytes) for buffered (non-streaming)
    /// historical responses. Endpoints whose decoded total exceeds this
    /// value log a warning pointing the caller at the
    /// matching `<endpoint>Stream(...)` method (e.g. `optionHistoryTradeStream`),
    /// which delivers the same rows chunk-by-chunk through a callback with
    /// memory bounded to a single chunk; the buffered data is still
    /// delivered. `0n` disables the warning entirely. Default is
    /// `100n * 1024n * 1024n` (100 MiB). Byte budgets can exceed the
    /// 32-bit unsigned range, so the setter takes a `BigInt`.
    #[napi(js_name = "setWarnOnBufferedThresholdBytes")]
    pub fn set_warn_on_buffered_threshold_bytes(&self, n: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setWarnOnBufferedThresholdBytes", &n)?;
        let value = usize::try_from(value)
            .map_err(|_| napi::Error::from_reason("value exceeds usize on this platform"))?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.market_data.warn_on_buffered_threshold_bytes = value;
        Ok(())
    }

    /// Current `warn_on_buffered_threshold_bytes` setting (bytes,
    /// returned as a `BigInt`).
    #[napi(getter, js_name = "warnOnBufferedThresholdBytes")]
    pub fn warn_on_buffered_threshold_bytes(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.market_data.warn_on_buffered_threshold_bytes as u64))
    }

    /// Set the default per-request deadline (seconds) for market-data
    /// queries. Bounds every request that did not set its own deadline,
    /// so a live-but-silent stream resolves to a timeout instead of
    /// blocking forever. `0n` no longer disables the default; it is floored
    /// to the `300n`-second default at request time. Default `300n`
    /// (5 minutes). Seconds are taken as a `BigInt` for parity with the
    /// other `*Secs` knobs.
    #[napi(js_name = "setRequestTimeoutSecs")]
    pub fn set_request_timeout_secs(&self, secs: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setRequestTimeoutSecs", &secs)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.market_data.request_timeout_secs = value;
        Ok(())
    }

    /// Current market-data `request_timeout_secs` setting in seconds
    /// (default `300n`). A stored `0n` is floored to the `300n`-second
    /// default at request time rather than disabling the deadline.
    #[napi(getter, js_name = "requestTimeoutSecs")]
    pub fn request_timeout_secs(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.market_data.request_timeout_secs))
    }

    /// Set the initial per-stream HTTP/2 flow-control window (in KB) for the
    /// market-data gRPC channel. A larger window raises the throughput ceiling
    /// on bulk streaming pulls before HTTP/2 backpressure kicks in. The value
    /// is clamped into `[64, 2_097_151]` KB at validate/connect time. Default
    /// `8192n` (8 MiB). KB are taken as a `BigInt` for parity with the other
    /// byte/KB-denominated knobs.
    #[napi(js_name = "setMarketDataStreamWindowSizeKb")]
    pub fn set_market_data_stream_window_size_kb(&self, kb: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setMarketDataStreamWindowSizeKb", &kb)?;
        let value = usize::try_from(value)
            .map_err(|_| napi::Error::from_reason("value exceeds usize on this platform"))?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.market_data.stream_window_size_kb = value;
        Ok(())
    }

    /// Current per-stream HTTP/2 flow-control window (KB) for the market-data
    /// gRPC channel (default `8192n`, returned as a `BigInt`).
    #[napi(getter, js_name = "marketDataStreamWindowSizeKb")]
    pub fn market_data_stream_window_size_kb(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.market_data.stream_window_size_kb as u64))
    }

    /// Set the initial connection-level HTTP/2 flow-control window (in KB) for
    /// the market-data gRPC channel. A larger window raises the throughput
    /// ceiling on bulk streaming pulls before HTTP/2 backpressure kicks in.
    /// The value is clamped into `[64, 2_097_151]` KB at validate/connect
    /// time. Default `16384n` (16 MiB). KB are taken as a `BigInt` for parity
    /// with the other byte/KB-denominated knobs.
    #[napi(js_name = "setMarketDataConnectionWindowSizeKb")]
    pub fn set_market_data_connection_window_size_kb(&self, kb: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setMarketDataConnectionWindowSizeKb", &kb)?;
        let value = usize::try_from(value)
            .map_err(|_| napi::Error::from_reason("value exceeds usize on this platform"))?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.market_data.connection_window_size_kb = value;
        Ok(())
    }

    /// Current connection-level HTTP/2 flow-control window (KB) for the
    /// market-data gRPC channel (default `16384n`, returned as a `BigInt`).
    #[napi(getter, js_name = "marketDataConnectionWindowSizeKb")]
    pub fn market_data_connection_window_size_kb(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(guard.market_data.connection_window_size_kb as u64))
    }

    /// Automatic bulk-fetch sharding policy for history pulls (buffered and
    /// chunk-streaming alike). Accepts `"auto"` (default: a large history
    /// pull's requested time or date range is split into equal concurrent
    /// bands across the account's concurrent-request budget — buffered pulls
    /// are merged back into exactly
    /// the rows of the single-stream response, single-contract, stock, and
    /// index pulls in the exact single-stream order and option-chain pulls in
    /// a deterministic canonical order grouped by expiration, strike, and
    /// right; streaming pulls forward each band's chunks as they arrive, every
    /// chunk exactly once but interleaved across bands in arrival order; small
    /// pulls are never sharded) or `"off"` (every query runs as a single
    /// stream, in the server's own row and chunk order), case-insensitive.
    #[napi(js_name = "setBulkFetch")]
    pub fn set_bulk_fetch(&self, policy: String) -> napi::Result<()> {
        let parsed = config::BulkFetchPolicy::parse(&policy).ok_or_else(|| {
            crate::invalid_parameter_err(format!(
                "setBulkFetch: unknown policy {policy:?}; expected \"auto\" or \"off\""
            ))
        })?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.market_data.bulk_fetch = parsed;
        Ok(())
    }

    /// Current bulk-fetch sharding policy as a lowercase string.
    #[napi(getter, js_name = "bulkFetch")]
    pub fn bulk_fetch(&self) -> napi::Result<&'static str> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.market_data.bulk_fetch.as_str())
    }

    /// Set the upper bound on concurrent sub-requests per sharded bulk fetch.
    /// Pass `null` or `undefined` (the default) to use the account's full
    /// concurrent-request budget (the tier-derived channel-pool size resolved
    /// at connect time); pass a `number` to cap the fan-out. The applied value
    /// is clamped into `[1, pool_size]` when a plan is built (the pool size is
    /// the server-enforced tier ceiling).
    #[napi(js_name = "setShardConcurrency")]
    pub fn set_shard_concurrency(&self, n: Option<u32>) -> napi::Result<()> {
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.market_data.shard_concurrency = n;
        Ok(())
    }

    /// Current `shardConcurrency` setting. `null` means a sharded pull uses
    /// the account's full concurrent-request budget; a `number` is the
    /// configured cap.
    #[napi(getter, js_name = "shardConcurrency")]
    pub fn shard_concurrency(&self) -> napi::Result<Option<u32>> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.market_data.shard_concurrency)
    }

    /// Current `retry.initial_delay` value (ms, returned as BigInt).
    #[napi(getter, js_name = "retryInitialDelayMs")]
    pub fn retry_initial_delay_ms(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(u64::try_from(guard.retry.initial_delay.as_millis()).unwrap_or(u64::MAX)))
    }

    /// Current `retry.max_delay` value (ms, returned as BigInt).
    #[napi(getter, js_name = "retryMaxDelayMs")]
    pub fn retry_max_delay_ms(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(napi::bindgen_prelude::BigInt::from(u64::try_from(guard.retry.max_delay.as_millis()).unwrap_or(u64::MAX)))
    }

    /// Set the per-class transient-failure attempt budget for the
    /// auto-reconnect path. Default `30`. No effect unless the
    /// reconnect policy is `Auto`.
    #[napi(js_name = "setReconnectMaxAttempts")]
    pub fn set_reconnect_max_attempts(&self, max_attempts: f64) -> napi::Result<()> {
        let value = crate::validate_u32_arg_min1("reconnectMaxAttempts", max_attempts)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        if let config::ReconnectPolicy::Auto(ref mut limits) = guard.reconnect.policy {
            limits.max_attempts = value;
        }
        Ok(())
    }

    /// Current generic-transient reconnect attempt budget (default
    /// `30`). Reads the default-limits value when the policy is not
    /// `Auto`.
    #[napi(getter, js_name = "reconnectMaxAttempts")]
    pub fn reconnect_max_attempts(&self) -> napi::Result<u32> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(match &guard.reconnect.policy {
            config::ReconnectPolicy::Auto(limits) => limits.max_attempts,
            _ => config::ReconnectAttemptLimits::default().max_attempts,
        })
    }

    /// Set the per-class rate-limited (`TooManyRequests`) attempt
    /// budget for the auto-reconnect path. Default `100`. No effect
    /// unless the reconnect policy is `Auto`.
    #[napi(js_name = "setReconnectMaxRateLimitedAttempts")]
    pub fn set_reconnect_max_rate_limited_attempts(&self, max_rate_limited_attempts: f64) -> napi::Result<()> {
        let value = crate::validate_u32_arg_min1("reconnectMaxRateLimitedAttempts", max_rate_limited_attempts)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        if let config::ReconnectPolicy::Auto(ref mut limits) = guard.reconnect.policy {
            limits.max_rate_limited_attempts = value;
        }
        Ok(())
    }

    /// Current rate-limited reconnect attempt budget (default `100`).
    /// Reads the default-limits value when the policy is not `Auto`.
    #[napi(getter, js_name = "reconnectMaxRateLimitedAttempts")]
    pub fn reconnect_max_rate_limited_attempts(&self) -> napi::Result<u32> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(match &guard.reconnect.policy {
            config::ReconnectPolicy::Auto(limits) => limits.max_rate_limited_attempts,
            _ => config::ReconnectAttemptLimits::default().max_rate_limited_attempts,
        })
    }

    /// Set the `ServerRestarting` reconnect attempt budget. Default
    /// `60`. No effect unless the reconnect policy is `Auto`.
    #[napi(js_name = "setReconnectMaxServerRestartAttempts")]
    pub fn set_reconnect_max_server_restart_attempts(&self, n: f64) -> napi::Result<()> {
        let value = crate::validate_u32_arg_min1("reconnectMaxServerRestartAttempts", n)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        if let config::ReconnectPolicy::Auto(ref mut limits) = guard.reconnect.policy {
            limits.max_server_restart_attempts = value;
        }
        Ok(())
    }

    /// Current `ServerRestarting` reconnect attempt budget (default
    /// `60`). Reads the default-limits value when the policy is not
    /// `Auto`.
    #[napi(getter, js_name = "reconnectMaxServerRestartAttempts")]
    pub fn reconnect_max_server_restart_attempts(&self) -> napi::Result<u32> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(match &guard.reconnect.policy {
            config::ReconnectPolicy::Auto(limits) => limits.max_server_restart_attempts,
            _ => config::ReconnectAttemptLimits::default().max_server_restart_attempts,
        })
    }

    /// Set the wall-clock reconnect envelope (seconds) for the
    /// generic-transient and server-restart classes, measured from the
    /// first attempt of a consecutive-reconnect sequence. `0n` disables
    /// the envelope (attempt budgets only). Default `300n`. No effect
    /// unless the reconnect policy is `Auto`.
    #[napi(js_name = "setReconnectMaxElapsedSecs")]
    pub fn set_reconnect_max_elapsed_secs(&self, secs: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setReconnectMaxElapsedSecs", &secs)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        if let config::ReconnectPolicy::Auto(ref mut limits) = guard.reconnect.policy {
            limits.max_elapsed = std::time::Duration::from_secs(value);
        }
        Ok(())
    }

    /// Current wall-clock reconnect envelope in seconds (default
    /// `300n`; `0n` = disabled). Reads the default-limits value when
    /// the policy is not `Auto`.
    #[napi(getter, js_name = "reconnectMaxElapsedSecs")]
    pub fn reconnect_max_elapsed_secs(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        let value = match &guard.reconnect.policy {
            config::ReconnectPolicy::Auto(limits) => limits.max_elapsed,
            _ => config::ReconnectAttemptLimits::default().max_elapsed,
        };
        Ok(napi::bindgen_prelude::BigInt::from(value.as_secs()))
    }

    /// Set the continuous successful-data-flow window (in seconds)
    /// after which the auto-reconnect attempt counters reset. Default
    /// `60`. No effect unless the reconnect policy is `Auto`.
    ///
    /// Accepts a `bigint` for parity with the Python / C++ / FFI
    /// surface, which uses a 64-bit unsigned integer. JavaScript `Number` callers should wrap their
    /// value: `setReconnectStableWindowSecs(BigInt(60))`.
    #[napi(js_name = "setReconnectStableWindowSecs")]
    pub fn set_reconnect_stable_window_secs(&self, secs: napi::bindgen_prelude::BigInt) -> napi::Result<()> {
        let value = bigint_to_u64("setReconnectStableWindowSecs", &secs)?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        if let config::ReconnectPolicy::Auto(ref mut limits) = guard.reconnect.policy {
            limits.stable_window = std::time::Duration::from_secs(value);
        }
        Ok(())
    }

    /// Current stable-window reset interval in seconds (default `60n`).
    /// Reads the default-limits value when the policy is not `Auto`.
    #[napi(getter, js_name = "reconnectStableWindowSecs")]
    pub fn reconnect_stable_window_secs(&self) -> napi::Result<napi::bindgen_prelude::BigInt> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        let value = match &guard.reconnect.policy {
            config::ReconnectPolicy::Auto(limits) => limits.stable_window,
            _ => config::ReconnectAttemptLimits::default().stable_window,
        };
        Ok(napi::bindgen_prelude::BigInt::from(value.as_secs()))
    }

    /// Set the Nexus auth URL. Default matches the upstream
    /// production endpoint; override to redirect at a staging
    /// cluster for testing.
    #[napi(js_name = "setNexusUrl")]
    pub fn set_nexus_url(&self, url: String) -> napi::Result<()> {
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.auth.nexus_url = url;
        Ok(())
    }

    /// Current `auth.nexus_url` value.
    #[napi(getter, js_name = "nexusUrl")]
    pub fn nexus_url(&self) -> napi::Result<String> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.auth.nexus_url.clone())
    }

    /// Set the `QueryInfo.client_type` identifier. Default is
    /// `"rust-thetadatadx"`; override to identify a deployment fleet
    /// in server-side dashboards.
    #[napi(js_name = "setClientType")]
    pub fn set_client_type(&self, client_type: String) -> napi::Result<()> {
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.auth.client_type = client_type;
        Ok(())
    }

    /// Current `auth.client_type` value.
    #[napi(getter, js_name = "clientType")]
    pub fn client_type(&self) -> napi::Result<String> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.auth.client_type.clone())
    }

    /// Override the market-data gRPC host. Companion to `setMarketDataPort`.
    #[napi(js_name = "setMarketDataHost")]
    pub fn set_market_data_host(&self, host: String) -> napi::Result<()> {
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.set_market_data_host(host);
        Ok(())
    }

    /// Current market-data gRPC host.
    #[napi(getter, js_name = "marketDataHost")]
    pub fn market_data_host(&self) -> napi::Result<String> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.market_data_host().to_string())
    }

    /// Set the jitter strategy applied to every reconnect delay.
    /// Accepts `"full"` (default) or `"none"` (case-insensitive).
    #[napi(js_name = "setReconnectJitter")]
    pub fn set_reconnect_jitter(&self, mode: String) -> napi::Result<()> {
        let parsed = config::JitterMode::parse(&mode).ok_or_else(|| {
            crate::invalid_parameter_err(format!(
                "setReconnectJitter: unknown mode {mode:?}; expected \"full\" or \"none\""
            ))
        })?;
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.reconnect.jitter = parsed;
        Ok(())
    }

    /// Current reconnect jitter mode as a lowercase string.
    #[napi(getter, js_name = "reconnectJitter")]
    pub fn reconnect_jitter(&self) -> napi::Result<&'static str> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.reconnect.jitter.as_str())
    }

    /// Set the Prometheus exporter port. Pass `null` or `undefined`
    /// to leave the exporter disabled (the default); pass a
    /// `number` to bind an HTTP listener on `0.0.0.0:<port>` when the
    /// `metrics-prometheus` feature is compiled in.
    ///
    /// Rejects values outside the `0..=65535` port range.
    #[napi(js_name = "setMetricsPort")]
    pub fn set_metrics_port(&self, port: Option<u32>) -> napi::Result<()> {
        let resolved = match port {
            Some(v) => Some(u16::try_from(v).map_err(|_| {
                crate::invalid_parameter_err(format!(
                    "setMetricsPort: port must be in 0..=65535; got {v}"
                ))
            })?),
            None => None,
        };
        let mut guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        guard.metrics.port = resolved;
        Ok(())
    }

    /// Current `metrics.port` setting. `null` means the exporter is
    /// disabled; a `number` is the bound port.
    #[napi(getter, js_name = "metricsPort")]
    pub fn metrics_port(&self) -> napi::Result<Option<u32>> {
        let guard = self
            .inner
            .lock()
            .map_err(|_| napi::Error::from_reason("Config mutex poisoned"))?;
        Ok(guard.metrics.port.map(u32::from))
    }

}
