// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml

/// Fetch end-of-day stock data for a date range. Returns OHLCV + bid/ask per trading day.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_stock_history_eod_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    start_date: *const c_char
,
    end_date: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let start_date = require_cstr!(start_date, empty);
        args.insert(
            "start_date".to_string(),
            thetadatadx::EndpointArgValue::Str(start_date.to_string()),
        );
        let end_date = require_cstr!(end_date, empty);
        args.insert(
            "end_date".to_string(),
            thetadatadx::EndpointArgValue::Str(end_date.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "stock_history_eod", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch intraday OHLC bars for a stock on a single date.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_stock_history_ohlc_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "stock_history_ohlc", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch all trades for a stock on a given date.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_stock_history_trade_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "stock_history_trade", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch NBBO quotes for a stock on a given date at a given interval.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_stock_history_quote_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "stock_history_quote", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch combined trade + quote ticks for a stock on a given date. Returns raw DataTable.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_stock_history_trade_quote_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "stock_history_trade_quote", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch the trade at a specific time of day across a date range.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_stock_at_time_trade_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    start_date: *const c_char
,
    end_date: *const c_char
,
    time_of_day: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let start_date = require_cstr!(start_date, empty);
        args.insert(
            "start_date".to_string(),
            thetadatadx::EndpointArgValue::Str(start_date.to_string()),
        );
        let end_date = require_cstr!(end_date, empty);
        args.insert(
            "end_date".to_string(),
            thetadatadx::EndpointArgValue::Str(end_date.to_string()),
        );
        let time_of_day = require_cstr!(time_of_day, empty);
        args.insert(
            "time_of_day".to_string(),
            thetadatadx::EndpointArgValue::Str(time_of_day.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "stock_at_time_trade", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch the quote at a specific time of day across a date range.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_stock_at_time_quote_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    start_date: *const c_char
,
    end_date: *const c_char
,
    time_of_day: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let start_date = require_cstr!(start_date, empty);
        args.insert(
            "start_date".to_string(),
            thetadatadx::EndpointArgValue::Str(start_date.to_string()),
        );
        let end_date = require_cstr!(end_date, empty);
        args.insert(
            "end_date".to_string(),
            thetadatadx::EndpointArgValue::Str(end_date.to_string()),
        );
        let time_of_day = require_cstr!(time_of_day, empty);
        args.insert(
            "time_of_day".to_string(),
            thetadatadx::EndpointArgValue::Str(time_of_day.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "stock_at_time_quote", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch end-of-day option data for a contract over a date range.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_eod_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    start_date: *const c_char
,
    end_date: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );
        let start_date = require_cstr!(start_date, empty);
        args.insert(
            "start_date".to_string(),
            thetadatadx::EndpointArgValue::Str(start_date.to_string()),
        );
        let end_date = require_cstr!(end_date, empty);
        args.insert(
            "end_date".to_string(),
            thetadatadx::EndpointArgValue::Str(end_date.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_eod", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch intraday OHLC bars for an option contract.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_ohlc_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_ohlc", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch all trades for an option contract on a given date.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_trade_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_trade", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch NBBO quotes for an option contract on a given date.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_quote_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_quote", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch combined trade + quote ticks for an option contract.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_trade_quote_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_trade_quote", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch open interest history for an option contract.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_open_interest_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_open_interest", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch end-of-day Greeks history for an option contract.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_greeks_eod_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    start_date: *const c_char
,
    end_date: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );
        let start_date = require_cstr!(start_date, empty);
        args.insert(
            "start_date".to_string(),
            thetadatadx::EndpointArgValue::Str(start_date.to_string()),
        );
        let end_date = require_cstr!(end_date, empty);
        args.insert(
            "end_date".to_string(),
            thetadatadx::EndpointArgValue::Str(end_date.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_greeks_eod", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch all Greeks history for an option contract (intraday, sampled by interval).
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_greeks_all_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_greeks_all", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch all Greeks on each trade for an option contract.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_trade_greeks_all_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_trade_greeks_all", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch first-order Greeks history (intraday, sampled by interval).
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_greeks_first_order_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_greeks_first_order", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch first-order Greeks on each trade for an option contract.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_trade_greeks_first_order_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_trade_greeks_first_order", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch second-order Greeks history (intraday, sampled by interval).
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_greeks_second_order_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_greeks_second_order", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch second-order Greeks on each trade for an option contract.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_trade_greeks_second_order_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_trade_greeks_second_order", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch third-order Greeks history (intraday, sampled by interval).
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_greeks_third_order_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_greeks_third_order", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch third-order Greeks on each trade for an option contract.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_trade_greeks_third_order_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_trade_greeks_third_order", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch implied volatility history (intraday, sampled by interval).
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_greeks_implied_volatility_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_greeks_implied_volatility", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch implied volatility on each trade for an option contract.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_history_trade_greeks_implied_volatility_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_history_trade_greeks_implied_volatility", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch the trade at a specific time of day across a date range for an option.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_at_time_trade_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    start_date: *const c_char
,
    end_date: *const c_char
,
    time_of_day: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );
        let start_date = require_cstr!(start_date, empty);
        args.insert(
            "start_date".to_string(),
            thetadatadx::EndpointArgValue::Str(start_date.to_string()),
        );
        let end_date = require_cstr!(end_date, empty);
        args.insert(
            "end_date".to_string(),
            thetadatadx::EndpointArgValue::Str(end_date.to_string()),
        );
        let time_of_day = require_cstr!(time_of_day, empty);
        args.insert(
            "time_of_day".to_string(),
            thetadatadx::EndpointArgValue::Str(time_of_day.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_at_time_trade", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch the quote at a specific time of day across a date range for an option.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_option_at_time_quote_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    expiration: *const c_char
,
    start_date: *const c_char
,
    end_date: *const c_char
,
    time_of_day: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let expiration = require_cstr!(expiration, empty);
        args.insert(
            "expiration".to_string(),
            thetadatadx::EndpointArgValue::Str(expiration.to_string()),
        );
        let start_date = require_cstr!(start_date, empty);
        args.insert(
            "start_date".to_string(),
            thetadatadx::EndpointArgValue::Str(start_date.to_string()),
        );
        let end_date = require_cstr!(end_date, empty);
        args.insert(
            "end_date".to_string(),
            thetadatadx::EndpointArgValue::Str(end_date.to_string()),
        );
        let time_of_day = require_cstr!(time_of_day, empty);
        args.insert(
            "time_of_day".to_string(),
            thetadatadx::EndpointArgValue::Str(time_of_day.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "option_at_time_quote", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch end-of-day index data for a date range.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_index_history_eod_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    start_date: *const c_char
,
    end_date: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let start_date = require_cstr!(start_date, empty);
        args.insert(
            "start_date".to_string(),
            thetadatadx::EndpointArgValue::Str(start_date.to_string()),
        );
        let end_date = require_cstr!(end_date, empty);
        args.insert(
            "end_date".to_string(),
            thetadatadx::EndpointArgValue::Str(end_date.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "index_history_eod", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch intraday OHLC bars for an index.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_index_history_ohlc_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    start_date: *const c_char
,
    end_date: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let start_date = require_cstr!(start_date, empty);
        args.insert(
            "start_date".to_string(),
            thetadatadx::EndpointArgValue::Str(start_date.to_string()),
        );
        let end_date = require_cstr!(end_date, empty);
        args.insert(
            "end_date".to_string(),
            thetadatadx::EndpointArgValue::Str(end_date.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "index_history_ohlc", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch intraday price history for an index.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_index_history_price_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "index_history_price", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch the index price at a specific time of day across a date range.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_index_at_time_price_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    start_date: *const c_char
,
    end_date: *const c_char
,
    time_of_day: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let start_date = require_cstr!(start_date, empty);
        args.insert(
            "start_date".to_string(),
            thetadatadx::EndpointArgValue::Str(start_date.to_string()),
        );
        let end_date = require_cstr!(end_date, empty);
        args.insert(
            "end_date".to_string(),
            thetadatadx::EndpointArgValue::Str(end_date.to_string()),
        );
        let time_of_day = require_cstr!(time_of_day, empty);
        args.insert(
            "time_of_day".to_string(),
            thetadatadx::EndpointArgValue::Str(time_of_day.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "index_at_time_price", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

/// Fetch end-of-day interest rate history.
///
/// Stream the result chunk-by-chunk through `callback` without
/// materialising the full response. `callback(rows, len, ctx)` is
/// invoked once per server chunk with a pointer to a contiguous run
/// of the endpoint's tick struct (the same layout the buffered
/// `_with_options` array returns); the chunk is freed before the next
/// is fetched, so peak memory tracks a single chunk. Accepts the same
/// optional builder parameters as the buffered form. Returns 0 on a
/// clean drain, -1 on error (inspect `thetadatadx_last_error`).
#[no_mangle]
pub unsafe extern "C" fn thetadatadx_interest_rate_history_eod_stream(
    client: *const ThetaDataDxMarketDataClient,
    symbol: *const c_char
,
    start_date: *const c_char
,
    end_date: *const c_char
,
    callback: Option<ThetaDataDxTickChunkCallback>,
    ctx: *mut c_void,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> i32 {
    ffi_boundary!(-1, {
        let empty = -1;
        let client = require_client!(client, empty);

        let mut args = thetadatadx::EndpointArgs::new();
        let symbol = require_cstr!(symbol, empty);
        args.insert(
            "symbol".to_string(),
            thetadatadx::EndpointArgValue::Str(symbol.to_string()),
        );
        let start_date = require_cstr!(start_date, empty);
        args.insert(
            "start_date".to_string(),
            thetadatadx::EndpointArgValue::Str(start_date.to_string()),
        );
        let end_date = require_cstr!(end_date, empty);
        args.insert(
            "end_date".to_string(),
            thetadatadx::EndpointArgValue::Str(end_date.to_string()),
        );

        if let Err(message) = apply_endpoint_request_options(&mut args, options) {
            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);
            return empty;
        }

        let Some(callback) = callback else {
            set_error("callback function pointer is null");
            return empty;
        };
        let sink = TickChunkSink { callback, ctx };
        match runtime().block_on(async {
            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, "interest_rate_history_eod", &args, move |rows, len| sink.emit(rows, len)).await
        }) {
            Ok(()) => 0,
            Err(error) => {
                set_error_from(&thetadatadx::Error::from(error));
                empty
            }
        }
    })
}

