// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml

/// Optional builder parameters for registry-driven endpoint requests over FFI.
///
/// Fields use simple C-friendly sentinels:
/// - integer/boolean/float fields: check the companion `has_*` flag
/// - string pointers: null means unset
///
/// `timeout_ms` is the cross-cutting per-call deadline. Set with the
/// companion `has_timeout_ms = 1`; on expiry the call returns an error and the
/// underlying gRPC stream is cancelled, leaving the client handle reusable.
#[repr(C)]
pub struct ThetaDataDxEndpointRequestOptions {
    /// Venue/exchange filter. Accepted values: `nqb`, `utp_cta`.
    pub venue: *const c_char,
    /// Minimum time filter
    pub min_time: *const c_char,
    /// Single date YYYYMMDD. Supply this for a single-day pull, or supply `start_date`/`end_date` for a range. When present, `date` takes precedence over the range.
    pub date: *const c_char,
    /// Interval preset. Defaults to `1s` when omitted — matching the upstream ThetaData Python library. Accepted values: `tick`, `10ms`, `100ms`, `500ms`, `1s`, `5s`, `10s`, `15s`, `30s`, `1m`, `5m`, `10m`, `15m`, `30m`, `1h`.
    pub interval: *const c_char,
    /// Start time filter
    pub start_time: *const c_char,
    /// End time filter
    pub end_time: *const c_char,
    /// Start date YYYYMMDD
    pub start_date: *const c_char,
    /// End date YYYYMMDD
    pub end_date: *const c_char,
    /// When true, quotes whose timestamp equals the trade timestamp are excluded; only quotes strictly before the trade are paired. Defaults to true, matching the terminal, which injects exclusive=true when the value is omitted.
    pub exclusive: i32,
    /// Presence flag for `exclusive`; set to `1` to apply the value.
    pub has_exclusive: i32,
    /// Strike price in dollars as a string (e.g. 500 or 17.5). Use `*` for wildcard selection.
    pub strike: *const c_char,
    /// Option side. Use `both` or `*` (alias) for calls and puts. Accepted values: `call`, `put`, `both`, `*`.
    pub right: *const c_char,
    /// Ticker symbol to filter by (e.g. AAPL). Omit to list every contract for the date.
    pub symbol: *const c_char,
    /// Maximum days to expiration
    pub max_dte: i32,
    /// Presence flag for `max_dte`; set to `1` to apply the value.
    pub has_max_dte: i32,
    /// Strike range filter
    pub strike_range: i32,
    /// Presence flag for `strike_range`; set to `1` to apply the value.
    pub has_strike_range: i32,
    /// Annualized expected dividend amount, in dollars per share, used in the Greeks calculation (e.g. 2.5 is $2.50 per share per year).
    pub annual_dividend: f64,
    /// Presence flag for `annual_dividend`; set to `1` to apply the value.
    pub has_annual_dividend: i32,
    /// Risk-free-rate source used in the Greeks calculation. Accepted values: `sofr`, `treasury_m1`, `treasury_m3`, `treasury_m6`, `treasury_y1`, `treasury_y2`, `treasury_y3`, `treasury_y5`, `treasury_y7`, `treasury_y10`, `treasury_y20`, `treasury_y30`.
    pub rate_type: *const c_char,
    /// Interest rate as a percent (4.36 means 4.36%, matching the InterestRateTick.rate convention) used in the Greeks calculation. Applied when rate_type selects a manual rate.
    pub rate_value: f64,
    /// Presence flag for `rate_value`; set to `1` to apply the value.
    pub has_rate_value: i32,
    /// Underlying price in dollars used in the Greeks calculation, overriding the observed underlying when set.
    pub stock_price: f64,
    /// Presence flag for `stock_price`; set to `1` to apply the value.
    pub has_stock_price: i32,
    /// Greeks model version. Accepted values: `latest`, `1`.
    pub version: *const c_char,
    /// When true, calculate Greeks against the option market value (mid-price) instead of the NBBO bid/ask pair.
    pub use_market_value: i32,
    /// Presence flag for `use_market_value`; set to `1` to apply the value.
    pub has_use_market_value: i32,
    /// When true, use the NBBO-derived underlyer price as the Greeks input instead of the last trade.
    pub underlyer_use_nbbo: i32,
    /// Presence flag for `underlyer_use_nbbo`; set to `1` to apply the value.
    pub has_underlyer_use_nbbo: i32,
    /// Per-call deadline in milliseconds; gated by `has_timeout_ms`.
    pub timeout_ms: u64,
    /// Presence flag for `timeout_ms`; set to `1` to apply the deadline.
    pub has_timeout_ms: i32,
}

// Layout drift-guard for the LP64 `#[repr(C)]` ABI contract shared with the C header.
const _: () = {
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, venue) == 0);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, min_time) == 8);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, date) == 16);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, interval) == 24);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, start_time) == 32);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, end_time) == 40);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, start_date) == 48);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, end_date) == 56);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, exclusive) == 64);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, has_exclusive) == 68);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, strike) == 72);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, right) == 80);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, symbol) == 88);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, max_dte) == 96);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, has_max_dte) == 100);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, strike_range) == 104);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, has_strike_range) == 108);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, annual_dividend) == 112);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, has_annual_dividend) == 120);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, rate_type) == 128);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, rate_value) == 136);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, has_rate_value) == 144);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, stock_price) == 152);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, has_stock_price) == 160);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, version) == 168);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, use_market_value) == 176);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, has_use_market_value) == 180);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, underlyer_use_nbbo) == 184);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, has_underlyer_use_nbbo) == 188);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, timeout_ms) == 192);
    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, has_timeout_ms) == 200);
    assert!(core::mem::size_of::<ThetaDataDxEndpointRequestOptions>() == 208);
    assert!(core::mem::align_of::<ThetaDataDxEndpointRequestOptions>() == 8);
};

fn apply_endpoint_request_options(
    args: &mut thetadatadx::EndpointArgs,
    options: *const ThetaDataDxEndpointRequestOptions,
) -> Result<(), String> {
    if options.is_null() {
        return Ok(());
    }

    // SAFETY: options is non-null (checked above) and the caller is required
    // to keep the ThetaDataDxEndpointRequestOptions alive for the duration of this call.
    let options = unsafe { &*options };
    insert_optional_str_arg(args, "venue", options.venue)?;
    insert_optional_str_arg(args, "min_time", options.min_time)?;
    insert_optional_str_arg(args, "date", options.date)?;
    insert_optional_str_arg(args, "interval", options.interval)?;
    insert_optional_str_arg(args, "start_time", options.start_time)?;
    insert_optional_str_arg(args, "end_time", options.end_time)?;
    insert_optional_str_arg(args, "start_date", options.start_date)?;
    insert_optional_str_arg(args, "end_date", options.end_date)?;
    if options.has_exclusive != 0 {
        insert_bool_arg(args, "exclusive", options.exclusive)?;
    }
    insert_optional_str_arg(args, "strike", options.strike)?;
    insert_optional_str_arg(args, "right", options.right)?;
    insert_optional_str_arg(args, "symbol", options.symbol)?;
    if options.has_max_dte != 0 {
        insert_int_arg(args, "max_dte", options.max_dte);
    }
    if options.has_strike_range != 0 {
        insert_int_arg(args, "strike_range", options.strike_range);
    }
    if options.has_annual_dividend != 0 {
        insert_float_arg(args, "annual_dividend", options.annual_dividend);
    }
    insert_optional_str_arg(args, "rate_type", options.rate_type)?;
    if options.has_rate_value != 0 {
        insert_float_arg(args, "rate_value", options.rate_value);
    }
    if options.has_stock_price != 0 {
        insert_float_arg(args, "stock_price", options.stock_price);
    }
    insert_optional_str_arg(args, "version", options.version)?;
    if options.has_use_market_value != 0 {
        insert_bool_arg(args, "use_market_value", options.use_market_value)?;
    }
    if options.has_underlyer_use_nbbo != 0 {
        insert_bool_arg(args, "underlyer_use_nbbo", options.underlyer_use_nbbo)?;
    }
    if options.has_timeout_ms != 0 {
        args.set_timeout_ms(options.timeout_ms);
    }
    Ok(())
}
