//! C++ SDK emitter.
//!
//! Generates the EndpointRequestOptions header, per-endpoint method
//! declarations and definitions on both the standalone `MarketDataClient`
//! and the unified client's `MarketData` view (returned by
//! `client.market_data()`), and the C-ABI-facing `_with_options` extern decl
//! header.

use std::fmt::Write as _;

use super::super::helpers::{endpoint_streams_repr_c_ticks, is_streaming_endpoint};
use super::super::model::{GeneratedEndpoint, GeneratedParam};
use super::super::sdk_helpers::{
    builder_copy_expr, builder_value_type_name, cpp_converter_expr, cpp_method_arg_decl,
    cpp_value_type, ffi_array_type, method_params, sdk_method_arg_name,
};

/// Renders the C++ `EndpointRequestOptions` header: the optional builder
/// fields, their `with_*` setters, and the internal FFI bridge struct.
pub(super) fn render_cpp_options(params: &[GeneratedParam]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n",
    );
    out.push_str(include_str!(
        "templates/cpp/endpoint_options_header.cpp.tmpl"
    ));
    for param in params {
        let ty = match param.param_type.as_str() {
            "Int" => "std::optional<int32_t>",
            "Float" => "std::optional<double>",
            "Bool" => "std::optional<bool>",
            _ => "std::optional<std::string>",
        };
        super::doc::doc_lines(&mut out, "    ", &param.description);
        writeln!(out, "    {} {};", ty, param.name).unwrap();
    }
    out.push_str("    /// Per-call deadline in milliseconds.\n");
    out.push_str("    std::optional<uint64_t> timeout_ms;\n");
    out.push('\n');
    for param in params {
        let arg_ty = builder_value_type_name(param);
        writeln!(
            out,
            "    EndpointRequestOptions& with_{}({} value) {{",
            param.name, arg_ty
        )
        .unwrap();
        writeln!(out, "        {};", builder_copy_expr(param, "value")).unwrap();
        out.push_str("        return *this;\n");
        out.push_str("    }\n");
    }
    out.push_str(include_str!("templates/cpp/with_timeout_ms.cpp.tmpl"));
    // A negative duration is rejected with `InvalidParameterError` rather
    // than coerced: the unsigned `timeout_ms` field cannot represent it,
    // and an `static_cast<uint64_t>` of a negative count would wrap to a
    // multi-century deadline — the opposite of the caller's intent. This
    // matches the reject-don't-coerce contract the other bindings hold for
    // the same out-of-domain deadline.
    out.push_str(include_str!("templates/cpp/with_deadline.cpp.tmpl"));
    out.push_str("};\n");
    out.push_str("\nnamespace detail {\n\n");
    out.push_str("struct FfiEndpointRequestOptions {\n");
    out.push_str("    ThetaDataDxEndpointRequestOptions raw{};\n");
    for param in params {
        if param.param_type != "Int" && param.param_type != "Float" && param.param_type != "Bool" {
            writeln!(out, "    std::string {}_storage;", param.name).unwrap();
        }
    }
    out.push('\n');
    out.push_str(
        "    explicit FfiEndpointRequestOptions(const EndpointRequestOptions& options) {\n",
    );
    for param in params {
        let template = match param.param_type.as_str() {
            "Int" | "Float" => include_str!("templates/cpp/ffi_numeric_case.cpp.tmpl"),
            "Bool" => include_str!("templates/cpp/ffi_bool_case.cpp.tmpl"),
            _ => include_str!("templates/cpp/ffi_string_case.cpp.tmpl"),
        };
        out.push_str(&template.replace("__PARAM__", &param.name));
    }
    out.push_str("        if (options.timeout_ms) {\n");
    out.push_str("            raw.timeout_ms = *options.timeout_ms;\n");
    out.push_str("            raw.has_timeout_ms = 1;\n");
    out.push_str("        }\n");
    out.push_str("    }\n");
    out.push('\n');
    out.push_str(include_str!(
        "templates/cpp/ffi_options_no_copy_move.cpp.tmpl"
    ));
    out.push_str("};\n\n");
    out.push_str("} // namespace detail\n");
    out
}

/// Renders the `MarketDataClient` member-function declarations for every
/// non-streaming endpoint, including the singular-symbol overloads. Each
/// blocking query is paired with an `<endpoint>_async` companion returning
/// a `std::future<std::vector<Row>>` so callers can run the request off the
/// calling thread without managing their own threads.
pub(super) fn render_cpp_market_data_decls(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "    // @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        // Use `///` line-comments rather than a `/** ... */` block so a
        // description containing `*/` cannot prematurely close the
        // doc-comment.
        super::doc::doc_lines(&mut out, "    ", &endpoint.description);
        let has_symbols = method_params(endpoint)
            .iter()
            .any(|param| param.param_type == "Symbols");
        if has_symbols {
            let mut params = method_params(endpoint)
                .iter()
                .map(|param| {
                    if param.param_type == "Symbols" {
                        "const std::string& symbol".to_string()
                    } else {
                        cpp_method_arg_decl(param)
                    }
                })
                .collect::<Vec<_>>();
            params.push("const EndpointRequestOptions& options = {}".into());
            // Tick-returning endpoints expose an optional presence out-param so
            // a caller can drive the projected Arrow export from the response.
            if endpoint.return_type != "StringList" {
                params.push("ColumnPresence* out_columns = nullptr".into());
            }
            writeln!(
                out,
                "    std::vector<{}> {}({}) const;\n",
                cpp_value_type(&endpoint.return_type),
                endpoint.name,
                params.join(", ")
            )
            .unwrap();
        }
        let mut params = method_params(endpoint)
            .iter()
            .map(|param| cpp_method_arg_decl(param))
            .collect::<Vec<_>>();
        // Every endpoint accepts EndpointRequestOptions now: even
        // endpoints with no other builder params can carry a timeout_ms.
        params.push("const EndpointRequestOptions& options = {}".into());
        // Tick-returning endpoints expose an optional presence out-param so
        // a caller can drive the projected Arrow export from the response.
        if endpoint.return_type != "StringList" {
            params.push("ColumnPresence* out_columns = nullptr".into());
        }
        writeln!(
            out,
            "    std::vector<{}> {}({}) const;\n",
            cpp_value_type(&endpoint.return_type),
            endpoint.name,
            params.join(", ")
        )
        .unwrap();
        // The async companions are inline header-only wrappers over the
        // blocking members declared just above, so they live with the
        // declarations rather than in the out-of-line `.cpp` fragment.
        out.push_str(&render_cpp_async_method(endpoint, has_symbols));
    }
    out
}

/// Renders the inline `<endpoint>_async` companion(s) for one buffered
/// endpoint. Each returns a `std::future<std::vector<Row>>` that runs the
/// matching blocking member on a fresh thread via
/// `std::async(std::launch::async, ...)` and fulfils the future with its
/// result; a throw from the blocking call is captured in the shared state
/// and re-raised on `future::get()`, so typed errors propagate unchanged.
///
/// Arguments are taken by value and moved into the task closure so the
/// future stays valid no matter when the caller invokes `get()` — the
/// closure owns its inputs rather than borrowing the caller's. The closure
/// also captures a COPY of the client (`self = *this`) and runs the blocking
/// member on that copy, so the FFI handle is co-owned for the future's whole
/// lifetime: a future may safely outlive the object it was launched from
/// (the captured copy shares the underlying `shared_ptr`, so the handle is
/// freed only once the last owner — object or in-flight future — drops).
/// The underlying handle is not thread-safe for concurrent calls (the C ABI
/// serialises per handle), so an `_async` request must not run concurrently
/// with another query on the same client; callers that fan out share one
/// client per in-flight request or synchronise externally, matching the
/// blocking surface's contract.
fn render_cpp_async_method(endpoint: &GeneratedEndpoint, has_symbols: bool) -> String {
    let mut out = String::new();
    let row = cpp_value_type(&endpoint.return_type);
    let async_name = format!("{}_async", endpoint.name);

    // Emit the singular-symbol overload first when the endpoint takes a
    // symbol list, mirroring the blocking surface's convenience overload.
    if has_symbols {
        out.push_str(&render_cpp_async_overload(
            endpoint,
            &row,
            &async_name,
            true,
        ));
    }
    out.push_str(&render_cpp_async_overload(
        endpoint,
        &row,
        &async_name,
        false,
    ));
    out
}

/// Renders one `<endpoint>_async` overload. When `singular`, a `Symbols`
/// parameter is presented as a single `std::string symbol`; otherwise it is
/// the full `std::vector<std::string> symbols`.
fn render_cpp_async_overload(
    endpoint: &GeneratedEndpoint,
    row: &str,
    async_name: &str,
    singular: bool,
) -> String {
    let mut out = String::new();
    // By-value parameter list: the task closure must own its inputs, so the
    // async surface takes values rather than the blocking surface's
    // `const T&`.
    let mut decls = Vec::new();
    let mut captures = Vec::new();
    let mut forwards = Vec::new();
    for param in method_params(endpoint) {
        let name = sdk_method_arg_name(param);
        if param.param_type == "Symbols" {
            if singular {
                decls.push("std::string symbol".to_string());
                captures.push("symbol = std::move(symbol)".to_string());
                forwards.push("symbol".to_string());
            } else {
                decls.push("std::vector<std::string> symbols".to_string());
                captures.push("symbols = std::move(symbols)".to_string());
                forwards.push("symbols".to_string());
            }
        } else {
            decls.push(format!("std::string {name}"));
            captures.push(format!("{name} = std::move({name})"));
            forwards.push(name);
        }
    }
    decls.push("EndpointRequestOptions options = {}".to_string());
    captures.push("options = std::move(options)".to_string());
    forwards.push("options".to_string());

    out.push_str(
        "    /// The detached task captures a copy of this object (`self = *this`), so the\n",
    );
    out.push_str(
        "    /// returned future co-owns the FFI handle and may safely outlive the object\n",
    );
    out.push_str(
        "    /// it was launched from — including a temporary `client.market_data()` view.\n",
    );
    out.push_str("    /// The handle is freed only once the last owner (this object or the\n");
    out.push_str("    /// in-flight future) drops, so there is no dangling-`this` window.\n");
    writeln!(
        out,
        "    std::future<std::vector<{row}>> {async_name}({}) const {{",
        decls.join(", ")
    )
    .unwrap();
    writeln!(
        out,
        "        return std::async(std::launch::async, [self = *this, {}]() {{",
        captures.join(", ")
    )
    .unwrap();
    writeln!(
        out,
        "            return self.{}({});",
        endpoint.name,
        forwards.join(", ")
    )
    .unwrap();
    out.push_str("        });\n");
    out.push_str("    }\n\n");
    out
}

/// One trailing argument list shared by the `<endpoint>_stream` declaration
/// and definition: the endpoint's positional params, the typed chunk handler,
/// and the trailing `EndpointRequestOptions`. `default_options` controls the
/// `= {}` default arg, present on the in-class declaration and absent on the
/// out-of-line definition (a redefaulted parameter is ill-formed in C++).
fn cpp_stream_signature(endpoint: &GeneratedEndpoint, default_options: bool) -> String {
    let tick = cpp_value_type(&endpoint.return_type);
    let mut params = method_params(endpoint)
        .iter()
        .map(|param| cpp_method_arg_decl(param))
        .collect::<Vec<_>>();
    params.push(format!("std::function<void(Span<const {tick}>)> handler"));
    let options = if default_options {
        "const EndpointRequestOptions& options = {}"
    } else {
        "const EndpointRequestOptions& options"
    };
    params.push(options.into());
    params.join(", ")
}

/// Emit the `<endpoint>_stream(...)` server-stream method *declarations* on the
/// C++ `MarketData` view (returned by `client.market_data()`), included in the
/// class body via `thetadatadx-cpp/include/market_data_stream.hpp.inc`.
///
/// Declarations only — the definitions live out-of-line in
/// `market_data_stream.cpp.inc` (mirroring the buffered `market_data.cpp.inc`).
/// Keeping the C-ABI `thetadatadx_<endpoint>_stream` call sites out of the class body
/// is also what stops the cross-binding parity collector — which scans class
/// bodies for `name(` shapes — from mistaking a C-ABI call for a C++ method.
/// The one inline member is the shared trampoline
/// `stream_chunk_shim`: tick-agnostic (the erased handler carries the per-
/// endpoint reinterpretation) and `thetadatadx_`-free, so it is safe inline. It
/// swallows exceptions — a throw must never unwind across the C ABI into Rust,
/// the same contract the FPSS `callback_shim` holds.
pub(super) fn render_cpp_stream_decls(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "    // @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );

    out.push_str(include_str!("templates/cpp/stream_chunk_shim.cpp.tmpl"));
    out.push('\n');

    for endpoint in endpoints
        .iter()
        .filter(|endpoint| endpoint_streams_repr_c_ticks(endpoint))
    {
        let tick = cpp_value_type(&endpoint.return_type);

        super::doc::doc_lines(&mut out, "    ", &endpoint.description);
        out.push_str("    ///\n");
        writeln!(
            out,
            "    /// Stream `{}` rows into `handler` without materialising the full",
            endpoint.name
        )
        .unwrap();
        out.push_str("    /// response. `handler` is invoked once per server chunk with a\n");
        writeln!(
            out,
            "    /// `Span<const {tick}>` view over a contiguous run of rows; the chunk is"
        )
        .unwrap();
        out.push_str("    /// freed before the next is fetched, so peak memory tracks a single\n");
        out.push_str("    /// chunk rather than the whole result. Carries the same optional\n");
        out.push_str("    /// builder parameters and `timeout_ms` as the buffered method via\n");
        out.push_str("    /// `options`. Throws on a wire or decode error once the stream\n");
        out.push_str("    /// drains; the `Span` is valid only for the duration of each call.\n");
        writeln!(
            out,
            "    void {}_stream({}) const;\n",
            endpoint.name,
            cpp_stream_signature(endpoint, true),
        )
        .unwrap();
    }
    out
}

/// Emit the out-of-line `Client::<endpoint>_stream(...)`
/// definitions, included in `thetadatadx.cpp` via
/// `thetadatadx-cpp/src/market_data_stream.cpp.inc`.
///
/// Each borrows the market-data `ThetaDataDxMarketDataClient*` from the unified handle
/// (`thetadatadx_client_market_data`), builds the same `EndpointRequestOptions` the
/// buffered methods take, erases the typed `handler` to a
/// `std::function<void(const void*, size_t)>` that reinterprets each chunk
/// pointer as the endpoint's tick type, and drives the C-ABI
/// `thetadatadx_<endpoint>_stream` entry point through the shared `stream_chunk_shim`
/// trampoline. The handler and the erased wrapper live on the stack for the
/// synchronous drain — the C ABI blocks until the stream completes and only
/// fires the callback during that call, so no heap lifetime juggling is
/// needed (unlike the long-lived FPSS push callback).
pub(super) fn render_cpp_stream_defs(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );

    for endpoint in endpoints
        .iter()
        .filter(|endpoint| endpoint_streams_repr_c_ticks(endpoint))
    {
        let method_params = method_params(endpoint);
        let tick = cpp_value_type(&endpoint.return_type);

        writeln!(
            out,
            "void MarketData::{}_stream({}) const {{",
            endpoint.name,
            cpp_stream_signature(endpoint, false),
        )
        .unwrap();
        out.push_str("    const ThetaDataDxMarketDataClient* hist = market_data_handle();\n");
        out.push_str("    detail::FfiEndpointRequestOptions ffi_options(options);\n");
        // Clear any stale FFI error so a -1 return is attributed to this call.
        out.push_str("    thetadatadx_clear_error();\n");
        // Reject an empty handler up front: calling it throws
        // bad_function_call, which the noexcept shim must swallow -> a silent
        // no-op stream. Fail loudly instead.
        writeln!(
            out,
            "    if (!handler) {{\n        throw InvalidParameterError(\"thetadatadx: {}_stream handler must not be empty\");\n    }}",
            endpoint.name
        )
        .unwrap();
        // Erase the typed handler into the shim context, which also carries a
        // slot for the first exception the handler throws so it can be
        // rethrown after the drain rather than silently lost. The borrow of
        // `handler` is sound because both live to the end of this synchronous
        // call.
        writeln!(
            out,
            "    StreamHandlerCtx ctx{{\n        [&handler](const void* rows, std::size_t len) {{\n            handler(Span<const {tick}>(static_cast<const {tick}*>(rows), len));\n        }},\n        {{}},\n    }};"
        )
        .unwrap();
        write!(
            out,
            "    int32_t rc = thetadatadx_{}_stream(hist",
            endpoint.name
        )
        .unwrap();
        for param in &method_params {
            write!(out, ", {}.c_str()", sdk_method_arg_name(param)).unwrap();
        }
        out.push_str(", &MarketData::stream_chunk_shim, &ctx, &ffi_options.raw);\n");
        // A handler exception is the proximate cause; rethrow it before any
        // FFI drain error observed after delivery stopped.
        out.push_str("    if (ctx.error) {\n");
        out.push_str("        std::rethrow_exception(ctx.error);\n");
        out.push_str("    }\n");
        out.push_str("    if (rc != 0) {\n");
        out.push_str("        detail::throw_last_ffi_error();\n");
        out.push_str("    }\n");
        out.push_str("}\n\n");
    }
    out
}

/// C++ classes that carry the buffered market-data query surface. The
/// standalone `MarketDataClient` owns a `ThetaDataDxMarketDataClient*` directly;
/// the unified client's `MarketData` view (returned by `client.market_data()`)
/// borrows the unified handle and derives the market-data sub-handle. Both
/// expose a private `market_data_handle()` accessor, so the generated
/// definitions are identical apart from the qualifying class name and
/// compile against either at zero per-method cost.
const MARKET_DATA_IMPL_CLASSES: &[&str] = &["MarketDataClient", "MarketData"];

/// Renders the buffered market-data query member-function definitions for
/// every non-streaming endpoint onto each market-data class, bridging each
/// into its `_with_options` FFI call.
pub(super) fn render_cpp_market_data_defs(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );
    for class_name in MARKET_DATA_IMPL_CLASSES {
        for endpoint in endpoints
            .iter()
            .filter(|endpoint| !is_streaming_endpoint(endpoint))
        {
            out.push_str(&render_cpp_endpoint_def(endpoint, class_name));
            out.push('\n');
        }
    }
    out
}

fn render_cpp_endpoint_def(endpoint: &GeneratedEndpoint, class_name: &str) -> String {
    let method_params = method_params(endpoint);
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    let mut signature_parts = method_params
        .iter()
        .map(|param| cpp_method_arg_decl(param))
        .collect::<Vec<_>>();
    // Every endpoint accepts EndpointRequestOptions so callers can
    // pass at least the cross-cutting deadline.
    signature_parts.push("const EndpointRequestOptions& options".into());
    // Tick-returning endpoints take an optional presence out-param (`nullptr`
    // to skip); `StringList` results carry no column set.
    let has_presence = endpoint.return_type != "StringList";
    if has_presence {
        signature_parts.push("ColumnPresence* out_columns".into());
    }

    let mut out = String::new();
    if has_symbols {
        let mut singular_parts = method_params
            .iter()
            .map(|param| {
                if param.param_type == "Symbols" {
                    "const std::string& symbol".to_string()
                } else {
                    cpp_method_arg_decl(param)
                }
            })
            .collect::<Vec<_>>();
        singular_parts.push("const EndpointRequestOptions& options".into());
        if has_presence {
            singular_parts.push("ColumnPresence* out_columns".into());
        }
        writeln!(
            out,
            "std::vector<{}> {}::{}({}) const {{",
            cpp_value_type(&endpoint.return_type),
            class_name,
            endpoint.name,
            singular_parts.join(", ")
        )
        .unwrap();
        let forwarded = method_params
            .iter()
            .map(|param| {
                if param.param_type == "Symbols" {
                    "std::vector<std::string>{symbol}".to_string()
                } else {
                    sdk_method_arg_name(param)
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        if has_presence {
            writeln!(
                out,
                "    return {}({}, options, out_columns);",
                endpoint.name, forwarded
            )
            .unwrap();
        } else {
            writeln!(out, "    return {}({}, options);", endpoint.name, forwarded).unwrap();
        }
        out.push_str("}\n\n");
    }
    writeln!(
        out,
        "std::vector<{}> {}::{}({}) const {{",
        cpp_value_type(&endpoint.return_type),
        class_name,
        endpoint.name,
        signature_parts.join(", ")
    )
    .unwrap();

    if has_symbols {
        out.push_str("    auto symbol_ptrs = detail::string_ptrs(symbols);\n");
    }
    out.push_str("    detail::FfiEndpointRequestOptions ffi_options(options);\n");
    // Clear any stale FFI error before the call so check_string_array /
    // check_tick_array can disambiguate "success-empty" from
    // "failure-with-empty-sentinel" (e.g. timeout). See
    // thetadatadx-ffi/src/lib.rs::thetadatadx_clear_error.
    out.push_str("    thetadatadx_clear_error();\n");

    if endpoint.return_type == "StringList" {
        write!(
            out,
            "    return detail::check_string_array(thetadatadx_{}_with_options",
            endpoint.name
        )
        .unwrap();
        out.push_str("(market_data_handle()");
        for param in &method_params {
            if param.param_type == "Symbols" {
                out.push_str(", symbol_ptrs.data(), symbol_ptrs.size()");
            } else {
                write!(out, ", {}.c_str()", sdk_method_arg_name(param)).unwrap();
            }
        }
        out.push_str(", &ffi_options.raw));\n");
        out.push_str("}\n");
        return out;
    }

    if endpoint.return_type == "OptionContracts" {
        out.push_str("    ThetaDataDxColumnPresence presence_raw{nullptr, 0};\n");
        write!(
            out,
            "    ThetaDataDxOptionContractArray arr = thetadatadx_{}_with_options",
            endpoint.name
        )
        .unwrap();
        out.push_str("(market_data_handle()");
        for param in &method_params {
            if param.param_type == "Symbols" {
                out.push_str(", symbol_ptrs.data(), symbol_ptrs.size()");
            } else {
                write!(out, ", {}.c_str()", sdk_method_arg_name(param)).unwrap();
            }
        }
        out.push_str(", &ffi_options.raw, out_columns ? &presence_raw : nullptr);\n");
        out.push_str(
            "    if (out_columns != nullptr) { *out_columns = ColumnPresence(presence_raw); }\n",
        );
        // Disambiguate empty-success vs failure-empty (e.g. timeout). See
        // thetadatadx-ffi/src/lib.rs::thetadatadx_clear_error and the matching call before the FFI.
        out.push_str(include_str!(
            "templates/cpp/option_contracts_convert.cpp.tmpl"
        ));
        return out;
    }

    out.push_str("    ThetaDataDxColumnPresence presence_raw{nullptr, 0};\n");
    write!(
        out,
        "    auto arr = thetadatadx_{}_with_options",
        endpoint.name
    )
    .unwrap();
    out.push_str("(market_data_handle()");
    for param in &method_params {
        if param.param_type == "Symbols" {
            out.push_str(", symbol_ptrs.data(), symbol_ptrs.size()");
        } else {
            write!(out, ", {}.c_str()", sdk_method_arg_name(param)).unwrap();
        }
    }
    out.push_str(", &ffi_options.raw, out_columns ? &presence_raw : nullptr);\n");
    out.push_str(
        "    if (out_columns != nullptr) { *out_columns = ColumnPresence(presence_raw); }\n",
    );
    writeln!(out, "    {}", cpp_converter_expr(&endpoint.return_type)).unwrap();
    out.push_str("}\n");
    out
}

/// Renders the C-ABI-facing `extern` declarations for every endpoint's
/// `thetadatadx_<endpoint>_with_options` C entry point.
pub(super) fn render_c_endpoint_with_options_decls(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "/* @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml */\n",
    );
    out.push_str(
        "/* Endpoints that return rows accept an optional out_presence pointer. Pass NULL to skip it.\n",
    );
    out.push_str(
        " * On success the function writes an owned ThetaDataDxColumnPresence that must be\n",
    );
    out.push_str(
        " * released with thetadatadx_column_presence_free. On failure it writes EMPTY;\n",
    );
    out.push_str(" * freeing EMPTY is safe but not required. */\n");
    // All non-streaming endpoints now have a `_with_options` form.
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        let ffi_name = format!("thetadatadx_{}_with_options", endpoint.name);
        let return_type = ffi_array_type(&endpoint.return_type);
        let params = method_params(endpoint);
        write!(
            out,
            "extern {} {}(const ThetaDataDxMarketDataClient* client",
            return_type, ffi_name
        )
        .unwrap();
        for param in &params {
            if param.param_type == "Symbols" {
                write!(out, ", const char* const* symbols, size_t symbols_len").unwrap();
            } else {
                write!(out, ", const char* {}", param.name).unwrap();
            }
        }
        out.push_str(", const ThetaDataDxEndpointRequestOptions* options");
        // Tick-returning endpoints append the wire-column presence out-param
        // (null to skip); `StringList` results carry no column set.
        if endpoint.return_type != "StringList" {
            out.push_str(", ThetaDataDxColumnPresence* out_presence");
        }
        out.push_str(");\n");
    }
    out
}
