//! C-ABI FFI emitter.
//!
//! Two families of outputs:
//! * `ThetaDataDxEndpointRequestOptions` — the shared `#[repr(C)]` struct carrying
//!   optional builder parameters over the ABI, plus its `apply_*` helper.
//! * `thetadatadx_<endpoint>_with_options` — one per endpoint that accepts builder
//!   params, bridging the C-call signature into the shared endpoint dispatch
//!   runtime.

use std::fmt::Write as _;

use super::super::helpers::{endpoint_streams_repr_c_ticks, is_streaming_endpoint};
use super::super::model::{GeneratedEndpoint, GeneratedParam};
use super::super::sdk_helpers::{
    c_option_value_type, ffi_array_type, ffi_from_vec_array_type, ffi_option_has_flag,
    ffi_option_insert_expr, ffi_option_value_type, ffi_output_variant, method_params,
};

/// Renders the Rust `#[repr(C)]` `ThetaDataDxEndpointRequestOptions` struct and
/// its `apply_*` helper that folds the options into the endpoint args.
pub(super) fn render_ffi_endpoint_request_options(params: &[GeneratedParam]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );
    out.push_str(include_str!(
        "templates/ffi/endpoint_options_header.rs.tmpl"
    ));
    for param in params {
        if param.description.trim().is_empty() {
            writeln!(out, "    /// Optional `{}` parameter.", param.name).unwrap();
        } else {
            super::doc::doc_lines(&mut out, "    ", &param.description);
        }
        writeln!(
            out,
            "    pub {}: {},",
            param.name,
            ffi_option_value_type(param)
        )
        .unwrap();
        if ffi_option_has_flag(param) {
            writeln!(
                out,
                "    /// Presence flag for `{}`; set to `1` to apply the value.",
                param.name
            )
            .unwrap();
            writeln!(out, "    pub has_{}: i32,", param.name).unwrap();
        }
    }
    out.push_str("    /// Per-call deadline in milliseconds; gated by `has_timeout_ms`.\n");
    out.push_str("    pub timeout_ms: u64,\n");
    out.push_str("    /// Presence flag for `timeout_ms`; set to `1` to apply the deadline.\n");
    out.push_str("    pub has_timeout_ms: i32,\n");
    out.push_str("}\n\n");
    // Layout drift-guard for the LP64 `#[repr(C)]` ABI contract shared with
    // the C header. Offsets are computed from the field list (in declaration
    // order) using repr(C) alignment rules, so adding or reordering a builder
    // param can never leave a stale literal behind.
    out.push_str(&render_request_options_layout_asserts(params));
    out.push_str("fn apply_endpoint_request_options(\n");
    out.push_str("    args: &mut thetadatadx::EndpointArgs,\n");
    out.push_str("    options: *const ThetaDataDxEndpointRequestOptions,\n");
    out.push_str(") -> Result<(), String> {\n");
    out.push_str("    if options.is_null() {\n        return Ok(());\n    }\n\n");
    out.push_str("    // SAFETY: options is non-null (checked above) and the caller is required\n");
    out.push_str(
        "    // to keep the ThetaDataDxEndpointRequestOptions alive for the duration of this call.\n",
    );
    out.push_str("    let options = unsafe { &*options };\n");
    for param in params {
        if !ffi_option_has_flag(param) {
            out.push_str(&ffi_option_insert_expr(param));
            out.push('\n');
        } else {
            writeln!(out, "    if options.has_{} != 0 {{", param.name).unwrap();
            out.push_str(&ffi_option_insert_expr(param));
            out.push('\n');
            out.push_str("    }\n");
        }
    }
    out.push_str("    if options.has_timeout_ms != 0 {\n");
    out.push_str("        args.set_timeout_ms(options.timeout_ms);\n");
    out.push_str("    }\n");
    out.push_str("    Ok(())\n");
    out.push_str("}\n");
    out
}

/// Size and alignment of an FFI scalar/pointer field type, for computing the
/// `#[repr(C)]` layout of `ThetaDataDxEndpointRequestOptions`. Panics on an
/// unmapped type so a new field kind fails the build rather than silently
/// producing a wrong offset guard.
fn ffi_field_size_align(ty: &str) -> (usize, usize) {
    let ty = ty.trim();
    if ty.contains('*') {
        (8, 8) // any pointer
    } else {
        match ty {
            "i32" => (4, 4),
            "u32" => (4, 4),
            "i64" | "u64" | "f64" => (8, 8),
            other => panic!(
                "ffi_field_size_align: unmapped ThetaDataDxEndpointRequestOptions field type {other:?}; \
                 add its size/align before adding a field of this type"
            ),
        }
    }
}

/// Emit the `const _: () = { .. }` layout drift-guard for
/// `ThetaDataDxEndpointRequestOptions`. Offsets are computed from the field
/// list in declaration order using repr(C) alignment, so the guard can never
/// carry a stale literal after a field is added or reordered.
fn render_request_options_layout_asserts(params: &[GeneratedParam]) -> String {
    // (field name, size, align) in exact declaration order — mirror the struct
    // emission above: each param's value field, then its `has_` flag (i32),
    // and finally the fixed `timeout_ms` (u64) + `has_timeout_ms` (i32) tail.
    let mut fields: Vec<(String, usize, usize)> = Vec::new();
    for param in params {
        let (size, align) = ffi_field_size_align(ffi_option_value_type(param));
        fields.push((param.name.clone(), size, align));
        if ffi_option_has_flag(param) {
            fields.push((format!("has_{}", param.name), 4, 4));
        }
    }
    fields.push(("timeout_ms".to_string(), 8, 8));
    fields.push(("has_timeout_ms".to_string(), 4, 4));

    let struct_align = fields.iter().map(|(_, _, a)| *a).max().unwrap_or(1);
    let mut out = String::new();
    out.push_str(
        "// Layout drift-guard for the LP64 `#[repr(C)]` ABI contract shared with the C header.\n",
    );
    out.push_str("const _: () = {\n");
    let mut offset = 0usize;
    for (name, size, align) in &fields {
        offset = offset.div_ceil(*align) * align;
        writeln!(
            out,
            "    assert!(core::mem::offset_of!(ThetaDataDxEndpointRequestOptions, {name}) == {offset});"
        )
        .unwrap();
        offset += size;
    }
    let struct_size = offset.div_ceil(struct_align) * struct_align;
    writeln!(
        out,
        "    assert!(core::mem::size_of::<ThetaDataDxEndpointRequestOptions>() == {struct_size});"
    )
    .unwrap();
    writeln!(
        out,
        "    assert!(core::mem::align_of::<ThetaDataDxEndpointRequestOptions>() == {struct_align});"
    )
    .unwrap();
    out.push_str("};\n\n");
    out
}

/// Renders the C `typedef struct ThetaDataDxEndpointRequestOptions` header with
/// one field (plus presence flag, where needed) per optional parameter.
pub(super) fn render_c_endpoint_request_options(params: &[GeneratedParam]) -> String {
    let mut out = String::new();
    out.push_str(
        "/* @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml */\n",
    );
    out.push_str("typedef struct {\n");
    for param in params {
        writeln!(out, "    {} {};", c_option_value_type(param), param.name).unwrap();
        if ffi_option_has_flag(param) {
            writeln!(out, "    int32_t has_{};", param.name).unwrap();
        }
    }
    out.push_str("    /* Per-call deadline. Set has_timeout_ms = 1 to apply. */\n");
    out.push_str("    uint64_t timeout_ms;\n");
    out.push_str("    int32_t has_timeout_ms;\n");
    out.push_str("} ThetaDataDxEndpointRequestOptions;\n");
    out
}

/// Renders the `thetadatadx_<endpoint>_with_options` C-ABI export for every
/// non-streaming endpoint.
pub(super) fn render_ffi_with_options(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );
    // Every non-streaming endpoint gets a `_with_options` form so callers can
    // pass at least the cross-cutting `timeout_ms`. Endpoints without
    // builder params take a `ThetaDataDxEndpointRequestOptions` whose only meaningful
    // field is the deadline; the others stay at their unset sentinels.
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        out.push_str(&render_ffi_with_options_endpoint(endpoint));
        out.push('\n');
    }
    out
}

fn render_ffi_with_options_endpoint(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let array_type = ffi_array_type(&endpoint.return_type);
    let output_variant = ffi_output_variant(&endpoint.return_type);
    let from_vec_type = ffi_from_vec_array_type(&endpoint.return_type);
    let mut out = String::new();

    // Doc emission goes through `doc_lines` so embedded newlines
    // / quote / backslash in the upstream description cannot escape
    // the comment block.
    super::doc::doc_lines(&mut out, "", &endpoint.description);
    out.push_str("///\n/// Accepts optional builder parameters.\n");
    out.push_str("#[no_mangle]\n");
    write!(
        out,
        "pub unsafe extern \"C\" fn thetadatadx_{}_with_options(\n    client: *const ThetaDataDxMarketDataClient",
        endpoint.name
    )
    .unwrap();
    for param in &method_params {
        if param.param_type == "Symbols" {
            out.push_str(",\n    symbols: *const *const c_char,\n    symbols_len: usize");
        } else {
            writeln!(out, ",\n    {}: *const c_char", param.name).unwrap();
        }
    }
    out.push_str(",\n    options: *const ThetaDataDxEndpointRequestOptions,\n");
    // Tick-returning endpoints surface the response's wire-column presence
    // through a trailing out-param so a C/C++ caller can drive the projected
    // Arrow export from a real endpoint response. `StringList` results carry no
    // column set, so they keep the original signature.
    let has_presence = endpoint.return_type != "StringList";
    if has_presence {
        out.push_str("    out_presence: *mut ThetaDataDxColumnPresence,\n");
    }
    writeln!(out, ") -> {} {{", array_type).unwrap();
    // Wrap the entire body in `ffi_boundary!` so a panic inside
    // `runtime().block_on`, `apply_endpoint_request_options`, or any
    // converter never crosses the `extern "C"` boundary. Rust 1.81+
    // converts an unwinding panic across `extern "C"` into a process
    // abort (pre-1.81 it was UB); either way, killing the host process
    // from a library binding is unacceptable. Defaults to the empty
    // sentinel so callers see the same `data=null, len=0` they already
    // handle for real errors, and the panic payload is surfaced through
    // `thetadatadx_last_error()`.
    writeln!(out, "    ffi_boundary!({array_type}::EMPTY, {{").unwrap();
    writeln!(out, "        let empty = {array_type}::EMPTY;").unwrap();
    if has_presence {
        // Seed the out-param empty before any early return so every exit path
        // leaves a valid presence; the success arm overwrites it. Freed by the
        // caller via `thetadatadx_column_presence_free`.
        out.push_str("        if !out_presence.is_null() {\n");
        out.push_str("            // SAFETY: caller-supplied writable slot (checked non-null).\n");
        out.push_str("            unsafe { *out_presence = ThetaDataDxColumnPresence::EMPTY };\n");
        out.push_str("        }\n");
    }
    out.push_str("        let client = require_client!(client, empty);\n\n");
    out.push_str("        let mut args = thetadatadx::EndpointArgs::new();\n");

    for param in &method_params {
        if param.param_type == "Symbols" {
            // Indent the template body one extra level so everything lives
            // inside the `ffi_boundary!` block.
            let symbols_tmpl = include_str!("templates/ffi/symbols_extract.rs.tmpl");
            out.push_str(&indent_template(symbols_tmpl));
        } else {
            let cstr_tmpl =
                include_str!("templates/ffi/cstr_extract.rs.tmpl").replace("__NAME__", &param.name);
            out.push_str(&indent_template(&cstr_tmpl));
        }
    }

    out.push_str(
        "\n        if let Err(message) = apply_endpoint_request_options(&mut args, options) {\n",
    );
    out.push_str("            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);\n");
    out.push_str("            return empty;\n");
    out.push_str("        }\n\n");
    out.push_str("        match runtime().block_on(async {\n");
    writeln!(
        out,
        "            thetadatadx::endpoint::invoke_endpoint(&client.inner, {:?}, &args).await",
        endpoint.name
    )
    .unwrap();
    out.push_str("        }) {\n");
    if has_presence {
        // The variant now carries `Ticks<T>` (rows + wire column set). Clone the
        // presence, run the fallible `from_vec` first, and write the heap-owned
        // out-param ONLY on success: on a conversion error the function returns
        // the empty sentinel, so `out_presence` must stay the `EMPTY` seeded
        // above (writing it here would leak a `ColumnPresence` the caller never
        // frees on the error path).
        writeln!(
            out,
            "            Ok(thetadatadx::EndpointOutput::{}(values)) => {{",
            output_variant
        )
        .unwrap();
        out.push_str("                let columns = values.columns().clone();\n");
        writeln!(
            out,
            "                match {}::from_vec(values.into_vec()) {{",
            from_vec_type
        )
        .unwrap();
        out.push_str("                    Ok(arr) => {\n");
        out.push_str("                        if !out_presence.is_null() {\n");
        out.push_str(
            "                            // SAFETY: caller-supplied writable slot (checked non-null).\n",
        );
        out.push_str(
            "                            unsafe { *out_presence = ThetaDataDxColumnPresence::from_presence(&columns) };\n",
        );
        out.push_str("                        }\n");
        out.push_str("                        arr\n");
        out.push_str("                    }\n");
        out.push_str("                    Err(e) => {\n");
        out.push_str(
            "                        set_error(&format!(\"interior NUL in server string: {e}\"));\n",
        );
        out.push_str("                        empty\n");
        out.push_str("                    }\n");
        out.push_str("                }\n");
        out.push_str("            }\n");
    } else {
        writeln!(
            out,
            "            Ok(thetadatadx::EndpointOutput::{}(values)) => match {}::from_vec(values) {{",
            output_variant, from_vec_type
        )
        .unwrap();
        out.push_str("                Ok(arr) => arr,\n");
        out.push_str("                Err(e) => {\n");
        out.push_str(
            "                    set_error(&format!(\"interior NUL in server string: {e}\"));\n",
        );
        out.push_str("                    empty\n");
        out.push_str("                }\n");
        out.push_str("            },\n");
    }
    out.push_str("            Ok(other) => {\n");
    writeln!(
        out,
        "                set_error(&format!(\"internal error: unexpected endpoint output for {}: {{other:?}}\"));",
        endpoint.name
    )
    .unwrap();
    out.push_str("                empty\n");
    out.push_str("            }\n");
    out.push_str("            Err(error) => {\n");
    // Convert the endpoint error into the core `Error` (preserving the
    // gRPC variant + its `retry_after` hint for server failures and
    // classifying bad params as invalid-parameter) and route through
    // `set_error_from` so the typed discriminant and the back-off hint
    // reach the C ABI; the C++ wrapper reads both to pick the right
    // exception leaf and seat `retry_after`.
    out.push_str("                set_error_from(&thetadatadx::Error::from(error));\n");
    out.push_str("                empty\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    })\n");
    out.push_str("}\n");
    out
}

/// Emit `thetadatadx-ffi/src/endpoint_stream.rs` — the `thetadatadx_<endpoint>_stream` server-
/// stream entry points, one per streaming endpoint (see
/// [`endpoint_streams_repr_c_ticks`]).
///
/// Each entry point is the C-ABI surface of the core `request.stream(handler)`
/// primitive: it builds the same `EndpointArgs` the buffered `_with_options`
/// form builds (reusing the identical positional + options extraction), then
/// drains the response chunk-by-chunk via `invoke_endpoint_stream`, handing
/// each chunk to the registered `ThetaDataDxTickChunkCallback`. The chunk pointer is
/// the same `#[repr(C)]` tick the buffered `thetadatadx_<endpoint>_with_options` array
/// exposes, so the callback sees zero re-marshaling — peak memory tracks a
/// single chunk rather than the full result.
pub(super) fn render_ffi_stream_endpoints(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );
    for endpoint in endpoints
        .iter()
        .filter(|e| endpoint_streams_repr_c_ticks(e))
    {
        out.push_str(&render_ffi_stream_endpoint(endpoint));
        out.push('\n');
    }
    out
}

fn render_ffi_stream_endpoint(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let mut out = String::new();

    super::doc::doc_lines(&mut out, "", &endpoint.description);
    out.push_str("///\n/// Stream the result chunk-by-chunk through `callback` without\n");
    out.push_str("/// materialising the full response. `callback(rows, len, ctx)` is\n");
    out.push_str("/// invoked once per server chunk with a pointer to a contiguous run\n");
    out.push_str("/// of the endpoint's tick struct (the same layout the buffered\n");
    out.push_str("/// `_with_options` array returns); the chunk is freed before the next\n");
    out.push_str("/// is fetched, so peak memory tracks a single chunk. Accepts the same\n");
    out.push_str("/// optional builder parameters as the buffered form. Returns 0 on a\n");
    out.push_str("/// clean drain, -1 on error (inspect `thetadatadx_last_error`).\n");
    out.push_str("#[no_mangle]\n");
    write!(
        out,
        "pub unsafe extern \"C\" fn thetadatadx_{}_stream(\n    client: *const ThetaDataDxMarketDataClient",
        endpoint.name
    )
    .unwrap();
    for param in &method_params {
        if param.param_type == "Symbols" {
            out.push_str(",\n    symbols: *const *const c_char,\n    symbols_len: usize");
        } else {
            writeln!(out, ",\n    {}: *const c_char", param.name).unwrap();
        }
    }
    out.push_str(",\n    callback: Option<ThetaDataDxTickChunkCallback>,\n    ctx: *mut c_void,\n");
    out.push_str("    options: *const ThetaDataDxEndpointRequestOptions,\n");
    out.push_str(") -> i32 {\n");
    // Reuse the panic boundary with an `i32` sentinel: a clean drain returns
    // 0, every failure path (null handle / arg, options error, wire / decode
    // error, or a caught panic) returns -1 with the reason in the FFI error
    // slot. `empty` is bound to -1 so the shared cstr / symbol extraction
    // templates — which `return empty` on a null or non-UTF-8 argument —
    // reuse verbatim.
    out.push_str("    ffi_boundary!(-1, {\n");
    out.push_str("        let empty = -1;\n");
    out.push_str("        let client = require_client!(client, empty);\n\n");
    out.push_str("        let mut args = thetadatadx::EndpointArgs::new();\n");

    for param in &method_params {
        if param.param_type == "Symbols" {
            let symbols_tmpl = include_str!("templates/ffi/symbols_extract.rs.tmpl");
            out.push_str(&indent_template(symbols_tmpl));
        } else {
            let cstr_tmpl =
                include_str!("templates/ffi/cstr_extract.rs.tmpl").replace("__NAME__", &param.name);
            out.push_str(&indent_template(&cstr_tmpl));
        }
    }

    out.push_str(
        "\n        if let Err(message) = apply_endpoint_request_options(&mut args, options) {\n",
    );
    out.push_str("            crate::error::set_error_with_code(&message, crate::error::THETADATADX_ERR_INVALID_PARAMETER);\n");
    out.push_str("            return empty;\n");
    out.push_str("        }\n\n");
    // A C caller can pass a null function pointer; modelling the parameter
    // as `Option` lets the null bit pattern be represented and rejected here,
    // before the sink is built, instead of being stored and invoked on a
    // runtime worker thread where a call through address 0 would fault the
    // process beyond the reach of the `ffi_boundary!` unwind guard.
    out.push_str("        let Some(callback) = callback else {\n");
    out.push_str("            set_error(\"callback function pointer is null\");\n");
    out.push_str("            return empty;\n");
    out.push_str("        };\n");
    // Bundle (callback, ctx) into the `Send` wrapper so the per-chunk closure
    // — which the core primitive may invoke from a runtime worker thread —
    // can carry the opaque pointer across the boundary. The wrapper never
    // dereferences `ctx`; it only hands it back to the user's `extern "C"`
    // function exactly as registered.
    out.push_str("        let sink = TickChunkSink { callback, ctx };\n");
    out.push_str("        match runtime().block_on(async {\n");
    writeln!(
        out,
        "            thetadatadx::endpoint::invoke_endpoint_stream(&client.inner, {:?}, &args, move |rows, len| sink.emit(rows, len)).await",
        endpoint.name
    )
    .unwrap();
    out.push_str("        }) {\n");
    out.push_str("            Ok(()) => 0,\n");
    out.push_str("            Err(error) => {\n");
    out.push_str("                set_error_from(&thetadatadx::Error::from(error));\n");
    out.push_str("                empty\n");
    out.push_str("            }\n");
    out.push_str("        }\n");
    out.push_str("    })\n");
    out.push_str("}\n");
    out
}

/// Emit the C header declarations for every `thetadatadx_<endpoint>_stream` symbol
/// into `thetadatadx-cpp/include/market_data_stream.h.inc`. The `ThetaDataDxTickChunkCallback`
/// typedef itself is hand-declared in `thetadatadx.h` (it is not endpoint-keyed);
/// these are just the per-endpoint `extern` prototypes the C++ wrapper and the
/// nm-based completeness gate consume.
pub(super) fn render_c_stream_decls(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "/* @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml */\n",
    );
    for endpoint in endpoints
        .iter()
        .filter(|e| endpoint_streams_repr_c_ticks(e))
    {
        let params = method_params(endpoint);
        write!(
            out,
            "extern int32_t thetadatadx_{}_stream(const ThetaDataDxMarketDataClient* client",
            endpoint.name
        )
        .unwrap();
        for param in &params {
            if param.param_type == "Symbols" {
                write!(out, ", const char* const* symbols, size_t symbols_len").unwrap();
            } else {
                write!(out, ", const char* {}", param.name).unwrap();
            }
        }
        out.push_str(", ThetaDataDxTickChunkCallback callback, void* ctx, const ThetaDataDxEndpointRequestOptions* options);\n");
    }
    out
}

/// Re-indent each non-empty line of an `include_str!` template by a single
/// 4-space level so it nests one scope deeper. Used when the template's
/// surrounding block moves inside `ffi_boundary!` — without the shift every
/// line would sit flush-left of the block and rustfmt would re-indent on
/// every regeneration.
fn indent_template(template: &str) -> String {
    template
        .lines()
        .map(|line| {
            if line.is_empty() {
                String::from("\n")
            } else {
                format!("    {line}\n")
            }
        })
        .collect()
}
