//! Python SDK `#[pymethods]` emitter.
//!
//! Renders `thetadatadx-py/src/_generated/market_data_methods.rs` — the `Client` impl
//! block that PyO3 compiles into the Python extension.
//!
//! Every method takes a `timeout_ms: Optional[int]` kwarg. When set the
//! call is given a deadline; on expiry a `RuntimeError` carrying the
//! `Error::Timeout` message is raised and the underlying gRPC stream is
//! cancelled. The `Client` handle remains usable for subsequent calls.
//!
//! # Three variants per endpoint (sync / async / fluent builder)
//!
//! The Python-UX surface exposes every market-data endpoint in three
//! forms without duplicating the spec:
//!
//! 1. **Sync `fn name(...)`** — original blocking signature; every kwarg is
//!    an `Option<T>`. Runs on the shared `runtime()` singleton (`OnceLock<
//!    tokio::runtime::Runtime>`) through `run_blocking` so Ctrl+C is
//!    honoured during long calls.
//! 2. **Async `fn name_async(...)`** — returns `Bound<'py, PyAny>` backed by
//!    `pyo3_async_runtimes::tokio::future_into_py`. Shares the same runtime
//!    singleton; no second runtime is created per call.
//! 3. **Fluent builder `fn name_builder(...)`** — returns a per-endpoint
//!    `#[pyclass]` whose chainable setters mirror the builder on the Rust
//!    side. Single terminal: `.list()` (and its `_async` companion),
//!    returning a typed list wrapper (`<TickName>List` / `StringList`).
//!    DataFrame terminals (`to_polars`, `to_arrow`, `to_pandas`,
//!    `to_list`) live on the wrapper, so builder users write
//!    `client.stock_history_eod_builder(...).list().to_polars()` instead
//!    of four parallel terminal methods.
//!
//! Every docstring in the three variants is produced by `compose_endpoint_doc`
//! + `render_rust_doc_block`, sourcing from `endpoint.description`
//! + `endpoint.vendor_docstring` in `endpoint_surface.toml` — single SSOT for
//!   all three variants so the sync / async / builder docs cannot drift.

use std::fmt::Write as _;

use super::super::helpers::{
    compose_endpoint_doc, direct_parser_name, is_streaming_endpoint, to_pascal_case,
};
use super::super::model::{GeneratedEndpoint, GeneratedParam};
use super::super::sdk_helpers::{
    builder_params, is_snapshot_endpoint, is_time_arg, method_params, python_method_arg_decl,
    python_optional_type, python_pyclass_list_class, python_pyclass_list_converter,
    python_pyclass_row_class, python_string_arg_type, python_vec_to_pylist_converter,
    render_rust_doc_block, sdk_method_arg_name, snapshot_returns_plain_pylist, write_timeout_call,
};

/// Emit `thetadatadx-py/src/_generated/decode_bench.rs` — the offline decode hook.
///
/// Exposes `decode_response_bytes(py, endpoint, chunks) -> list[TickClass]`
/// so Python benchmarks can feed recorded gRPC response bytes into the
/// Rust decoder without an MDDS round-trip. The dispatch arms are driven
/// by `endpoint_surface.toml`: every endpoint that today has a typed
/// decoder (i.e. `returns != "StringList"` and not a streaming endpoint)
/// gets a `match` arm automatically, so adding a new endpoint to the
/// TOML requires zero edits to this file.
pub(super) fn render_python_decode_bench(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n",
    );
    out.push_str("//\n");
    out.push_str("// Offline-decode hook used by the external parity bench harness:\n");
    out.push_str("// feed a recorded `Vec<&[u8]>` of `proto::ResponseData` chunks (one\n");
    out.push_str("// per on-the-wire gRPC frame) and receive the same typed pyclass\n");
    out.push_str("// list the corresponding endpoint would have returned. Separates\n");
    out.push_str("// DX decode cost from end-to-end wall time so benchmarks can\n");
    out.push_str("// attribute CPU to the parts of the stack they actually exercise.\n\n");

    // Imports are deliberately minimal: this file is `include!()`-d
    // into `thetadatadx-py/src/lib.rs`, so every PyO3 / pyo3::exceptions
    // / thetadatadx prelude symbol is already in scope at that seam.
    // Reaching for fully-qualified paths (`thetadatadx::decode::…`,
    // `pyo3::exceptions::PyValueError`) keeps the generator's output
    // free of use-statement collisions at the include site.

    // Helper: decode a chunk stream into a merged DataTable. Shared
    // across every dispatch arm.
    out.push_str(include_str!(
        "templates/python/decode_response_bytes_helper.rs.tmpl"
    ));

    // The pyfunction itself.
    out.push_str("/// Decode recorded gRPC response bytes into the same typed pyclass list\n");
    out.push_str("/// the matching `Client` endpoint would have returned.\n");
    out.push_str("///\n");
    out.push_str("/// `endpoint` must match an endpoint name from `endpoint_surface.toml` that\n");
    out.push_str(
        "/// exposes a typed decoder (every entry whose `returns` is not `StringList`).\n",
    );
    out.push_str(
        "/// `chunks` is the recorded byte list — one prost-encoded `proto::ResponseData`\n",
    );
    out.push_str("/// per entry, same frame boundaries tonic hands out of `Streaming::next()`.\n");
    out.push_str("///\n");
    out.push_str("/// Unknown `endpoint` values return [`PyValueError`] — the caller is\n");
    out.push_str("/// expected to stage the right fixture for the right endpoint.\n");
    out.push_str("#[pyfunction]\n");
    out.push_str("#[pyo3(signature = (endpoint, chunks))]\n");
    out.push_str(
        "pub(crate) fn decode_response_bytes(py: Python<'_>, endpoint: &str, chunks: Vec<Vec<u8>>) -> PyResult<Py<PyAny>> {\n",
    );
    out.push_str("    let refs: Vec<&[u8]> = chunks.iter().map(Vec::as_slice).collect();\n");
    out.push_str("    match endpoint {\n");

    // Dispatch arms. Skip streaming endpoints (they don't collect into
    // a single DataTable) and StringList endpoints (those return
    // `Vec<String>`, not a tick list — trivial decode, not worth a
    // bench arm).
    let mut bench_endpoints: Vec<&GeneratedEndpoint> = endpoints
        .iter()
        .filter(|e| !is_streaming_endpoint(e))
        .filter(|e| e.return_type != "StringList")
        .collect();
    bench_endpoints.sort_by(|a, b| a.name.cmp(&b.name));

    for endpoint in bench_endpoints {
        // `direct_parser_name` returns `decode::parse_xxx_ticks`; prefix
        // with `thetadatadx::` so the generator output works from the
        // Python SDK crate (which depends on `thetadatadx` but does not
        // `use` the module at top level — see the include-site comment).
        let parser = direct_parser_name(&endpoint.return_type)
            .strip_prefix("decode::")
            .map(|rest| format!("thetadatadx::decode::{rest}"))
            .unwrap_or_else(|| {
                panic!(
                    "direct_parser_name '{}' must start with 'decode::'",
                    direct_parser_name(&endpoint.return_type)
                )
            });
        let pyclass_fn = python_pyclass_list_converter(&endpoint.return_type);
        let row_class = python_pyclass_row_class(&endpoint.return_type);
        writeln!(out, "        \"{name}\" => {{", name = endpoint.name).unwrap();
        writeln!(
            out,
            "            let table = decode_chunks_into_table(&refs)?;"
        )
        .unwrap();
        writeln!(
            out,
            "            let rows = {parser}(&table).map_err(|e| pyo3::exceptions::PyRuntimeError::new_err(e.to_string()))?;"
        )
        .unwrap();
        // Pair the decoded rows with the recorded response's wire columns so
        // the bench list projects exactly as the live endpoint would.
        writeln!(
            out,
            "            let header_refs: Vec<&str> = table.headers.iter().map(String::as_str).collect();"
        )
        .unwrap();
        writeln!(
            out,
            "            let columns = <tick::{row_class} as thetadatadx::WireColumns>::present_columns(&header_refs);"
        )
        .unwrap();
        // Carry the response's `symbol` (root) as the leading column, matching
        // the live collector (`mdds::macros` `collect_stream` path): a constant
        // broadcast (option/index, single-symbol snapshot), a per-row column (a
        // multi-symbol snapshot, one value per row), or neither (stock history).
        writeln!(
            out,
            "            let columns = if columns.contains(\"symbol\") {{ columns }} else {{ match thetadatadx::decode::response_symbol(&table) {{ thetadatadx::decode::ResponseSymbol::Constant(symbol) => columns.with_symbol(symbol), thetadatadx::decode::ResponseSymbol::PerRow(symbols) => columns.with_symbols(symbols), thetadatadx::decode::ResponseSymbol::Absent => columns }} }};"
        )
        .unwrap();
        writeln!(
            out,
            "            let ticks = thetadatadx::Ticks::new(rows, columns);"
        )
        .unwrap();
        // `*_to_pyclass_list` now returns `Py<<TickName>List>`; the public
        // parity-bench hook keeps its `Py<PyAny>` signature, so erase the
        // concrete class on the way out.
        writeln!(out, "            Ok({pyclass_fn}(py, ticks)?.into_any())").unwrap();
        out.push_str("        }\n");
    }

    out.push_str("        other => Err(PyValueError::new_err(format!(\n");
    out.push_str(
        "            \"decode_response_bytes: unknown endpoint `{other}` — extend endpoint_surface.toml and regen `cargo run --bin generate_sdk_surfaces`\"\n",
    );
    out.push_str("        ))),\n");
    out.push_str("    }\n");
    out.push_str("}\n");
    out
}

/// Renders the Python market-data surface: per-endpoint builder
/// pyclasses, their module registrar, and the `Client`
/// `#[pymethods]` block with sync, async, and builder variants.
pub(super) fn render_python_market_data_methods(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );

    // Per-endpoint fluent builder pyclasses. Emitted BEFORE the `Client`
    // impl block so `add_class::<MarketDataBuilder>()` at module-init time sees
    // the types. One struct per endpoint; each has chained setters for the
    // optional params, required params captured at construction time, and
    // a single terminal `.list()` (+ `.list_async()`) that returns the
    // typed list wrapper. DataFrame terminals (`to_polars`, `to_arrow`,
    // `to_pandas`, `to_list`) live on the wrapper itself.
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        out.push_str(&render_python_endpoint_builder(endpoint));
        out.push('\n');
    }

    // Module-init registrar for the generated builders. Called from
    // `lib.rs::thetadatadx_py` so every builder class lands in the
    // `thetadatadx` Python namespace.
    out.push_str(
        "fn register_generated_market_data_builders(m: &Bound<'_, PyModule>) -> PyResult<()> {\n",
    );
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        writeln!(
            out,
            "    m.add_class::<{}>()?;",
            endpoint_builder_struct(&endpoint.name)
        )
        .unwrap();
    }
    out.push_str("    Ok(())\n");
    out.push_str("}\n\n");

    out.push_str("#[pymethods]\n");
    out.push_str("impl MarketDataView {\n");
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        // Sync — preserves the original blocking signature byte-for-byte.
        out.push_str(&render_python_endpoint_sync(endpoint));
        out.push('\n');
        // Async — awaitable via pyo3-async-runtimes.
        out.push_str(&render_python_endpoint_async(endpoint));
        out.push('\n');
        // Fluent builder constructor.
        out.push_str(&render_python_builder_constructor(endpoint));
        out.push('\n');
    }
    out.push_str("}\n");
    out
}

// ───────────────────────── Sync (original blocking signature) ─────────────

fn render_python_endpoint_sync(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let is_string_list = endpoint.return_type == "StringList";
    let builder_params = if is_string_list {
        Vec::new()
    } else {
        builder_params(endpoint)
    };
    let is_snapshot = is_snapshot_endpoint(endpoint);
    let snapshot_plain_list = snapshot_returns_plain_pylist(endpoint);
    let mut out = String::new();

    let doc = compose_endpoint_doc(endpoint);
    out.push_str(&render_rust_doc_block("    ", &doc));

    let mut signature_parts = method_params
        .iter()
        .map(|param| sdk_method_arg_name(param))
        .collect::<Vec<_>>();
    signature_parts.push("*".into());
    signature_parts.extend(
        builder_params
            .iter()
            .map(|param| python_signature_kwarg(param)),
    );
    signature_parts.push("timeout_ms=None".into());
    writeln!(
        out,
        "    #[pyo3(signature = ({}))]",
        signature_parts.join(", ")
    )
    .unwrap();

    writeln!(out, "    fn {}(", endpoint.name).unwrap();
    out.push_str("        &self,\n");
    out.push_str("        py: Python<'_>,\n");
    for param in &method_params {
        writeln!(out, "        {},", python_method_arg_decl(param)).unwrap();
    }
    for param in &builder_params {
        writeln!(
            out,
            "        {}: {},",
            param.name,
            python_optional_type(param)
        )
        .unwrap();
    }
    out.push_str("        timeout_ms: Option<u64>,\n");
    out.push_str("    ) -> PyResult<");
    if is_string_list {
        // Chained return: `endpoint(...).to_polars()` — `StringList`
        // carries both the `Vec<String>` payload and the DataFrame
        // column name pulled from `endpoint_surface.toml::list_column`.
        out.push_str("Py<StringList>> {\n");
    } else if snapshot_plain_list {
        // Snapshot fast-path: return a plain `Py<PyList>` of typed
        // pyclass rows. This is only safe for snapshots that cannot carry a
        // per-row symbol vector; multi-symbol snapshots need the list wrapper
        // to preserve row attribution.
        out.push_str("Py<pyo3::types::PyList>> {\n");
    } else {
        // Chained return: `endpoint(...).to_polars()` — typed list
        // wrapper per tick type, holds the decoder-owned `Vec<tick::T>`
        // and exposes `.to_list()` / `.to_arrow()` / `.to_pandas()` /
        // `.to_polars()` terminals.
        writeln!(
            out,
            "Py<{}>> {{",
            python_pyclass_list_class(&endpoint.return_type)
        )
        .unwrap();
    }

    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        out.push_str(
            "        let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
        );
    }

    if is_string_list {
        let positional_args = method_params
            .iter()
            .map(|param| {
                if param.param_type == "Symbols" {
                    "&refs".into()
                } else {
                    format!("{}.as_str()", sdk_method_arg_name(param))
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        let column = endpoint
            .list_column
            .as_deref()
            .expect("list endpoint must declare list_column");
        out.push_str("        let values: Vec<String> = run_blocking(py, async move {\n");
        writeln!(
            out,
            "            let call = self.client.market_data().{}({});",
            endpoint.name, positional_args
        )
        .unwrap();
        write_timeout_call(&mut out, "            ");
        out.push_str("        })?;\n");
        writeln!(
            out,
            "        strings_to_string_list(py, values, \"{column}\")"
        )
        .unwrap();
        out.push_str("    }\n");
        return out;
    }

    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("{}.as_str()", sdk_method_arg_name(param))
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "        let mut request = self.client.market_data().{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in &builder_params {
        writeln!(out, "        if let Some(value) = {} {{", param.name).unwrap();
        writeln!(
            out,
            "            request = request.{}({});",
            param.name,
            sync_setter_arg_expr(param)
        )
        .unwrap();
        out.push_str("        }\n");
    }
    out.push_str("        if let Some(ms) = timeout_ms {\n");
    out.push_str(
        "            request = request.with_deadline(std::time::Duration::from_millis(ms));\n",
    );
    out.push_str("        }\n");
    if is_snapshot {
        // Snapshots run through the same interruptible `run_blocking` path as
        // every other request: the timeout is the request's own deadline
        // (`timeout_ms`, else the configured request timeout), never a
        // wrapper-imposed cap. This branch exists only for the return-shape
        // split: plain-list snapshots keep the low-allocation `PyList`
        // materialiser; multi-symbol snapshots use the typed list wrapper so
        // `ColumnPresence::symbols()` survives to DataFrame terminals.
        out.push_str("        let ticks = run_blocking(py, async move { request.await })?;\n");
        if snapshot_plain_list {
            writeln!(
                out,
                "        {}(py, ticks)",
                python_vec_to_pylist_converter(&endpoint.return_type)
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "        {}(py, ticks)",
                python_pyclass_list_converter(&endpoint.return_type)
            )
            .unwrap();
        }
        out.push_str("    }\n");
        return out;
    }
    out.push_str("        let ticks = run_blocking(py, async move { request.await })?;\n");
    writeln!(
        out,
        "        {}(py, ticks)",
        python_pyclass_list_converter(&endpoint.return_type)
    )
    .unwrap();
    out.push_str("    }\n");
    out
}

// ───────────────────────── Async variant (`_async` suffix) ─────────────────

fn render_python_endpoint_async(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let is_string_list = endpoint.return_type == "StringList";
    let builder_params = if is_string_list {
        Vec::new()
    } else {
        builder_params(endpoint)
    };
    let snapshot_plain_list = snapshot_returns_plain_pylist(endpoint);
    let mut out = String::new();

    // Same composed doc as sync — readers of `name_async` see the same
    // vendor notes as readers of `name`. No drift.
    let mut doc = compose_endpoint_doc(endpoint);
    doc.push_str(
        "\n\nAsync companion — returns an awaitable (`asyncio.Future`).\n\
         Shares the same shared tokio runtime as the sync variant; no\n\
         second runtime is created per call.",
    );
    out.push_str(&render_rust_doc_block("    ", &doc));

    let mut signature_parts = method_params
        .iter()
        .map(|param| sdk_method_arg_name(param))
        .collect::<Vec<_>>();
    signature_parts.push("*".into());
    signature_parts.extend(
        builder_params
            .iter()
            .map(|param| format!("{}=None", param.name)),
    );
    signature_parts.push("timeout_ms=None".into());
    writeln!(
        out,
        "    #[pyo3(signature = ({}))]",
        signature_parts.join(", ")
    )
    .unwrap();

    writeln!(out, "    fn {}_async<'py>(", endpoint.name).unwrap();
    out.push_str("        &self,\n");
    out.push_str("        py: Python<'py>,\n");
    for param in &method_params {
        writeln!(out, "        {},", python_method_arg_decl(param)).unwrap();
    }
    for param in &builder_params {
        writeln!(
            out,
            "        {}: {},",
            param.name,
            python_optional_type(param)
        )
        .unwrap();
    }
    out.push_str("        timeout_ms: Option<u64>,\n");
    out.push_str("    ) -> PyResult<Bound<'py, PyAny>> {\n");

    // Clone the Arc<thetadatadx::Client> handle into the closure — the
    // inner client is not Clone but the Arc is, and the builder pyclass
    // pattern elsewhere in this file relies on the same contract.
    out.push_str("        let client = self.client.clone();\n");

    // `spawn_awaitable` is the hand-written async twin of `run_blocking` —
    // it wraps `pyo3_async_runtimes::tokio::future_into_py`, routes
    // `thetadatadx::Error` through `to_py_err`, and invokes `convert` with
    // a held GIL. One call per `*_async` emit keeps the generator output
    // symmetric with the sync path (one `run_blocking` per emit).
    out.push_str("        spawn_awaitable(py, async move {\n");

    if is_string_list {
        // List endpoints: call the `_with_deadline` variant when caller set
        // timeout_ms; otherwise the deadline-less call. The future returns
        // `Result<Vec<String>, thetadatadx::Error>`; `spawn_awaitable`
        // routes the error through `to_py_err` and hands the `Vec<String>`
        // to the `convert` closure with the GIL held.
        let has_symbols = method_params
            .iter()
            .any(|param| param.param_type == "Symbols");
        if has_symbols {
            out.push_str(
                "            let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
            );
        }
        let positional_args = method_params
            .iter()
            .map(|param| {
                if param.param_type == "Symbols" {
                    "&refs".into()
                } else {
                    format!("{}.as_str()", param.name)
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        let column = endpoint
            .list_column
            .as_deref()
            .expect("list endpoint must declare list_column");
        writeln!(
            out,
            "            let call = client.market_data().{}({});",
            endpoint.name, positional_args
        )
        .unwrap();
        write_timeout_call(&mut out, "            ");
        // Wrap the returned `Vec<String>` in a typed `StringList` with
        // the semantic column name so the caller can chain `.to_polars()`
        // into a single-column frame with a sensible header. `.into_any()`
        // coerces the `Py<StringList>` up to the `Py<PyAny>` the helper
        // signature demands.
        writeln!(
            out,
            "        }}, |py, values| strings_to_string_list(py, values, \"{column}\").map(|p| p.into_any()))"
        )
        .unwrap();
        out.push_str("    }\n");
        return out;
    }

    // Builder-backed endpoints: chain optional setters on the owned future.
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        out.push_str(
            "            let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
        );
    }
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("{}.as_str()", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "            let mut request = client.market_data().{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in &builder_params {
        writeln!(out, "            if let Some(value) = {} {{", param.name).unwrap();
        writeln!(
            out,
            "                request = request.{}({});",
            param.name,
            sync_setter_arg_expr(param)
        )
        .unwrap();
        out.push_str("            }\n");
    }
    out.push_str("            if let Some(ms) = timeout_ms {\n");
    out.push_str(
        "                request = request.with_deadline(std::time::Duration::from_millis(ms));\n",
    );
    out.push_str("            }\n");
    out.push_str("            request.await\n");
    // Convert back on the Python thread with GIL held. Plain-list snapshots
    // use the low-allocation pylist materialiser; multi-symbol snapshots and
    // parsed list endpoints keep the wrapper so callers can chain
    // `.to_polars()` and preserve symbol attribution. `.into_any()` coerces
    // either return type up to `Py<PyAny>` for the helper signature.
    if snapshot_plain_list {
        writeln!(
            out,
            "        }}, |py, ticks| {}(py, ticks).map(|p| p.into_any()))",
            python_vec_to_pylist_converter(&endpoint.return_type)
        )
        .unwrap();
    } else {
        writeln!(
            out,
            "        }}, |py, ticks| {}(py, ticks).map(|p| p.into_any()))",
            python_pyclass_list_converter(&endpoint.return_type)
        )
        .unwrap();
    }
    out.push_str("    }\n");
    out
}

fn python_signature_kwarg(param: &GeneratedParam) -> String {
    let Some(default) = param.default.as_deref() else {
        return format!("{}=None", param.name);
    };
    let value = match param.param_type.as_str() {
        "Bool" => default.to_string(),
        "Int" | "Float" => default.to_string(),
        _ => return format!("{}=None", param.name),
    };
    format!("{}={value}", param.name)
}

fn sync_setter_arg_expr(param: &GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Int" | "Float" | "Bool" => "value",
        _ => "value.as_str()",
    }
}

// ───────────────────────── Fluent builder (per-endpoint #[pyclass]) ────────
//
// The builder pattern is a Python-side ergonomics layer: chain setters,
// terminate with `.arrow()` / `.list()` / `.polars()` / `.pandas()`. The
// builder struct clones an `Arc<thetadatadx::Client>` from the owning
// `Client` pyclass (see lib.rs where the field is wrapped in Arc for
// exactly this reason), so terminal calls can drive the existing endpoint
// methods on the underlying client without re-authenticating or copying
// configuration. State captured at builder construction time: required
// args + accumulated optional kwargs + timeout_ms.

/// The name of the `#[pyclass]` builder emitted for this endpoint.
fn endpoint_builder_struct(name: &str) -> String {
    format!("{}Builder", to_pascal_case(name))
}

/// Setter field type inside the builder pyclass.
fn builder_field_optional_type(param: &GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Int" => "Option<i32>",
        "Float" => "Option<f64>",
        "Bool" => "Option<bool>",
        _ => "Option<String>",
    }
}

/// Setter parameter type on the builder pymethod (what Python passes in).
fn builder_setter_arg_type(param: &GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Int" => "i32",
        "Float" => "f64",
        "Bool" => "bool",
        "Date" | "Expiration" => "PyDateArg",
        _ if is_time_arg(param) => "PyTimeArg",
        _ => "PyStringArg",
    }
}

/// Convert the setter arg into the stored field.
fn builder_setter_store_expr(param: &GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        "Int" | "Float" | "Bool" => "Some(value)",
        _ => "Some(value.into_string())",
    }
}

/// Render the per-endpoint `#[pyclass]` builder. Emits the struct + its
/// `#[pymethods]` impl (setters + terminals).
fn render_python_endpoint_builder(endpoint: &GeneratedEndpoint) -> String {
    let struct_name = endpoint_builder_struct(&endpoint.name);
    let method_params = method_params(endpoint);
    let is_string_list = endpoint.return_type == "StringList";
    let builder_params = if is_string_list {
        Vec::new()
    } else {
        builder_params(endpoint)
    };
    // Snapshot endpoints (bounded rows) don't benefit from `.stream()`.
    let is_snapshot = is_snapshot_endpoint(endpoint);
    let mut out = String::new();

    // Struct definition. Setters mutate through `PyRefMut<'_, Self>`.
    let doc = compose_endpoint_doc(endpoint);
    out.push_str(&render_rust_doc_block("", &doc));
    writeln!(
        out,
        "#[pyclass(module = \"thetadatadx\", name = \"{}\")]",
        struct_name
    )
    .unwrap();
    writeln!(out, "pub struct {struct_name} {{").unwrap();
    // Same Arc the parent `Client` pyclass stores — cheap to clone,
    // so the async terminal can move it into the future.
    out.push_str("    client: std::sync::Arc<thetadatadx::Client>,\n");
    for param in &method_params {
        if param.param_type == "Symbols" {
            out.push_str("    symbols: Vec<String>,\n");
        } else {
            writeln!(out, "    {}: String,", param.name).unwrap();
        }
    }
    for param in &builder_params {
        writeln!(
            out,
            "    {}: {},",
            param.name,
            builder_field_optional_type(param)
        )
        .unwrap();
    }
    out.push_str("    timeout_ms: Option<u64>,\n");
    out.push_str("}\n\n");

    // Impl block.
    out.push_str("#[pymethods]\n");
    writeln!(out, "impl {struct_name} {{").unwrap();

    // Builder setters for optional params — chainable, mutate in place.
    for param in &builder_params {
        writeln!(out, "    /// Set `{}` on the pending request.", param.name).unwrap();
        writeln!(
            out,
            "    fn {}<'py>(mut slf: PyRefMut<'py, Self>, value: {}) -> PyRefMut<'py, Self> {{",
            param.name,
            builder_setter_arg_type(param)
        )
        .unwrap();
        writeln!(
            out,
            "        slf.{} = {};",
            param.name,
            builder_setter_store_expr(param)
        )
        .unwrap();
        out.push_str("        slf\n");
        out.push_str("    }\n\n");
    }

    // Required-param setters — allow chain `.symbol("AAPL").symbol("MSFT")`
    // to retarget a builder. Opt-in: callers happily compose at the
    // constructor site today.
    for param in &method_params {
        writeln!(
            out,
            "    /// Replace the required `{}` on the pending request.",
            param.name
        )
        .unwrap();
        if param.param_type == "Symbols" {
            writeln!(
                out,
                "    fn symbols<'py>(mut slf: PyRefMut<'py, Self>, value: PySymbols) -> PyRefMut<'py, Self> {{"
            )
            .unwrap();
            out.push_str("        slf.symbols = value.into_vec();\n");
            out.push_str("        slf\n");
            out.push_str("    }\n\n");
        } else {
            writeln!(
                out,
                "    fn {}<'py>(mut slf: PyRefMut<'py, Self>, value: {}) -> PyRefMut<'py, Self> {{",
                param.name,
                python_string_arg_type(param)
            )
            .unwrap();
            writeln!(out, "        slf.{} = value.into_string();", param.name).unwrap();
            out.push_str("        slf\n");
            out.push_str("    }\n\n");
        }
    }

    // Per-request deadline setter.
    out.push_str("    /// Apply a per-request deadline in milliseconds.\n");
    out.push_str(
        "    fn timeout_ms<'py>(mut slf: PyRefMut<'py, Self>, value: u64) -> PyRefMut<'py, Self> {\n",
    );
    out.push_str("        slf.timeout_ms = Some(value);\n");
    out.push_str("        slf\n");
    out.push_str("    }\n\n");

    // Single terminal per builder: `.list()` (sync) + `.list_async()`.
    // Returns the typed list wrapper (`StringList` or `<TickName>List`);
    // callers chain `.to_arrow()` / `.to_pandas()` / `.to_polars()` /
    // `.to_list()` off the wrapper to cross into the DataFrame world.
    // One terminal, one SSOT path, no drift across four variants.
    if is_string_list {
        let column = endpoint
            .list_column
            .as_deref()
            .expect("list endpoint must declare list_column");
        out.push_str("    /// Execute the request and return a typed `StringList` wrapper.\n");
        out.push_str("    ///\n");
        out.push_str(
            "    /// Chain `.to_polars()` / `.to_pandas()` / `.to_arrow()` / `.to_list()`\n",
        );
        out.push_str("    /// on the result to convert to the downstream representation.\n");
        out.push_str("    fn list(&self, py: Python<'_>) -> PyResult<Py<StringList>> {\n");
        write_sync_list_dispatch(&mut out, endpoint, &method_params, "        ");
        out.push_str("?;\n");
        writeln!(
            out,
            "        strings_to_string_list(py, values, \"{column}\")"
        )
        .unwrap();
        out.push_str("    }\n\n");

        out.push_str(
            "    /// Async companion to `list()` — awaitable yields the `StringList` wrapper.\n",
        );
        out.push_str(
            "    fn list_async<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {\n",
        );
        write_async_list_dispatch(&mut out, endpoint, &method_params, column, "        ");
        out.push_str("    }\n");
        out.push_str("}\n");
        return out;
    }

    // Parsed endpoint: builder runs the request and wraps the decoder-owned
    // `Vec<tick::T>` in a `<TickName>List`. The wrapper owns the terminals
    // (`to_list`, `to_arrow`, `to_pandas`, `to_polars`) so there is exactly
    // one path from decoded ticks to DataFrame output; no four-way drift.
    let list_class = python_pyclass_list_class(&endpoint.return_type);
    out.push_str("    /// Execute the request and return a typed list wrapper.\n");
    out.push_str("    ///\n");
    out.push_str("    /// Chain `.to_polars()` / `.to_pandas()` / `.to_arrow()` / `.to_list()`\n");
    out.push_str("    /// on the result to convert to the downstream representation.\n");
    writeln!(
        out,
        "    fn list(&self, py: Python<'_>) -> PyResult<Py<{list_class}>> {{"
    )
    .unwrap();
    write_sync_parsed_dispatch(
        &mut out,
        endpoint,
        &method_params,
        &builder_params,
        "        ",
    );
    writeln!(
        out,
        "        {}(py, ticks)",
        python_pyclass_list_converter(&endpoint.return_type)
    )
    .unwrap();
    out.push_str("    }\n\n");

    // Async terminal. Clones the Arc + state into the future; the closure
    // is `'static + Send` so no references survive.
    out.push_str(
        "    /// Async companion to `list()` — awaitable yields the typed list wrapper.\n",
    );
    out.push_str(
        "    fn list_async<'py>(&self, py: Python<'py>) -> PyResult<Bound<'py, PyAny>> {\n",
    );
    write_async_parsed_dispatch(
        &mut out,
        endpoint,
        &method_params,
        &builder_params,
        "        ",
    );
    out.push_str("    }\n\n");

    // Streaming terminal. Skip for snapshot endpoints (bounded rows).
    // Every
    // other market-data parsed endpoint gets `.stream(handler)` and
    // `.stream_async(handler)` — the handler receives one Python list
    // of typed tick instances per gRPC chunk, never the full Vec.
    if !is_snapshot {
        write_sync_stream_terminal(&mut out, endpoint, &method_params, &builder_params);
        out.push('\n');
        write_async_stream_terminal(&mut out, endpoint, &method_params, &builder_params);
    }

    out.push_str("}\n");

    out
}

/// Emit the `stream(handler)` sync terminal that routes each gRPC
/// chunk into a Python callback as a typed `list[Tick]`. The decoder-
/// owned `Vec<tick::T>` is converted under the GIL via the per-tick
/// `*_vec_to_pylist` factory then handed to the user's callable; once
/// the call returns the Python list is dropped and the wire `Bytes`
/// are released before the next chunk is fetched.
///
/// PyErr bridging: callback exceptions are captured into the spawned
/// future's `Result<(), thetadatadx::Error>` via
/// `Error::config_internal(msg)` so `run_blocking`'s signature is
/// honoured. The captured PyErr is re-raised on the Python side via
/// `Python::with_gil` before `run_blocking` returns. A wire error
/// observed while a callback PyErr is also pending surfaces the
/// callback error — the user's Python exception is the proximate
/// cause of the stream's cancellation.
fn write_sync_stream_terminal(
    out: &mut String,
    endpoint: &GeneratedEndpoint,
    method_params: &[&GeneratedParam],
    builder_params: &[&GeneratedParam],
) {
    let pylist_converter = python_vec_to_pylist_converter(&endpoint.return_type);
    // Only shardable history endpoints can fan out; the rest are always
    // single-stream, so omit the fan-out note for them (see `endpoint_can_fan_out`).
    let fan_out = if super::endpoint_can_fan_out(endpoint) {
        " Under `bulk_fetch = \"auto\"` a large history pull may fan out across \
         concurrent sub-requests: every chunk is still delivered exactly once, but \
         chunks from different sub-requests interleave in arrival order rather than \
         the single-stream order (`bulk_fetch = \"off\"` restores it)."
    } else {
        ""
    };
    let doc = format!(
        "Stream chunks of `{}` rows into `handler` without materialising the full \
         response in memory. `handler(chunk: list[Tick]) -> None` is called once per \
         gRPC chunk; the chunk is freed before the stream's next chunk is fetched.{fan_out} \
         A `RuntimeError` raised by `handler` aborts the stream and propagates as the \
         method's return value.",
        endpoint.name
    );
    out.push_str(&render_rust_doc_block("    ", &doc));
    out.push_str("    fn stream(&self, py: Python<'_>, handler: Py<PyAny>) -> PyResult<()> {\n");
    write_stream_dispatch_setup(out, method_params, builder_params, "        ");
    out.push_str("        let handler_arc = std::sync::Arc::new(handler);\n");
    out.push_str("        let handler_for_closure = std::sync::Arc::clone(&handler_arc);\n");
    out.push_str("        // Callback PyErr is captured in a Mutex<Option<PyErr>>\n");
    out.push_str("        // because the chunk closure is `FnMut`, not `FnOnce`, and\n");
    out.push_str("        // can't move-out of `&mut Option<PyErr>`. The Mutex also\n");
    out.push_str("        // gives us `Send`, which `run_blocking`'s bound requires.\n");
    out.push_str("        let callback_error: std::sync::Arc<std::sync::Mutex<Option<PyErr>>> =\n");
    out.push_str("            std::sync::Arc::new(std::sync::Mutex::new(None));\n");
    out.push_str("        let cb_err_for_closure = std::sync::Arc::clone(&callback_error);\n");
    out.push_str("        let stream_result = run_blocking(py, async move {\n");
    write_stream_request_setup(out, endpoint, method_params, builder_params, "            ");
    out.push_str("            request.stream_ticks(|chunk| {\n");
    out.push_str("                if cb_err_for_closure.lock().unwrap().is_some() {\n");
    out.push_str("                    return;\n");
    out.push_str("                }\n");
    out.push_str("                Python::attach(|py| {\n");
    writeln!(
        out,
        "                    let py_list = match {}(py, chunk) {{",
        pylist_converter
    )
    .unwrap();
    out.push_str("                        Ok(list) => list,\n");
    out.push_str("                        Err(e) => {\n");
    out.push_str("                            *cb_err_for_closure.lock().unwrap() = Some(e);\n");
    out.push_str("                            return;\n");
    out.push_str("                        }\n");
    out.push_str("                    };\n");
    out.push_str(
        "                    if let Err(e) = handler_for_closure.call1(py, (py_list,)) {\n",
    );
    out.push_str("                        *cb_err_for_closure.lock().unwrap() = Some(e);\n");
    out.push_str("                    }\n");
    out.push_str("                });\n");
    out.push_str("            }).await\n");
    out.push_str("        });\n");
    out.push_str("        // Surface the callback PyErr before any later stream/deadline\n");
    out.push_str("        // error observed while draining after the callback stopped\n");
    out.push_str("        // processing; the callback exception is the proximate cause.\n");
    out.push_str("        if let Some(py_err) = callback_error.lock().unwrap().take() {\n");
    out.push_str("            return Err(py_err);\n");
    out.push_str("        }\n");
    out.push_str("        stream_result?;\n");
    out.push_str("        Ok(())\n");
    out.push_str("    }\n");
}

/// Emit the `stream_async(handler)` async terminal — awaitable variant
/// of [`write_sync_stream_terminal`]. Each chunk's owned rows are copied
/// out synchronously, then the GIL-bound `handler` runs on tokio's
/// blocking pool via `spawn_blocking` (driven by `stream_async` on the
/// builder, which awaits the per-chunk future before fetching the next).
/// Offloading the handler keeps the shared async workers free for every
/// other in-flight market-data call while the handler runs — `block_in_place`
/// would instead churn the worker pool for an arbitrary-duration handler.
/// The awaitable resolves to `None` on clean drain, raises on first error.
///
/// Same PyErr-folding strategy as the sync path: the chunk closure
/// stashes a captured PyErr inside an `Arc<Mutex<Option<PyErr>>>` so
/// the spawned future's `Result<(), thetadatadx::Error>` stays free of
/// PyErr (the bound on `spawn_awaitable` wouldn't accept it). A panic in
/// the blocking task is folded into the same slot rather than swallowed.
/// The stashed PyErr is unstashed in the post-await converter step where
/// the GIL is reacquired.
fn write_async_stream_terminal(
    out: &mut String,
    endpoint: &GeneratedEndpoint,
    method_params: &[&GeneratedParam],
    builder_params: &[&GeneratedParam],
) {
    let pylist_converter = python_vec_to_pylist_converter(&endpoint.return_type);
    // Only shardable history endpoints can fan out (see `endpoint_can_fan_out`).
    let fan_out = if super::endpoint_can_fan_out(endpoint) {
        " Under `bulk_fetch = \"auto\"` a large history pull may fan \
         out across concurrent sub-requests: every chunk is still delivered \
         exactly once, but chunks from different sub-requests interleave in \
         arrival order rather than the single-stream order (`bulk_fetch = \
         \"off\"` restores it)."
    } else {
        ""
    };
    let doc = format!(
        "Async companion to `stream()` — awaitable yields `None` when the \
         streamed response of `{}` rows finishes. `handler(chunk: list[Tick]) \
         -> None` runs once per gRPC chunk, one call at a time, on a worker \
         thread; a stream's next chunk is not fetched until its handler call \
         returns.{fan_out} Cancelling the awaitable \
         drops the in-flight gRPC stream (RST_STREAM on the underlying h2 \
         stream) and fetches no further chunks. A handler already running when \
         cancellation lands runs to completion — Python is not interruptible \
         mid-call — so one final `handler` call may finish after the awaitable \
         is cancelled or its deadline expires.",
        endpoint.name
    );
    out.push_str(&render_rust_doc_block("    ", &doc));
    out.push_str("    fn stream_async<'py>(&self, py: Python<'py>, handler: Py<PyAny>) -> PyResult<Bound<'py, PyAny>> {\n");
    write_stream_dispatch_setup(out, method_params, builder_params, "        ");
    out.push_str("        let handler_arc = std::sync::Arc::new(handler);\n");
    out.push_str("        let handler_for_closure = std::sync::Arc::clone(&handler_arc);\n");
    out.push_str("        let callback_error: std::sync::Arc<std::sync::Mutex<Option<PyErr>>> =\n");
    out.push_str("            std::sync::Arc::new(std::sync::Mutex::new(None));\n");
    out.push_str("        let cb_err_for_closure = std::sync::Arc::clone(&callback_error);\n");
    out.push_str("        let cb_err_for_convert = std::sync::Arc::clone(&callback_error);\n");
    out.push_str("        spawn_awaitable(py, async move {\n");
    write_stream_request_setup(out, endpoint, method_params, builder_params, "            ");
    out.push_str("            Ok::<_, thetadatadx::Error>(request.stream_ticks_async(|chunk| {\n");
    out.push_str("                // Copy the chunk out synchronously so nothing borrowed\n");
    out.push_str("                // is held across the await, then run the GIL-bound\n");
    out.push_str("                // handler on the blocking pool: a slow handler parks a\n");
    out.push_str("                // pool thread, never a shared async worker driving other\n");
    out.push_str("                // in-flight market-data calls. The handler Py<PyAny> is\n");
    out.push_str("                // Arc'd once (Send + Sync); we clone the Arc per chunk\n");
    out.push_str("                // (no GIL needed), never clone_ref.\n");
    // Short-circuit synchronously once a handler has errored: handlers run
    // one-at-a-time (awaited in-line), so a post-error drain skips both the
    // handler and any Python conversion work.
    out.push_str("                let owned = if cb_err_for_closure.lock().unwrap().is_some() {\n");
    out.push_str("                    None\n");
    out.push_str("                } else {\n");
    out.push_str("                    Some(chunk)\n");
    out.push_str("                };\n");
    out.push_str(
        "                let handler_for_task = std::sync::Arc::clone(&handler_for_closure);\n",
    );
    out.push_str(
        "                let cb_err_for_task = std::sync::Arc::clone(&cb_err_for_closure);\n",
    );
    out.push_str(
        "                let cb_err_for_join = std::sync::Arc::clone(&cb_err_for_closure);\n",
    );
    out.push_str("                async move {\n");
    out.push_str("                    let Some(owned) = owned else { return; };\n");
    out.push_str("                    // GIL acquired strictly inside spawn_blocking — never\n");
    out.push_str("                    // held on the async side while awaiting the join, so a\n");
    out.push_str("                    // pool thread waiting on the GIL cannot deadlock the\n");
    out.push_str("                    // task awaiting it.\n");
    out.push_str("                    let join = tokio::task::spawn_blocking(move || {\n");
    out.push_str("                        Python::attach(|py| {\n");
    writeln!(
        out,
        "                            let py_list = match {}(py, owned) {{",
        pylist_converter
    )
    .unwrap();
    out.push_str("                                Ok(list) => list,\n");
    out.push_str("                                Err(e) => {\n");
    out.push_str(
        "                                    *cb_err_for_task.lock().unwrap() = Some(e);\n",
    );
    out.push_str("                                    return;\n");
    out.push_str("                                }\n");
    out.push_str("                            };\n");
    out.push_str(
        "                            if let Err(e) = handler_for_task.call1(py, (py_list,)) {\n",
    );
    out.push_str("                                *cb_err_for_task.lock().unwrap() = Some(e);\n");
    out.push_str("                            }\n");
    out.push_str("                        })\n");
    out.push_str("                    }).await;\n");
    out.push_str("                    if let Err(join_err) = join {\n");
    out.push_str("                        // A panic in the handler task surfaces as a\n");
    out.push_str("                        // re-raised RuntimeError instead of being swallowed.\n");
    out.push_str("                        crate::async_runtime::capture_join_error(&cb_err_for_join, join_err);\n");
    out.push_str("                    }\n");
    out.push_str("                }\n");
    out.push_str("            }).await)\n");
    out.push_str("        }, move |py, stream_result| {\n");
    out.push_str("            // Post-await converter — reacquired GIL. Re-raise any\n");
    out.push_str("            // captured callback PyErr before any later stream/deadline\n");
    out.push_str("            // error observed after the callback stopped processing.\n");
    out.push_str("            if let Some(py_err) = cb_err_for_convert.lock().unwrap().take() {\n");
    out.push_str("                return Err(py_err);\n");
    out.push_str("            }\n");
    out.push_str("            stream_result.map_err(to_py_err)?;\n");
    out.push_str("            Ok::<_, PyErr>(py.None())\n");
    out.push_str("        })\n");
    out.push_str("    }\n");
}

/// Shared dispatch-setup emit: clones the Arc + every captured request
/// param off `self` so the spawned future / blocking call owns its
/// state. Mirrors [`write_sync_parsed_dispatch`] / [`write_async_parsed_dispatch`].
fn write_stream_dispatch_setup(
    out: &mut String,
    method_params: &[&GeneratedParam],
    builder_params: &[&GeneratedParam],
    indent: &str,
) {
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    writeln!(out, "{indent}let client = self.client.clone();").unwrap();
    if has_symbols {
        writeln!(out, "{indent}let symbols = self.symbols.clone();").unwrap();
    } else {
        for param in method_params {
            writeln!(
                out,
                "{indent}let {} = self.{}.clone();",
                param.name, param.name
            )
            .unwrap();
        }
    }
    for param in builder_params {
        writeln!(
            out,
            "{indent}let {} = self.{}{};",
            param.name,
            param.name,
            builder_field_clone_expr(param)
        )
        .unwrap();
    }
    writeln!(out, "{indent}let timeout_ms = self.timeout_ms;").unwrap();
}

/// Shared request-builder emit: turns the cloned state into a
/// `client.<endpoint>(...)` builder with every chained setter applied.
/// Lives inside the spawned future / `run_blocking` body; consumed by
/// the `.stream(handler)` call right after.
fn write_stream_request_setup(
    out: &mut String,
    endpoint: &GeneratedEndpoint,
    method_params: &[&GeneratedParam],
    builder_params: &[&GeneratedParam],
    indent: &str,
) {
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        writeln!(
            out,
            "{indent}let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();"
        )
        .unwrap();
    }
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("&{}", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "{indent}let mut request = client.market_data().{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in builder_params {
        writeln!(out, "{indent}if let Some(value) = &{} {{", param.name).unwrap();
        writeln!(
            out,
            "{indent}    request = request.{}({});",
            param.name,
            builder_apply_self_value(param)
        )
        .unwrap();
        writeln!(out, "{indent}}}").unwrap();
    }
    writeln!(out, "{indent}if let Some(ms) = timeout_ms {{").unwrap();
    writeln!(
        out,
        "{indent}    request = request.with_deadline(std::time::Duration::from_millis(ms));"
    )
    .unwrap();
    writeln!(out, "{indent}}}").unwrap();
}

/// Builder constructor emitted on `Client` — `client.name_builder(...)` is
/// the Python entry point that yields a `NameBuilder`. Required params are
/// passed positionally (same order as the typed endpoint); optionals are
/// chained after construction.
fn render_python_builder_constructor(endpoint: &GeneratedEndpoint) -> String {
    let struct_name = endpoint_builder_struct(&endpoint.name);
    let method_params = method_params(endpoint);
    let builder_params = if endpoint.return_type == "StringList" {
        Vec::new()
    } else {
        builder_params(endpoint)
    };
    let mut out = String::new();

    let mut doc = format!(
        "Create a fluent-builder for `{}`. Chain setters then call `.list()`\n\
         (or `.list_async()`) to execute the request; the returned typed list\n\
         wrapper exposes the chainable terminals `.to_list()` / `.to_arrow()`\n\
         / `.to_pandas()` / `.to_polars()`.",
        endpoint.name
    );
    doc.push_str("\n\nSee `");
    doc.push_str(&endpoint.name);
    doc.push_str("()` for the sync signature; `");
    doc.push_str(&endpoint.name);
    doc.push_str("_async()` for the awaitable companion.");
    out.push_str(&render_rust_doc_block("    ", &doc));

    let signature_parts = method_params
        .iter()
        .map(|param| sdk_method_arg_name(param))
        .collect::<Vec<_>>();
    writeln!(
        out,
        "    #[pyo3(signature = ({}))]",
        signature_parts.join(", ")
    )
    .unwrap();

    writeln!(out, "    fn {}_builder(", endpoint.name).unwrap();
    out.push_str("        &self,\n");
    for param in &method_params {
        writeln!(out, "        {},", python_method_arg_decl(param)).unwrap();
    }
    writeln!(out, "    ) -> {} {{", struct_name).unwrap();
    writeln!(out, "        {} {{", struct_name).unwrap();
    out.push_str("            client: self.client.clone(),\n");
    for param in &method_params {
        if param.param_type == "Symbols" {
            out.push_str("            symbols: symbols.into_vec(),\n");
        } else {
            writeln!(
                out,
                "            {}: {}.into_string(),",
                param.name, param.name
            )
            .unwrap();
        }
    }
    for param in &builder_params {
        writeln!(out, "            {}: None,", param.name).unwrap();
    }
    out.push_str("            timeout_ms: None,\n");
    out.push_str("        }\n");
    out.push_str("    }\n");

    out
}

// ───────────────────────── Shared dispatch writers ─────────────────────────

fn write_sync_list_dispatch(
    out: &mut String,
    endpoint: &GeneratedEndpoint,
    method_params: &[&GeneratedParam],
    indent: &str,
) {
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        writeln!(
            out,
            "{indent}let refs: Vec<&str> = self.symbols.iter().map(|s| s.as_str()).collect();"
        )
        .unwrap();
    }
    writeln!(out, "{indent}let client = self.client.clone();").unwrap();
    writeln!(out, "{indent}let timeout_ms = self.timeout_ms;").unwrap();
    // Rebuild the args vector inside the closure so the closure owns every
    // dependency at move time.
    if has_symbols {
        writeln!(out, "{indent}let symbols = self.symbols.clone();").unwrap();
    } else {
        for param in method_params {
            writeln!(
                out,
                "{indent}let {} = self.{}.clone();",
                param.name, param.name
            )
            .unwrap();
        }
    }
    // Emits `let values: Vec<String> = run_blocking(...)` — no trailing
    // `?;` or semicolon; the caller appends `?;` and chains the
    // `strings_to_string_list` wrap.
    writeln!(
        out,
        "{indent}let values: Vec<String> = run_blocking(py, async move {{"
    )
    .unwrap();
    if has_symbols {
        writeln!(
            out,
            "{indent}    let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();"
        )
        .unwrap();
    }
    // Rebuild positional args to reference the moved-in owned values.
    let positional_args_closure = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("&{}", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "{indent}    let call = client.market_data().{}({});",
        endpoint.name, positional_args_closure
    )
    .unwrap();
    write_timeout_call(out, &format!("{indent}    "));
    write!(out, "{indent}}})").unwrap();
}

fn write_async_list_dispatch(
    out: &mut String,
    endpoint: &GeneratedEndpoint,
    method_params: &[&GeneratedParam],
    column_name: &str,
    indent: &str,
) {
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    writeln!(out, "{indent}let client = self.client.clone();").unwrap();
    if has_symbols {
        writeln!(out, "{indent}let symbols = self.symbols.clone();").unwrap();
    } else {
        for param in method_params {
            writeln!(
                out,
                "{indent}let {} = self.{}.clone();",
                param.name, param.name
            )
            .unwrap();
        }
    }
    writeln!(out, "{indent}let timeout_ms = self.timeout_ms;").unwrap();
    // `spawn_awaitable` wraps `pyo3_async_runtimes::tokio::future_into_py`,
    // routes `thetadatadx::Error` through `to_py_err`, and runs the convert
    // closure under `Python::attach`. One call per builder `list_async`
    // emit keeps this path symmetric with the free-function `_async` emit.
    writeln!(out, "{indent}spawn_awaitable(py, async move {{").unwrap();
    if has_symbols {
        writeln!(
            out,
            "{indent}    let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();"
        )
        .unwrap();
    }
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("&{}", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "{indent}    let call = client.market_data().{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    write_timeout_call(out, &format!("{indent}    "));
    // Convert the resolved `Vec<String>` into the typed `StringList` and
    // coerce up to `Py<PyAny>` to satisfy the helper's convert signature.
    writeln!(
        out,
        "{indent}}}, |py, values| strings_to_string_list(py, values, \"{column_name}\").map(|p| p.into_any()))"
    )
    .unwrap();
}

fn write_sync_parsed_dispatch(
    out: &mut String,
    endpoint: &GeneratedEndpoint,
    method_params: &[&GeneratedParam],
    builder_params: &[&GeneratedParam],
    indent: &str,
) {
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    writeln!(out, "{indent}let client = self.client.clone();").unwrap();
    if has_symbols {
        writeln!(out, "{indent}let symbols = self.symbols.clone();").unwrap();
    } else {
        for param in method_params {
            writeln!(
                out,
                "{indent}let {} = self.{}.clone();",
                param.name, param.name
            )
            .unwrap();
        }
    }
    for param in builder_params {
        writeln!(
            out,
            "{indent}let {} = self.{}{};",
            param.name,
            param.name,
            builder_field_clone_expr(param)
        )
        .unwrap();
    }
    writeln!(out, "{indent}let timeout_ms = self.timeout_ms;").unwrap();
    writeln!(out, "{indent}let ticks = run_blocking(py, async move {{").unwrap();
    if has_symbols {
        writeln!(
            out,
            "{indent}    let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();"
        )
        .unwrap();
    }
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("&{}", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "{indent}    let mut request = client.market_data().{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in builder_params {
        writeln!(out, "{indent}    if let Some(value) = &{} {{", param.name).unwrap();
        writeln!(
            out,
            "{indent}        request = request.{}({});",
            param.name,
            builder_apply_self_value(param)
        )
        .unwrap();
        writeln!(out, "{indent}    }}").unwrap();
    }
    writeln!(out, "{indent}    if let Some(ms) = timeout_ms {{").unwrap();
    writeln!(
        out,
        "{indent}        request = request.with_deadline(std::time::Duration::from_millis(ms));"
    )
    .unwrap();
    writeln!(out, "{indent}    }}").unwrap();
    writeln!(out, "{indent}    request.await").unwrap();
    writeln!(out, "{indent}}})?;").unwrap();
}

/// Stored-value-to-setter-arg converter for the builder pyclass dispatch.
fn builder_apply_self_value(param: &GeneratedParam) -> String {
    match param.param_type.as_str() {
        "Int" | "Float" | "Bool" => "*value".into(),
        _ => "value.as_str()".into(),
    }
}

/// Return `true` if the builder-stored type for this param implements
/// `Copy` (so we can skip `.clone()` — clippy flags clone-on-Copy).
fn builder_stored_is_copy(param: &GeneratedParam) -> bool {
    matches!(param.param_type.as_str(), "Int" | "Float" | "Bool")
}

/// Clone or move expression for transferring a builder field into the
/// `async move` closure, avoiding the `clone_on_copy` clippy error.
fn builder_field_clone_expr(param: &GeneratedParam) -> &'static str {
    if builder_stored_is_copy(param) {
        ""
    } else {
        ".clone()"
    }
}

fn write_async_parsed_dispatch(
    out: &mut String,
    endpoint: &GeneratedEndpoint,
    method_params: &[&GeneratedParam],
    builder_params: &[&GeneratedParam],
    indent: &str,
) {
    writeln!(out, "{indent}let client = self.client.clone();").unwrap();
    for param in method_params {
        if param.param_type == "Symbols" {
            writeln!(out, "{indent}let symbols = self.symbols.clone();").unwrap();
        } else {
            writeln!(
                out,
                "{indent}let {} = self.{}.clone();",
                param.name, param.name
            )
            .unwrap();
        }
    }
    for param in builder_params {
        writeln!(
            out,
            "{indent}let {} = self.{}{};",
            param.name,
            param.name,
            builder_field_clone_expr(param)
        )
        .unwrap();
    }
    writeln!(out, "{indent}let timeout_ms = self.timeout_ms;").unwrap();
    // `spawn_awaitable` owns the `future_into_py` + `to_py_err` + GIL-held
    // convert plumbing; one call per builder `list_async` emit keeps this
    // path symmetric with the free-function `_async` emit.
    writeln!(out, "{indent}spawn_awaitable(py, async move {{").unwrap();
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        writeln!(
            out,
            "{indent}    let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();"
        )
        .unwrap();
    }
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else {
                format!("&{}", param.name)
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    writeln!(
        out,
        "{indent}    let mut request = client.market_data().{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in builder_params {
        writeln!(out, "{indent}    if let Some(value) = &{} {{", param.name).unwrap();
        writeln!(
            out,
            "{indent}        request = request.{}({});",
            param.name,
            builder_apply_self_value(param)
        )
        .unwrap();
        writeln!(out, "{indent}    }}").unwrap();
    }
    writeln!(out, "{indent}    if let Some(ms) = timeout_ms {{").unwrap();
    writeln!(
        out,
        "{indent}        request = request.with_deadline(std::time::Duration::from_millis(ms));"
    )
    .unwrap();
    writeln!(out, "{indent}    }}").unwrap();
    writeln!(out, "{indent}    request.await").unwrap();
    // Single terminal path — wrap the decoder-owned Ticks<T> in the typed
    // `<TickName>List` and coerce to `Py<PyAny>` for the helper signature.
    // The caller chains `.to_polars()` / etc. off the awaited value.
    writeln!(
        out,
        "{indent}}}, |py, ticks| {}(py, ticks).map(|p| p.into_any()))",
        python_pyclass_list_converter(&endpoint.return_type)
    )
    .unwrap();
}
