//! TypeScript SDK napi-rs emitter.
//!
//! Renders `thetadatadx-ts/src/_generated/market_data_methods.rs` — the
//! shared per-endpoint options structs plus one `impl` block per
//! market-data napi class (`Client`, the unified handle, and
//! `MarketDataClient`, the standalone market-data-only handle). Both carry the
//! identical method bodies (every body references `self.client`), so the
//! market-data surface stays in lockstep across the two at zero
//! per-method cost. napi-rs compiles the result into the Node.js native
//! addon.
//!
//! Every endpoint method is an `async fn`: napi-rs returns a JS Promise
//! and resolves it off the runtime's execution thread, so the network
//! round-trip never holds the Node event loop for the duration of a
//! fetch. The returned Promise resolves with the same typed row array
//! the synchronous shape returned before; the element types are
//! unchanged. The blocking round-trip is handed to a worker via
//! `spawn_endpoint_task` so timers, queued promises, and concurrent
//! requests keep advancing while a fetch is in flight.
//!
//! Each method takes its required parameters positionally, followed by
//! ONE optional trailing options object (the JavaScript idiom for
//! multiple optional parameters — positional `undefined` holes silently
//! shift later arguments onto the wrong parameter). Each endpoint gets a
//! dedicated `#[napi(object)] <Method>Options` struct whose keys are the
//! camelCase parameter names; absent keys behave exactly like an omitted
//! parameter. `timeoutMs` rides in the same object: when set, the call is
//! given a deadline; on expiry the Promise rejects and the underlying
//! request is cancelled. The `Client` handle remains usable.
//!
//! Every history endpoint that returns a typed row collection also gets a
//! `<endpoint>Stream(...args, options, callback)` server-stream companion
//! (the TypeScript surface of the Python builders' `.stream(handler)`).
//! Instead of buffering the whole response, it pumps each decoded gRPC
//! chunk to `callback(chunk: Tick[])` through a napi-rs
//! `ThreadsafeFunction` and awaits that callback before fetching the next
//! chunk, so peak memory tracks one chunk rather than the full result — the
//! path the `Config.setWarnOnBufferedThresholdBytes` warning points
//! oversized buffered pulls at. The coverage set mirrors the Python streaming
//! builders exactly (non-snapshot, non-FPSS-kind endpoints that decode to a
//! row collection); snapshot endpoints and the flat `StringList` list
//! endpoints have no stream companion.

use std::fmt::Write as _;

use heck::ToLowerCamelCase as _;

use super::super::helpers::{compose_endpoint_doc, endpoint_streams, is_streaming_endpoint};
use super::super::model::GeneratedEndpoint;
use super::super::sdk_helpers::{
    builder_params, is_time_arg, method_params, render_rust_doc_block, sdk_method_arg_name,
    to_camel_case, to_pascal_case, ts_class_name, ts_class_vec_converter, write_timeout_call,
};

/// napi classes that carry the market-data endpoint surface. Both expose a
/// `client_handle(&self) -> napi::Result<Arc<thetadatadx::Client>>` accessor,
/// so the generated method bodies (which resolve the handle via
/// `self.client_handle()?`) compile unchanged against either receiver.
/// `MarketDataView` co-owns its `Arc` (always `Ok`, surviving a parent
/// `Client::close`); `MarketDataClient` holds the handle behind an `Option` and
/// rejects with "client is closed" once its own `close()` has released it.
///
/// `Client` is the unified handle (market-data + FPSS
/// streaming); `MarketDataClient` is the standalone market-data-only handle
/// that never opens the FPSS transport. The standalone client mirrors
/// the Python `MarketDataClient` (`thetadatadx-py/src/mdds_client.rs`), the C++
/// `thetadatadx::Client`, and the C ABI `thetadatadx_client_*` entry points: the same
/// MDDS/Nexus surface with no streaming methods reachable. Emitting the
/// identical method bodies onto both keeps the market-data surface in
/// lockstep at zero per-method cost — adding an endpoint to
/// `endpoint_surface.toml` lands it on both classes automatically.
///
/// The unified client exposes these through the `client.market_data`
/// sub-namespace, so the generated block targets `MarketDataView` (the
/// view returned by the `marketData` getter); the standalone
/// `MarketDataClient` keeps its flat market-data surface.
const MARKET_DATA_IMPL_CLASSES: &[&str] = &["MarketDataView", "MarketDataClient"];

/// Renders the TypeScript market-data surface: the per-endpoint options
/// structs and one napi `impl` block per market-data class, each carrying
/// every endpoint method and its server-stream companion.
pub(super) fn render_typescript_market_data_methods(endpoints: &[GeneratedEndpoint]) -> String {
    let mut out = String::new();
    out.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n\n",
    );
    // Per-endpoint options objects first (shared across every market-data
    // class — they carry no receiver), then one impl block per class.
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        out.push_str(&render_typescript_endpoint_options_struct(endpoint));
        out.push('\n');
    }
    // One `<Tick>WithColumns` return object per distinct columnar return type —
    // the `{ rows, presentColumns, symbol? }` shape the `<method>WithColumns`
    // variant returns, so a live caller can drive the projected Arrow-IPC exit
    // from the response's own column set. `StringList` endpoints carry no
    // column set and get none.
    let mut seen_return_types = std::collections::HashSet::new();
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
        .filter(|endpoint| endpoint.return_type != "StringList")
    {
        if seen_return_types.insert(endpoint.return_type.clone()) {
            out.push_str(&render_typescript_with_columns_struct(
                &endpoint.return_type,
            ));
            out.push('\n');
        }
    }
    for class_name in MARKET_DATA_IMPL_CLASSES {
        out.push_str(&render_typescript_market_data_impl_block(
            endpoints, class_name,
        ));
    }
    out
}

/// Emit a single `#[napi] impl <ClassName> { ... }` block carrying every
/// market-data endpoint method (and its server-stream companion). The
/// method bodies resolve the client via `self.client_handle()?`, so the block
/// compiles against any napi class that exposes a
/// `client_handle(&self) -> napi::Result<Arc<thetadatadx::Client>>` accessor.
/// Parameterising over the class name lets the generator
/// project the identical surface onto the unified `Client` and
/// the standalone `MarketDataClient` without duplicating the per-endpoint
/// rendering.
fn render_typescript_market_data_impl_block(
    endpoints: &[GeneratedEndpoint],
    class_name: &str,
) -> String {
    let mut out = String::new();
    out.push_str("#[napi]\n");
    writeln!(out, "impl {class_name} {{").unwrap();
    for endpoint in endpoints
        .iter()
        .filter(|endpoint| !is_streaming_endpoint(endpoint))
    {
        out.push_str(&render_typescript_endpoint_method(endpoint));
        out.push('\n');
        // Server-stream terminal companion. Emitted for every endpoint
        // that gets `.stream(handler)` / `.stream_async(handler)` on the
        // Python parsed builders (see `python.rs::write_sync_stream_terminal`):
        // a non-snapshot, non-streaming-kind history endpoint that returns a
        // typed row collection. Snapshot endpoints (≤10 rows) and the
        // `StringList` list endpoints (which return bare strings, not a tick
        // collection) are excluded — streaming a handful of rows or a flat
        // string list buys nothing over the buffered method. The stream
        // companion pumps decoded gRPC history chunks (not FPSS events), so
        // it stays on the MDDS-only surface like every other market-data
        // method.
        if endpoint_streams(endpoint) {
            out.push_str(&render_typescript_endpoint_stream_method(endpoint));
            out.push('\n');
        }
        // Presence-carrying variant: the same query returning the rows plus the
        // response's projected column set (and the broadcast `symbol` when the
        // wire carried one), so the projected Arrow-IPC exit is reachable from a
        // live call. `StringList` endpoints carry no column set and get none.
        if endpoint.return_type != "StringList" {
            out.push_str(&render_typescript_endpoint_with_columns_method(endpoint));
            out.push('\n');
        }
    }
    out.push_str("}\n");
    out
}

/// `stock_history_eod` -> `StockHistoryEodOptions`.
fn options_struct_name(endpoint: &GeneratedEndpoint) -> String {
    format!("{}Options", to_pascal_case(&endpoint.name))
}

/// Emit the per-endpoint `#[napi(object)]` options struct: one optional
/// key per optional endpoint parameter plus `timeoutMs`. All fields are
/// `Option`, so `Default` derives and an omitted object behaves exactly
/// like an empty one.
fn render_typescript_endpoint_options_struct(endpoint: &GeneratedEndpoint) -> String {
    let camel_name = to_camel_case(&endpoint.name);
    let struct_name = options_struct_name(endpoint);
    let builder_params = if endpoint.return_type == "StringList" {
        Vec::new()
    } else {
        builder_params(endpoint)
    };
    let mut out = String::new();
    writeln!(
        out,
        "/// Optional parameters for the `{camel_name}` method. Keys are"
    )
    .unwrap();
    out.push_str("/// the camelCase parameter names; absent keys behave exactly like an\n");
    out.push_str("/// omitted parameter. `timeoutMs` bounds the whole call: on expiry the\n");
    out.push_str("/// returned Promise rejects and the underlying request is cancelled.\n");
    out.push_str("#[napi(object)]\n");
    out.push_str("#[derive(Default)]\n");
    writeln!(out, "pub struct {struct_name} {{").unwrap();
    for param in &builder_params {
        // Per-field doc so the parameter's units and meaning reach the
        // generated `.d.ts` interface member (napi-rs propagates `///`
        // comments onto interface fields). Without this the options
        // object would list bare `annualDividend?: number` with no unit.
        super::doc::doc_lines(&mut out, "    ", &param.description);
        writeln!(
            out,
            "    pub {}: {},",
            param.name,
            ts_napi_optional_type(param)
        )
        .unwrap();
    }
    out.push_str("    /// Per-call deadline as a non-negative whole number of milliseconds;\n");
    out.push_str("    /// on expiry the returned Promise rejects and the underlying request\n");
    out.push_str("    /// is cancelled. A non-finite, negative, or fractional value is\n");
    out.push_str("    /// rejected with `InvalidParameterError` rather than coerced.\n");
    out.push_str("    pub timeout_ms: Option<f64>,\n");
    out.push_str("}\n");
    out
}

fn render_typescript_endpoint_method(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let is_string_list = endpoint.return_type == "StringList";
    let camel_name = to_camel_case(&endpoint.name);
    let struct_name = options_struct_name(endpoint);
    let mut out = String::new();

    out.push_str(&render_rust_doc_block(
        "    ",
        &compose_endpoint_doc(endpoint),
    ));
    writeln!(out, "    #[napi(js_name = \"{camel_name}\")]").unwrap();
    // The method is `async`: napi-rs returns a JS Promise and drives the
    // future on its own runtime, so the network round-trip never runs on
    // the V8 execution thread and the Node event loop stays free for the
    // call's whole duration.
    writeln!(out, "    pub async fn {name}(", name = endpoint.name).unwrap();
    out.push_str("        &self,\n");
    for param in &method_params {
        writeln!(
            out,
            "        {}: {},",
            sdk_method_arg_name(param),
            ts_napi_arg_type(param)
        )
        .unwrap();
    }
    writeln!(out, "        options: Option<{struct_name}>,").unwrap();

    if is_string_list {
        out.push_str("    ) -> napi::Result<Vec<String>> {\n");
    } else {
        writeln!(
            out,
            "    ) -> napi::Result<Vec<{}>> {{",
            ts_class_name(&endpoint.return_type)
        )
        .unwrap();
    }

    write_ts_request_prelude(&mut out, endpoint, is_string_list);

    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");

    if is_string_list {
        let positional_args = method_params
            .iter()
            .map(|param| {
                if param.param_type == "Symbols" {
                    "&refs".into()
                } else if matches!(param.param_type.as_str(), "Date" | "Expiration")
                    || is_time_arg(param)
                {
                    format!("{}.as_str()", sdk_method_arg_name(param))
                } else {
                    format!("&{}", sdk_method_arg_name(param))
                }
            })
            .collect::<Vec<_>>()
            .join(", ");
        // The builder borrows `client` and the owned params, so it is
        // constructed and awaited inside the spawned future where those
        // values live for `'static`.
        out.push_str("        spawn_endpoint_task(async move {\n");
        if has_symbols {
            out.push_str(
                "            let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
            );
        }
        writeln!(
            out,
            "            let call = client.market_data().{name}({positional_args});",
            name = endpoint.name,
        )
        .unwrap();
        write_timeout_call(&mut out, "            ");
        out.push_str("        })\n");
        out.push_str("        .await\n");
        out.push_str("    }\n");
        return out;
    }

    // Builder-backed endpoints.
    write_ts_builder_request(&mut out, endpoint);
    writeln!(
        out,
        "        Ok({}(&ticks))",
        ts_class_vec_converter(&endpoint.return_type)
    )
    .unwrap();
    out.push_str("    }\n");
    out
}

/// Emit the shared method prelude: `options` unwrap, deadline validation,
/// client-handle clone, and the argument / builder-parameter normalization.
/// Byte-identical across the buffered `Array<Tick>` method, the `StringList`
/// list method, and the presence-carrying `<method>WithColumns` variant, so
/// they share one source of the request setup.
fn write_ts_request_prelude(out: &mut String, endpoint: &GeneratedEndpoint, is_string_list: bool) {
    let method_params = method_params(endpoint);
    let builder_params = if is_string_list {
        Vec::new()
    } else {
        builder_params(endpoint)
    };
    out.push_str("        let options = options.unwrap_or_default();\n");

    // Validate the per-call deadline up front, before the request task
    // is spawned: the option rides in as a JS `number` (f64), and an
    // `as u64` cast would silently rewrite a non-finite, negative, or
    // fractional value instead of rejecting it. `validate_timeout_ms`
    // returns the integer-domain `u64` the other bindings take, or an
    // `InvalidParameterError`; `?` rejects the Promise synchronously.
    out.push_str("        let timeout_ms = match options.timeout_ms {\n");
    out.push_str("            Some(ms) => Some(validate_timeout_ms(ms)?),\n");
    out.push_str("            None => None,\n");
    out.push_str("        };\n");

    // Clone the `Arc` client handle so the spawned future owns a
    // `'static` borrow source: the request builder borrows the client,
    // and that borrow must outlive the V8 stack frame the Promise
    // detaches from.
    out.push_str("        let client = self.client_handle()?;\n");

    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        out.push_str("        let symbols = normalize_symbols(symbols);\n");
    }
    for param in &method_params {
        let arg_name = sdk_method_arg_name(param);
        match param.param_type.as_str() {
            "Date" | "Expiration" => {
                writeln!(out, "        let {arg_name} = normalize_date({arg_name});").unwrap();
            }
            _ if is_time_arg(param) => {
                writeln!(out, "        let {arg_name} = normalize_time({arg_name});").unwrap();
            }
            _ => {}
        }
    }
    for param in &builder_params {
        match param.param_type.as_str() {
            "Date" | "Expiration" => {
                writeln!(
                    out,
                    "        let {} = normalize_optional_date(options.{});",
                    param.name, param.name
                )
                .unwrap();
            }
            _ if is_time_arg(param) => {
                writeln!(
                    out,
                    "        let {} = normalize_optional_time(options.{});",
                    param.name, param.name
                )
                .unwrap();
            }
            "Int" => {
                // Validate + narrow the JS `number` to `i32`, rejecting a
                // non-finite, negative, fractional, or out-of-range value
                // with `InvalidParameterError` instead of V8-wrapping it.
                writeln!(
                    out,
                    "        let {name} = validate_optional_nonneg_i32(\"{camel}\", options.{name})?;",
                    name = param.name,
                    camel = napi_field_camel(&param.name),
                )
                .unwrap();
            }
            _ => {
                writeln!(out, "        let {} = options.{};", param.name, param.name).unwrap();
            }
        }
    }
}

/// Emit the builder construction, spawn, and `.await?` for a builder-backed
/// (non-`StringList`) endpoint, binding the decoded `ticks` — a core
/// `Ticks<T>` carrying the response's column presence (`ticks.columns()`).
/// Shared by the buffered `Array<Tick>` method and the `<method>WithColumns`
/// variant, which read the presence off the same `ticks` binding.
fn write_ts_builder_request(out: &mut String, endpoint: &GeneratedEndpoint) {
    let method_params = method_params(endpoint);
    let builder_params = builder_params(endpoint);
    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else if matches!(param.param_type.as_str(), "Date" | "Expiration")
                || is_time_arg(param)
            {
                format!("{}.as_str()", sdk_method_arg_name(param))
            } else {
                format!("&{}", sdk_method_arg_name(param))
            }
        })
        .collect::<Vec<_>>()
        .join(", ");
    // The builder borrows `client` and the owned params, so it is
    // constructed and awaited inside the spawned future where those
    // values live for `'static`.
    out.push_str("        let ticks = spawn_endpoint_task(async move {\n");
    if has_symbols {
        out.push_str(
            "            let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
        );
    }
    writeln!(
        out,
        "            let mut request = client.market_data().{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in &builder_params {
        writeln!(out, "            if let Some(value) = {} {{", param.name).unwrap();
        let setter_arg = match param.param_type.as_str() {
            "Int" | "Float" | "Bool" => "value".to_string(),
            _ => "value.as_str()".to_string(),
        };
        writeln!(
            out,
            "                request = request.{}({});",
            param.name, setter_arg
        )
        .unwrap();
        out.push_str("            }\n");
    }
    out.push_str("            if let Some(ms) = timeout_ms {\n");
    out.push_str(
        "                request = request.with_deadline(std::time::Duration::from_millis(ms));\n",
    );
    out.push_str("            }\n");
    out.push_str("            request.await\n");
    out.push_str("        })\n");
    out.push_str("        .await?;\n");
}

/// `TradeTick` (the collection's element class) -> `TradeTickWithColumns`, the
/// `#[napi(object)]` return shape of the `<method>WithColumns` variant.
fn with_columns_struct_name(return_type: &str) -> String {
    format!("{}WithColumns", ts_class_name(return_type))
}

/// Emit the `#[napi(object)] <Tick>WithColumns` return struct: the decoded
/// rows plus the response's projected column set and optional broadcast
/// `symbol`. A live caller feeds `presentColumns` (and `symbol`) straight into
/// `<tick>ToArrowIpcProjected` for a terminal-exact columnar frame, without
/// hand-supplying the header list.
fn render_typescript_with_columns_struct(return_type: &str) -> String {
    let tick_class = ts_class_name(return_type);
    let struct_name = with_columns_struct_name(return_type);
    let mut out = String::new();
    writeln!(
        out,
        "/// A decoded history result paired with the columns the response's wire"
    )
    .unwrap();
    out.push_str("/// actually carried. Returned by the `<method>WithColumns` variant so a\n");
    out.push_str("/// live caller can serialize a projected Arrow-IPC frame (only the wire's\n");
    out.push_str("/// columns, matching the terminal's columnar output) without hand-supplying\n");
    writeln!(
        out,
        "/// the header list: pass `presentColumns` and `symbol` to `{}ToArrowIpcProjected`.",
        tick_class.to_lower_camel_case()
    )
    .unwrap();
    out.push_str("#[napi(object)]\n");
    writeln!(out, "pub struct {struct_name} {{").unwrap();
    out.push_str("    /// The decoded rows, identical to the `Array<Tick>` the buffered\n");
    out.push_str("    /// method returns.\n");
    writeln!(out, "    pub rows: Vec<{tick_class}>,").unwrap();
    out.push_str("    /// The schema-column names the response's wire carried, in schema\n");
    out.push_str("    /// order — the projection set for a terminal-exact Arrow frame.\n");
    out.push_str("    pub present_columns: Vec<String>,\n");
    out.push_str("    /// The response's constant `symbol` (root) when the wire carried one\n");
    out.push_str("    /// constant across every row (option, index, and single-symbol snapshot\n");
    out.push_str("    /// responses), else `undefined`.\n");
    out.push_str("    pub symbol: Option<String>,\n");
    out.push_str("    /// The response's per-row `symbol` values when the wire carried a\n");
    out.push_str(
        "    /// `symbol` column that varies across rows (a multi-symbol snapshot), one\n",
    );
    out.push_str("    /// value per row so each row is attributable to its underlying, else\n");
    out.push_str(
        "    /// `undefined`. Pass straight to `<tick>ToArrowIpcProjected`'s `symbols`.\n",
    );
    out.push_str("    pub symbols: Option<Vec<String>>,\n");
    out.push_str("}\n");
    out
}

/// Emit the `<endpoint>WithColumns` method: the same query as the buffered
/// method, returning the rows plus the response's projected column set and
/// broadcast `symbol` (a `<Tick>WithColumns` object) so the projected
/// Arrow-IPC exit is reachable from a live call — the TypeScript analogue of
/// the C `_with_options` presence out-param and Python's presence-carrying
/// `<Tick>List`. Only emitted for builder-backed (non-`StringList`) endpoints.
fn render_typescript_endpoint_with_columns_method(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let camel_name = to_camel_case(&endpoint.name);
    let struct_name = options_struct_name(endpoint);
    let return_struct = with_columns_struct_name(&endpoint.return_type);
    let converter = ts_class_vec_converter(&endpoint.return_type);
    let mut out = String::new();

    let doc = format!(
        "Run the `{camel}` query and return the rows together with the columns the \
         response's wire carried, so a projected Arrow-IPC frame is drivable from a \
         live call. Same parameters and result rows as the `{camel}` method; the \
         returned object adds `presentColumns` (the schema columns the wire sent, in \
         schema order), `symbol` (the response's constant root, set for option, index, \
         and single-symbol snapshot responses), and `symbols` (the per-row root values \
         for a multi-symbol snapshot, one per row). Feed them to \
         `{tick_camel}ToArrowIpcProjected` for a terminal-exact columnar export that \
         omits the columns the wire omitted and attributes each row to its symbol.",
        camel = camel_name,
        tick_camel = ts_class_name(&endpoint.return_type).to_lower_camel_case(),
    );
    out.push_str(&render_rust_doc_block("    ", &doc));
    writeln!(out, "    #[napi(js_name = \"{camel_name}WithColumns\")]").unwrap();
    writeln!(
        out,
        "    pub async fn {name}_with_columns(",
        name = endpoint.name
    )
    .unwrap();
    out.push_str("        &self,\n");
    for param in &method_params {
        writeln!(
            out,
            "        {}: {},",
            sdk_method_arg_name(param),
            ts_napi_arg_type(param)
        )
        .unwrap();
    }
    writeln!(out, "        options: Option<{struct_name}>,").unwrap();
    writeln!(out, "    ) -> napi::Result<{return_struct}> {{").unwrap();

    write_ts_request_prelude(&mut out, endpoint, false);
    write_ts_builder_request(&mut out, endpoint);

    // The core `Ticks<T>` carries the response's `ColumnPresence`: emit its
    // present schema columns and broadcast `symbol` alongside the converted
    // rows so the projected Arrow terminal is drivable without a header list.
    writeln!(out, "        Ok({return_struct} {{").unwrap();
    writeln!(out, "            rows: {converter}(&ticks),").unwrap();
    out.push_str(
        "            present_columns: ticks.columns().present_names().map(String::from).collect(),\n",
    );
    out.push_str("            symbol: ticks.columns().symbol().map(String::from),\n");
    out.push_str(
        "            symbols: ticks.columns().symbols().map(|s| s.iter().map(|v| v.to_string()).collect()),\n",
    );
    out.push_str("        })\n");
    out.push_str("    }\n");
    out
}

/// Emit the `<endpoint>Stream(...callback)` server-stream terminal — the
/// TypeScript companion to the Python parsed builder's `.stream(handler)`.
///
/// The method takes the endpoint's required positional parameters, then the
/// same trailing `Options` object the buffered method takes (so `timeoutMs`
/// and every optional builder param ride along identically), and finally a
/// JS `callback`. Each decoded gRPC chunk is converted to the typed row
/// array (`Tick[]`) and delivered to `callback` through a napi-rs
/// `ThreadsafeFunction`, which routes the call onto the Node main thread —
/// the only thread allowed to execute V8 — and the Rust future awaits that
/// callback before the next chunk is fetched. The decoder-owned chunk is
/// dropped after the awaited callback returns, so peak memory tracks one
/// chunk, never the full response: the memory-bounded path the `Config` doc
/// points buffered callers at.
///
/// The callback is the LAST positional argument (after the options object)
/// rather than riding inside the options object: a `ThreadsafeFunction`
/// cannot be a `#[napi(object)]` field, and a trailing function argument is
/// the JavaScript idiom for a stream sink. `callback(chunk: Tick[]) => void`
/// is invoked once per gRPC chunk; a slow callback applies back-pressure by
/// delaying the next chunk fetch rather than dropping rows.
fn render_typescript_endpoint_stream_method(endpoint: &GeneratedEndpoint) -> String {
    let method_params = method_params(endpoint);
    let builder_params = builder_params(endpoint);
    let camel_name = to_camel_case(&endpoint.name);
    let stream_camel = format!("{camel_name}Stream");
    let struct_name = options_struct_name(endpoint);
    let tick_class = ts_class_name(&endpoint.return_type);
    let vec_converter = ts_class_vec_converter(&endpoint.return_type);
    let mut out = String::new();

    // Only shardable history endpoints can fan out (see `endpoint_can_fan_out`).
    let fan_out = if super::endpoint_can_fan_out(endpoint) {
        " Under `bulkFetch = \"auto\"` a large history pull may fan out \
         across concurrent sub-requests: every chunk is still delivered exactly \
         once, but chunks from different sub-requests interleave in arrival order \
         rather than the single-stream order (set `bulkFetch = \"off\"` to \
         restore it)."
    } else {
        ""
    };
    let doc = format!(
        "Stream `{name}` rows into `callback` without materialising the full \
         response in memory. `callback(chunk: {tick}[]) => void` is invoked once \
         per server chunk; the chunk is freed before that stream's next chunk is \
         fetched, so peak memory tracks a single chunk rather than the whole \
         result.{fan_out} This is the \
         memory-bounded companion to the `{camel}` method — prefer it \
         for multi-day or full-universe pulls. The returned Promise resolves when \
         the stream drains and rejects (typed like the buffered method) on a wire \
         or decode error. Cancelling the Promise drops the in-flight request. \
         `options` carries the same optional builder parameters and `timeoutMs` \
         as the buffered method; the `callback` is the trailing argument.",
        name = endpoint.name,
        tick = tick_class,
        camel = camel_name,
    );
    out.push_str(&render_rust_doc_block("    ", &doc));
    writeln!(out, "    #[napi(js_name = \"{stream_camel}\")]").unwrap();
    writeln!(out, "    pub async fn {name}_stream(", name = endpoint.name).unwrap();
    out.push_str("        &self,\n");
    for param in &method_params {
        writeln!(
            out,
            "        {}: {},",
            sdk_method_arg_name(param),
            ts_napi_arg_type(param)
        )
        .unwrap();
    }
    writeln!(out, "        options: Option<{struct_name}>,").unwrap();
    // `ErrorStrategy::CalleeHandled` is false, but the body uses
    // `call_async_catch`, so a JS-callback throw is returned as
    // `Err(napi::Error)` and rejects the Promise instead of being routed to
    // `uncaughtException`.
    writeln!(
        out,
        "        callback: napi::threadsafe_function::ThreadsafeFunction<Vec<{tick_class}>, (), Vec<{tick_class}>, napi::Status, false>,"
    )
    .unwrap();
    out.push_str("    ) -> napi::Result<()> {\n");

    out.push_str("        let options = options.unwrap_or_default();\n");
    out.push_str("        let timeout_ms = match options.timeout_ms {\n");
    out.push_str("            Some(ms) => Some(validate_timeout_ms(ms)?),\n");
    out.push_str("            None => None,\n");
    out.push_str("        };\n");
    out.push_str("        let client = self.client_handle()?;\n");

    let has_symbols = method_params
        .iter()
        .any(|param| param.param_type == "Symbols");
    if has_symbols {
        out.push_str("        let symbols = normalize_symbols(symbols);\n");
    }
    for param in &method_params {
        let arg_name = sdk_method_arg_name(param);
        match param.param_type.as_str() {
            "Date" | "Expiration" => {
                writeln!(out, "        let {arg_name} = normalize_date({arg_name});").unwrap();
            }
            _ if is_time_arg(param) => {
                writeln!(out, "        let {arg_name} = normalize_time({arg_name});").unwrap();
            }
            _ => {}
        }
    }
    for param in &builder_params {
        match param.param_type.as_str() {
            "Date" | "Expiration" => {
                writeln!(
                    out,
                    "        let {} = normalize_optional_date(options.{});",
                    param.name, param.name
                )
                .unwrap();
            }
            _ if is_time_arg(param) => {
                writeln!(
                    out,
                    "        let {} = normalize_optional_time(options.{});",
                    param.name, param.name
                )
                .unwrap();
            }
            "Int" => {
                // Validate + narrow the JS `number` to `i32`, rejecting a
                // non-finite, negative, fractional, or out-of-range value
                // with `InvalidParameterError` instead of V8-wrapping it.
                writeln!(
                    out,
                    "        let {name} = validate_optional_nonneg_i32(\"{camel}\", options.{name})?;",
                    name = param.name,
                    camel = napi_field_camel(&param.name),
                )
                .unwrap();
            }
            _ => {
                writeln!(out, "        let {} = options.{};", param.name, param.name).unwrap();
            }
        }
    }

    // Bind the callback behind an `Arc`: the chunk
    // closure the core `request.stream` takes captures the handle, and
    // `ThreadsafeFunction` is `Send + Sync` but does not implement `Clone`
    // in napi-rs 3.x — the outer `Arc` is the canonical share path (same as
    // the FPSS `startStreaming` registration on this client).
    out.push_str("        let callback = std::sync::Arc::new(callback);\n");
    out.push_str("        let callback_error = std::sync::Arc::new(std::sync::Mutex::new(None::<napi::Error>));\n");

    let positional_args = method_params
        .iter()
        .map(|param| {
            if param.param_type == "Symbols" {
                "&refs".into()
            } else if matches!(param.param_type.as_str(), "Date" | "Expiration")
                || is_time_arg(param)
            {
                format!("{}.as_str()", sdk_method_arg_name(param))
            } else {
                format!("&{}", sdk_method_arg_name(param))
            }
        })
        .collect::<Vec<_>>()
        .join(", ");

    // The builder + the gRPC server-stream run on `runtime()` (the reactor
    // that owns the connection's sockets), spawned off the V8 thread exactly
    // like the buffered method, so the Node event loop stays free for the
    // whole drain.
    out.push_str("        spawn_napi_task(async move {\n");
    if has_symbols {
        out.push_str(
            "            let refs: Vec<&str> = symbols.iter().map(|s| s.as_str()).collect();\n",
        );
    }
    writeln!(
        out,
        "            let mut request = client.market_data().{}({});",
        endpoint.name, positional_args
    )
    .unwrap();
    for param in &builder_params {
        writeln!(out, "            if let Some(value) = {} {{", param.name).unwrap();
        let setter_arg = match param.param_type.as_str() {
            "Int" | "Float" | "Bool" => "value".to_string(),
            _ => "value.as_str()".to_string(),
        };
        writeln!(
            out,
            "                request = request.{}({});",
            param.name, setter_arg
        )
        .unwrap();
        out.push_str("            }\n");
    }
    out.push_str("            if let Some(ms) = timeout_ms {\n");
    out.push_str(
        "                request = request.with_deadline(std::time::Duration::from_millis(ms));\n",
    );
    out.push_str("            }\n");
    // Per-chunk: convert the decoder-owned rows to the typed napi row
    // array, hand it to the `ThreadsafeFunction`, and await the JS callback
    // result before the next chunk is fetched. `call_async_catch` turns a
    // thrown JS handler error into `Err(napi::Error)` instead of routing it
    // through `uncaughtException`; the first such error wins and later chunks
    // skip callback invocation while the core stream drains.
    out.push_str(
        "            let callback_error_for_stream = std::sync::Arc::clone(&callback_error);\n",
    );
    out.push_str("            let stream_result = request\n");
    out.push_str("                .stream_ticks_async(move |chunk| {\n");
    out.push_str("                    let callback = std::sync::Arc::clone(&callback);\n");
    out.push_str("                    let callback_error = std::sync::Arc::clone(&callback_error_for_stream);\n");
    out.push_str("                    let rows = if callback_error.lock().unwrap_or_else(|e| e.into_inner()).is_some() {\n");
    out.push_str("                        None\n");
    out.push_str("                    } else {\n");
    writeln!(
        out,
        "                        Some({vec_converter}(chunk.as_slice()))"
    )
    .unwrap();
    out.push_str("                    };\n");
    out.push_str("                    async move {\n");
    out.push_str("                        let Some(rows) = rows else { return; };\n");
    out.push_str(
        "                        if let Err(err) = callback.call_async_catch(rows).await {\n",
    );
    out.push_str("                            let mut guard = callback_error.lock().unwrap_or_else(|e| e.into_inner());\n");
    out.push_str("                            if guard.is_none() {\n");
    out.push_str("                                *guard = Some(err);\n");
    out.push_str("                            }\n");
    out.push_str("                        }\n");
    out.push_str("                    }\n");
    out.push_str("                })\n");
    out.push_str("                .await;\n");
    out.push_str("            if let Some(err) = callback_error.lock().unwrap_or_else(|e| e.into_inner()).take() {\n");
    out.push_str("                Err(err)\n");
    out.push_str("            } else {\n");
    out.push_str("                stream_result.map_err(to_napi_err)\n");
    out.push_str("            }\n");
    out.push_str("        })\n");
    out.push_str("        .await\n");
    out.push_str("    }\n");
    out
}

fn ts_napi_arg_type(param: &super::super::model::GeneratedParam) -> &'static str {
    if param.param_type == "Symbols" {
        "Either<String, Vec<String>>"
    } else if matches!(param.param_type.as_str(), "Date" | "Expiration") || is_time_arg(param) {
        "Either<String, chrono::DateTime<chrono::Utc>>"
    } else {
        "String"
    }
}

/// Convert a snake_case field name to the lowerCamelCase key napi-rs emits
/// for a `#[napi(object)]` field (`max_dte` -> `maxDte`,
/// `strike_range` -> `strikeRange`). Unlike `to_camel_case`, this performs
/// no acronym uppercasing, so the name matches the literal key a JS caller
/// passes — the key a validation rejection message must echo back.
fn napi_field_camel(snake: &str) -> String {
    let mut out = String::with_capacity(snake.len());
    let mut upper_next = false;
    for ch in snake.chars() {
        if ch == '_' {
            upper_next = true;
        } else if upper_next {
            out.extend(ch.to_uppercase());
            upper_next = false;
        } else {
            out.push(ch);
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::super::super::model::{GeneratedParam, ProtoField};
    use super::*;

    fn method_param(name: &str, param_type: &str) -> GeneratedParam {
        GeneratedParam {
            name: name.to_string(),
            description: String::new(),
            param_type: param_type.to_string(),
            required: true,
            binding: "method".to_string(),
            _arg_name: None,
            default: None,
        }
    }

    fn stock_history_eod_endpoint() -> GeneratedEndpoint {
        GeneratedEndpoint {
            name: "stock_history_eod".to_string(),
            description: "stock eod".to_string(),
            category: "stock".to_string(),
            subcategory: "history".to_string(),
            _rest_path: "/v3/stock/history/eod".to_string(),
            grpc_name: "get_stock_history_eod".to_string(),
            request_type: "StockHistoryEodRequest".to_string(),
            query_type: "StockHistoryEodQuery".to_string(),
            fields: Vec::<ProtoField>::new(),
            params: vec![
                method_param("symbol", "Symbol"),
                method_param("start_date", "Date"),
                method_param("end_date", "Date"),
            ],
            return_type: "EodTicks".to_string(),
            kind: "marketData".to_string(),
            list_column: None,
            vendor_docstring: None,
        }
    }

    #[test]
    fn market_data_stream_awaits_callback_and_catches_js_errors() {
        let rendered = render_typescript_endpoint_stream_method(&stock_history_eod_endpoint());

        assert!(rendered.contains("spawn_napi_task(async move"));
        assert!(rendered.contains(".stream_ticks_async(move |chunk|"));
        assert!(rendered.contains("callback.call_async_catch(rows).await"));
        assert!(rendered.contains("let callback_error ="));
        assert!(!rendered.contains("callback.call(rows"));
    }

    // Fan-out note gating (see `endpoint_can_fan_out`): a daily-only EOD
    // stream is never sharded, so its doc must not claim a fan-out; a
    // shardable intraday-history stream must keep the note.
    #[test]
    fn stream_doc_omits_fan_out_note_for_non_shardable_endpoint() {
        let rendered = render_typescript_endpoint_stream_method(&stock_history_eod_endpoint());
        assert!(
            !rendered.contains("may fan out"),
            "eod stream must not claim a fan-out"
        );
    }

    #[test]
    fn stream_doc_keeps_fan_out_note_for_shardable_history_endpoint() {
        // The predicate is model-derived (same as the runtime shardable
        // set): a `history*` endpoint carrying the intraday window.
        let mut ep = stock_history_eod_endpoint();
        ep.name = "stock_history_trade".to_string();
        ep.params.push(method_param("start_time", "Time"));
        ep.params.push(method_param("end_time", "Time"));
        let rendered = render_typescript_endpoint_stream_method(&ep);
        assert!(
            rendered.contains("may fan out"),
            "shardable history stream must keep the fan-out note"
        );
    }

    #[test]
    fn stream_doc_keeps_fan_out_note_for_at_time_endpoint() {
        // The at_time families band their date range, so their stream
        // docs must carry the same interleaving caveat.
        let mut ep = stock_history_eod_endpoint();
        ep.name = "stock_at_time_trade".to_string();
        ep.subcategory = "at_time".to_string();
        let rendered = render_typescript_endpoint_stream_method(&ep);
        assert!(
            rendered.contains("may fan out"),
            "at_time stream must carry the fan-out note"
        );
    }
}

fn ts_napi_optional_type(param: &super::super::model::GeneratedParam) -> &'static str {
    match param.param_type.as_str() {
        // `Int` filters ride in as a JS `number` (f64) and are validated +
        // narrowed to `i32` in the method body via `validate_optional_nonneg_i32`,
        // rather than typed `i32` here where V8's `ToInt32` would silently
        // wrap a hostile or oversized input instead of rejecting it.
        "Int" => "Option<f64>",
        "Float" => "Option<f64>",
        "Bool" => "Option<bool>",
        "Date" | "Expiration" => "Option<Either<String, chrono::DateTime<chrono::Utc>>>",
        _ if is_time_arg(param) => "Option<Either<String, chrono::DateTime<chrono::Utc>>>",
        _ => "Option<String>",
    }
}
