// @generated DO NOT EDIT — regenerated by build.rs from config_surface.toml
//
// Mechanical scalar config accessors for the Python `Config` pyclass.
// `include!`-d into `lib.rs`, which keeps the divergent accessors
// (enum-parsing, string, `Option`-widened, policy-aware) hand-written.

#[pymethods]
impl Config {
    /// Set the reconnect delay (ms) honoured for generic transient
    /// disconnects (TimedOut, ServerRestarting, Unspecified, …).
    /// Plumbed through to the streaming I/O loop at connect time.
    /// Default ``250``.
    #[setter]
    fn set_reconnect_wait_ms(&self, ms: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.wait_ms = ms;
    }

    /// Current reconnect ``wait_ms`` value (default ``250``).
    #[getter]
    fn get_reconnect_wait_ms(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.wait_ms
    }

    /// Set the reconnect delay (ms) honoured for ``TooManyRequests``
    /// rate-limited disconnects. Default ``130_000`` (matches the
    /// JVM terminal's 130 s rate-limit cooldown).
    #[setter]
    fn set_reconnect_wait_rate_limited_ms(&self, ms: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.wait_rate_limited_ms = ms;
    }

    /// Current reconnect ``wait_rate_limited_ms`` value (default ``130_000``).
    #[getter]
    fn get_reconnect_wait_rate_limited_ms(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.wait_rate_limited_ms
    }

    /// Set the cap (ms) on the exponential generic-transient reconnect
    /// ladder. The ladder starts at ``reconnect_wait_ms`` and doubles
    /// per consecutive attempt up to this value. Default ``30_000``.
    #[setter]
    fn set_reconnect_wait_max_ms(&self, ms: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.wait_max_ms = ms;
    }

    /// Current reconnect ``wait_max_ms`` value (default ``30_000``).
    #[getter]
    fn get_reconnect_wait_max_ms(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.wait_max_ms
    }

    /// Set the flat reconnect cadence (ms) for ``ServerRestarting``
    /// disconnects. Default ``5_000``.
    #[setter]
    fn set_reconnect_wait_server_restart_ms(&self, ms: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.wait_server_restart_ms = ms;
    }

    /// Current reconnect ``wait_server_restart_ms`` value (default ``5_000``).
    #[getter]
    fn get_reconnect_wait_server_restart_ms(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.wait_server_restart_ms
    }

    /// Set the subscription-replay burst size used after an
    /// auto-reconnect: frames are written in bursts of this many, each
    /// burst flushed and followed by a jittered ``replay_pace_ms``
    /// pause. Minimum ``1`` (validated at connect). Default ``50``.
    #[setter]
    fn set_reconnect_replay_burst_size(&self, n: u32) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.replay_burst_size = n;
    }

    /// Current ``replay_burst_size`` value (default ``50``).
    #[getter]
    fn get_reconnect_replay_burst_size(&self) -> u32 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.replay_burst_size
    }

    /// Set the pause (ms) between subscription-replay bursts after an
    /// auto-reconnect. ``0`` removes the pause. Default ``5``.
    #[setter]
    fn set_reconnect_replay_pace_ms(&self, ms: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.replay_pace_ms = ms;
    }

    /// Current ``replay_pace_ms`` value (default ``5``).
    #[getter]
    fn get_reconnect_replay_pace_ms(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.replay_pace_ms
    }

    /// Set the streaming read timeout (ms): the no-frames deadline after
    /// which the streaming I/O loop declares the session dead and
    /// reconnects. Default ``10_000``; validated to ``[100, 60_000]``.
    #[setter]
    fn set_streaming_timeout_ms(&self, ms: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.timeout_ms = ms;
    }

    /// Current ``streaming.timeout_ms`` value (default ``10_000``).
    #[getter]
    fn get_streaming_timeout_ms(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.timeout_ms
    }

    /// Set the per-server connect timeout (ms) for the streaming
    /// connection. Default
    /// ``2_000``; validated to ``[1_000, 60_000]``.
    #[setter]
    fn set_streaming_connect_timeout_ms(&self, ms: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.connect_timeout_ms = ms;
    }

    /// Current ``streaming.connect_timeout_ms`` value (default ``2_000``).
    #[getter]
    fn get_streaming_connect_timeout_ms(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.connect_timeout_ms
    }

    /// Set the streaming heartbeat ping interval (ms). Default ``100``;
    /// validated to ``[100, 300_000]``.
    #[setter]
    fn set_streaming_ping_interval_ms(&self, ms: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.ping_interval_ms = ms;
    }

    /// Current ``streaming.ping_interval_ms`` value (default ``100``).
    #[getter]
    fn get_streaming_ping_interval_ms(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.ping_interval_ms
    }

    /// Set the per-iteration blocking-read slice (ms) for the
    /// streaming I/O loop. Default ``25``; validated to ``[10, 500]``.
    #[setter]
    fn set_streaming_io_read_slice_ms(&self, ms: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.io_read_slice_ms = ms;
    }

    /// Current ``streaming.io_read_slice_ms`` value (default ``25``).
    #[getter]
    fn get_streaming_io_read_slice_ms(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.io_read_slice_ms
    }

    /// Set the TCP keepalive idle time (seconds) before the first
    /// kernel probe on a silent streaming socket. Default ``5``;
    /// validated to ``[1, 7_200]``.
    #[setter]
    fn set_streaming_keepalive_idle_secs(&self, secs: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.keepalive_idle_secs = secs;
    }

    /// Current ``streaming.keepalive_idle_secs`` value (default ``5``).
    #[getter]
    fn get_streaming_keepalive_idle_secs(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.keepalive_idle_secs
    }

    /// Set the interval (seconds) between TCP keepalive probes.
    /// Default ``2``; validated to ``[1, 75]``.
    #[setter]
    fn set_streaming_keepalive_interval_secs(&self, secs: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.keepalive_interval_secs = secs;
    }

    /// Current ``streaming.keepalive_interval_secs`` value (default ``2``).
    #[getter]
    fn get_streaming_keepalive_interval_secs(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.keepalive_interval_secs
    }

    /// Set the number of unanswered TCP keepalive probes after which
    /// the kernel declares the streaming connection dead (where the
    /// platform exposes the knob). Default ``2``; validated to
    /// ``[1, 10]``.
    #[setter]
    fn set_streaming_keepalive_retries(&self, n: u32) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.keepalive_retries = n;
    }

    /// Current ``streaming.keepalive_retries`` value (default ``2``).
    #[getter]
    fn get_streaming_keepalive_retries(&self) -> u32 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.keepalive_retries
    }

    /// Current ``streaming.ring_size`` value (default ``131_072``).
    #[getter]
    fn get_streaming_ring_size(&self) -> usize {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.ring_size
    }

    /// Set how the streaming consumer waits when the event ring is empty.
    /// Accepts ``"spin"`` (default), ``"busyspin"``, ``"park"``, or
    /// ``"backoff"`` (case-insensitive). ``"spin"`` and ``"busyspin"`` both hold
    /// ~100% of one core and differ only in jitter; only ``"park"`` and
    /// ``"backoff"`` lower idle CPU. The park / backoff sleep length is
    /// ``park_interval_us``.
    #[setter]
    fn set_wait_mode(&self, mode: &str) -> PyResult<()> {
        let parsed = config::WaitMode::parse(mode).ok_or_else(|| {
            crate::errors::invalid_parameter_err(format!(
                "unknown wait_mode: {mode:?} (expected \"spin\", \"busyspin\", \"park\" or \"backoff\")"
            ))
        })?;
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.wait_mode = parsed;
        Ok(())
    }

    /// Current streaming consumer wait mode as a lowercase string.
    #[getter]
    fn get_wait_mode(&self) -> &'static str {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.wait_mode.as_str()
    }

    /// Set the park / backoff idle sleep length in microseconds for the streaming
    /// consumer. Used only when the wait mode is ``"park"`` or ``"backoff"``.
    /// Validated ``[50, 1000000]`` at connect time. Default ``1000`` (= 1 ms).
    #[setter]
    fn set_park_interval_us(&self, us: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.park_interval_us = us;
    }

    /// Current streaming ``park_interval_us`` value in microseconds (default
    /// ``1000``, = 1 ms).
    #[getter]
    fn get_park_interval_us(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.streaming.park_interval_us
    }

    /// Set the wall-clock envelope (seconds) for one
    /// market-data-channel retry sequence, measured from the first
    /// attempt. ``0`` disables the envelope (attempt budget only).
    /// Default ``300``.
    #[setter]
    fn set_retry_max_elapsed_secs(&self, secs: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.retry.max_elapsed = std::time::Duration::from_secs(secs);
    }

    /// Current ``retry.max_elapsed`` value in seconds (default ``300``;
    /// ``0`` = disabled).
    #[getter]
    fn get_retry_max_elapsed_secs(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.retry.max_elapsed.as_secs()
    }

    /// Toggle AWS-style full jitter on the flatfile retry ladder.
    /// Default ``True``; ``False`` gives the deterministic schedule,
    /// useful for tests that assert exact timings.
    #[setter]
    fn set_flatfiles_jitter(&self, jitter: bool) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.jitter = jitter;
    }

    /// Current ``flatfiles.jitter`` value (default ``True``).
    #[getter]
    fn get_flatfiles_jitter(&self) -> bool {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.jitter
    }

    /// Set the initial backoff delay (ms) for the market-data-channel retry policy.
    /// Default ``250``. Subsequent retries double from here, capped
    /// at :attr:`retry_max_delay_ms`.
    #[setter]
    fn set_retry_initial_delay_ms(&self, ms: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.retry.initial_delay = std::time::Duration::from_millis(ms);
    }

    /// Set the upper-bound backoff delay (ms) for the
    /// market-data-channel retry policy. Default ``30_000`` (30 s).
    #[setter]
    fn set_retry_max_delay_ms(&self, ms: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.retry.max_delay = std::time::Duration::from_millis(ms);
    }

    /// Set the total attempt budget for the market-data-channel retry policy. ``1``
    /// disables retry (single call only); higher values permit retries
    /// up to ``max_attempts - 1`` after the initial call. Default ``20``.
    #[setter]
    fn set_retry_max_attempts(&self, n: u32) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.retry.max_attempts = n;
    }

    /// Current ``retry.max_attempts`` value.
    #[getter]
    fn get_retry_max_attempts(&self) -> u32 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.retry.max_attempts
    }

    /// Toggle AWS-style full-jitter on the market-data-channel retry policy. Default
    /// ``True``. ``False`` gives the deterministic backoff schedule
    /// ``min(max_delay, initial * 2^attempt)``, useful for tests that
    /// need to assert exact timings.
    #[setter]
    fn set_retry_jitter(&self, jitter: bool) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.retry.jitter = jitter;
    }

    /// Current ``retry.jitter`` value.
    #[getter]
    fn get_retry_jitter(&self) -> bool {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.retry.jitter
    }

    /// Set the total attempt budget for the flatfile driver retry loop.
    /// ``1`` disables retry (single call only); higher values permit
    /// retries up to ``max_attempts - 1`` after the initial call.
    /// Default ``10``. Validated to the range ``[1, 100]`` at connect
    /// time.
    #[setter]
    fn set_flatfiles_max_attempts(&self, n: u32) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.max_attempts = n;
    }

    /// Current ``flatfiles.max_attempts`` value.
    #[getter]
    fn get_flatfiles_max_attempts(&self) -> u32 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.max_attempts
    }

    /// Set the initial backoff delay (seconds) for the flatfile driver
    /// retry loop. Doubles per attempt up to
    /// :attr:`flatfiles_max_backoff_secs`. Default ``1``.
    #[setter]
    fn set_flatfiles_initial_backoff_secs(&self, secs: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.initial_backoff = std::time::Duration::from_secs(secs);
    }

    /// Current ``flatfiles.initial_backoff`` value in seconds.
    #[getter]
    fn get_flatfiles_initial_backoff_secs(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.initial_backoff.as_secs()
    }

    /// Set the upper-bound backoff delay (seconds) for the flatfile
    /// driver retry loop. The doubling schedule never exceeds this
    /// value regardless of attempt number. Default ``30``. Must be
    /// greater than or equal to :attr:`flatfiles_initial_backoff_secs`
    /// (rejected at connect-time validate otherwise).
    #[setter]
    fn set_flatfiles_max_backoff_secs(&self, secs: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.max_backoff = std::time::Duration::from_secs(secs);
    }

    /// Current ``flatfiles.max_backoff`` value in seconds.
    #[getter]
    fn get_flatfiles_max_backoff_secs(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.max_backoff.as_secs()
    }

    /// Set the TCP + TLS connect timeout (seconds) for one flatfile-host
    /// attempt. Bounds the connect/auth handshake before the attempt is
    /// abandoned and the next host (or the retry ladder) takes over.
    /// Default ``10``.
    #[setter]
    fn set_flatfiles_connect_timeout_secs(&self, secs: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.connect_timeout_secs = secs;
    }

    /// Current ``flatfiles.connect_timeout_secs`` value in seconds.
    #[getter]
    fn get_flatfiles_connect_timeout_secs(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.connect_timeout_secs
    }

    /// Set the read timeout (seconds) for a single flatfile response
    /// frame. Bounds the wait for the next chunk once streaming has begun
    /// so a mid-stream stall fails over instead of blocking forever.
    /// Default ``60``.
    #[setter]
    fn set_flatfiles_read_timeout_secs(&self, secs: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.read_timeout_secs = secs;
    }

    /// Current ``flatfiles.read_timeout_secs`` value in seconds.
    #[getter]
    fn get_flatfiles_read_timeout_secs(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.flatfiles.read_timeout_secs
    }

    /// Override the market-data gRPC port. Companion to `market_data_host` —
    /// same rationale and same test-only usage.
    #[setter]
    fn set_market_data_port(&self, port: u16) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.port = port;
    }

    /// Current market-data gRPC port.
    #[getter]
    fn get_market_data_port(&self) -> u16 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.port
    }

    /// Set the warning threshold (in bytes) for buffered (non-streaming)
    /// historical responses. Endpoints whose decoded total exceeds this
    /// value log a `tracing::warn!` pointing the caller at the
    /// ``.stream()`` surface; the data is still delivered. ``0``
    /// disables the warning entirely. Default is ``100 * 1024 * 1024``
    /// (100 MiB).
    ///
    /// Examples
    /// --------
    ///     cfg = Config.production()
    ///     cfg.warn_on_buffered_threshold_bytes = 50 * 1024 * 1024
    #[setter]
    fn set_warn_on_buffered_threshold_bytes(&self, n: usize) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.warn_on_buffered_threshold_bytes = n;
    }

    /// Current ``warn_on_buffered_threshold_bytes`` setting (bytes).
    #[getter]
    fn get_warn_on_buffered_threshold_bytes(&self) -> usize {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.warn_on_buffered_threshold_bytes
    }

    /// Set the default per-request deadline (in seconds) for market-data
    /// queries. Bounds every request that did not call
    /// ``with_deadline(...)``, so a live-but-silent stream resolves to a
    /// timeout instead of blocking forever. ``0`` no longer disables the
    /// default: it is floored to the ``300``-second default at request time,
    /// so the deadline always applies. Default is ``300`` (5 minutes).
    ///
    /// Examples
    /// --------
    ///     cfg = Config.production()
    ///     cfg.request_timeout_secs = 120
    #[setter]
    fn set_request_timeout_secs(&self, secs: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.request_timeout_secs = secs;
    }

    /// Current market-data ``request_timeout_secs`` setting. A stored ``0``
    /// is floored to the ``300``-second default at request time rather than
    /// disabling the deadline.
    #[getter]
    fn get_request_timeout_secs(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.request_timeout_secs
    }

    /// Set the initial per-stream HTTP/2 flow-control window (in KB) for the
    /// market-data gRPC channel. A larger window raises the throughput ceiling
    /// on bulk streaming pulls before HTTP/2 backpressure kicks in. The value
    /// is clamped into ``[64, 2_097_151]`` KB at validate/connect time.
    /// Default is ``8192`` (8 MiB).
    ///
    /// Examples
    /// --------
    ///     cfg = Config.production()
    ///     cfg.market_data_stream_window_size_kb = 4096
    #[setter]
    fn set_market_data_stream_window_size_kb(&self, kb: usize) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.stream_window_size_kb = kb;
    }

    /// Current per-stream HTTP/2 flow-control window (KB) for the market-data
    /// gRPC channel (default ``8192``).
    #[getter]
    fn get_market_data_stream_window_size_kb(&self) -> usize {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.stream_window_size_kb
    }

    /// Set the initial connection-level HTTP/2 flow-control window (in KB) for
    /// the market-data gRPC channel. A larger window raises the throughput
    /// ceiling on bulk streaming pulls before HTTP/2 backpressure kicks in.
    /// The value is clamped into ``[64, 2_097_151]`` KB at validate/connect
    /// time. Default is ``16384`` (16 MiB).
    ///
    /// Examples
    /// --------
    ///     cfg = Config.production()
    ///     cfg.market_data_connection_window_size_kb = 16384
    #[setter]
    fn set_market_data_connection_window_size_kb(&self, kb: usize) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.connection_window_size_kb = kb;
    }

    /// Current connection-level HTTP/2 flow-control window (KB) for the
    /// market-data gRPC channel (default ``16384``).
    #[getter]
    fn get_market_data_connection_window_size_kb(&self) -> usize {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.connection_window_size_kb
    }

    /// Automatic bulk-fetch sharding policy for history pulls (buffered and
    /// chunk-streaming alike). Accepts ``"auto"`` (default: a large history
    /// pull's requested time or date range is split into equal concurrent
    /// bands across the account's concurrent-request budget — buffered
    /// pulls are merged back
    /// into exactly the rows of the single-stream response, single-contract,
    /// stock, and index pulls in the exact single-stream order and
    /// option-chain pulls in a deterministic canonical order grouped by
    /// expiration, strike, and right; streaming pulls forward each band's
    /// chunks as they arrive, every chunk exactly once but interleaved
    /// across bands in arrival order; small pulls are never sharded) or
    /// ``"off"`` (every query runs as a single stream, in the server's own
    /// row and chunk order), case-insensitive.
    #[setter]
    fn set_bulk_fetch(&self, policy: &str) -> PyResult<()> {
        let parsed = config::BulkFetchPolicy::parse(policy).ok_or_else(|| {
            crate::errors::invalid_parameter_err(format!(
                "unknown bulk_fetch: {policy:?} (expected \"auto\" or \"off\")"
            ))
        })?;
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.bulk_fetch = parsed;
        Ok(())
    }

    /// Current bulk-fetch sharding policy as a lowercase string.
    #[getter]
    fn get_bulk_fetch(&self) -> &'static str {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.bulk_fetch.as_str()
    }

    /// Upper bound on concurrent sub-requests per sharded bulk fetch.
    /// ``None`` (the default) uses the account's full concurrent-request
    /// budget (the tier-derived channel-pool size resolved at connect time);
    /// an ``int`` caps the fan-out. The applied value is clamped into
    /// ``[1, pool_size]`` when a plan is built, and validation floors an
    /// explicit ``0`` to ``1``.
    #[setter]
    fn set_shard_concurrency(&self, n: Option<u32>) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.shard_concurrency = n;
    }

    /// Current ``shard_concurrency`` setting. ``None`` means a sharded pull
    /// uses the account's full concurrent-request budget; an ``int`` is the
    /// configured cap.
    #[getter]
    fn get_shard_concurrency(&self) -> Option<u32> {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data.shard_concurrency
    }

    /// Current ``retry.initial_delay`` value in ms.
    #[getter]
    fn get_retry_initial_delay_ms(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        u64::try_from(guard.retry.initial_delay.as_millis()).unwrap_or(u64::MAX)
    }

    /// Current ``retry.max_delay`` value in ms.
    #[getter]
    fn get_retry_max_delay_ms(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        u64::try_from(guard.retry.max_delay.as_millis()).unwrap_or(u64::MAX)
    }

    /// Set the per-class transient-failure attempt budget for the
    /// auto-reconnect path. Default `30`. No effect unless the
    /// reconnect policy is `Auto`.
    #[setter]
    fn set_reconnect_max_attempts(&self, max_attempts: u32) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        if let config::ReconnectPolicy::Auto(ref mut limits) = guard.reconnect.policy {
            limits.max_attempts = max_attempts;
        }
    }

    /// Current generic-transient reconnect attempt budget (default
    /// `30`). Reads the default-limits value when the policy is not
    /// `Auto`.
    #[getter]
    fn get_reconnect_max_attempts(&self) -> u32 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        match &guard.reconnect.policy {
            config::ReconnectPolicy::Auto(limits) => limits.max_attempts,
            _ => config::ReconnectAttemptLimits::default().max_attempts,
        }
    }

    /// Set the per-class rate-limited (`TooManyRequests`) attempt budget
    /// for the auto-reconnect path. Default `100`. No effect unless the
    /// reconnect policy is `Auto`.
    #[setter]
    fn set_reconnect_max_rate_limited_attempts(&self, max_rate_limited_attempts: u32) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        if let config::ReconnectPolicy::Auto(ref mut limits) = guard.reconnect.policy {
            limits.max_rate_limited_attempts = max_rate_limited_attempts;
        }
    }

    /// Current rate-limited reconnect attempt budget (default `100`).
    /// Reads the default-limits value when the policy is not `Auto`.
    #[getter]
    fn get_reconnect_max_rate_limited_attempts(&self) -> u32 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        match &guard.reconnect.policy {
            config::ReconnectPolicy::Auto(limits) => limits.max_rate_limited_attempts,
            _ => config::ReconnectAttemptLimits::default().max_rate_limited_attempts,
        }
    }

    /// Set the ``ServerRestarting`` reconnect attempt budget. Default
    /// ``60``. No effect unless the reconnect policy is ``Auto``.
    #[setter]
    fn set_reconnect_max_server_restart_attempts(&self, n: u32) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        if let config::ReconnectPolicy::Auto(ref mut limits) = guard.reconnect.policy {
            limits.max_server_restart_attempts = n;
        }
    }

    /// Current ``ServerRestarting`` reconnect attempt budget (default
    /// ``60``). Reads the default-limits value when the policy is not
    /// ``Auto``.
    #[getter]
    fn get_reconnect_max_server_restart_attempts(&self) -> u32 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        match &guard.reconnect.policy {
            config::ReconnectPolicy::Auto(limits) => limits.max_server_restart_attempts,
            _ => config::ReconnectAttemptLimits::default().max_server_restart_attempts,
        }
    }

    /// Set the wall-clock reconnect envelope (seconds) for the
    /// generic-transient and server-restart classes, measured from the
    /// first attempt of a consecutive-reconnect sequence. ``0``
    /// disables the envelope (attempt budgets only). Default ``300``.
    /// No effect unless the reconnect policy is ``Auto``.
    #[setter]
    fn set_reconnect_max_elapsed_secs(&self, secs: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        if let config::ReconnectPolicy::Auto(ref mut limits) = guard.reconnect.policy {
            limits.max_elapsed = std::time::Duration::from_secs(secs);
        }
    }

    /// Current wall-clock reconnect envelope in seconds (default
    /// ``300``; ``0`` = disabled). Reads the default-limits value when
    /// the policy is not ``Auto``.
    #[getter]
    fn get_reconnect_max_elapsed_secs(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        match &guard.reconnect.policy {
            config::ReconnectPolicy::Auto(limits) => limits.max_elapsed.as_secs(),
            _ => config::ReconnectAttemptLimits::default()
                .max_elapsed
                .as_secs(),
        }
    }

    /// Set the continuous successful-data-flow window (in seconds)
    /// after which the auto-reconnect attempt counters reset. Default
    /// ``60``. No effect unless the reconnect policy is ``Auto``.
    #[setter]
    fn set_reconnect_stable_window_secs(&self, secs: u64) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        if let config::ReconnectPolicy::Auto(ref mut limits) = guard.reconnect.policy {
            limits.stable_window = std::time::Duration::from_secs(secs);
        }
    }

    /// Current stable-window reset interval in seconds (default `60`).
    /// Reads the default-limits value when the policy is not `Auto`.
    #[getter]
    fn get_reconnect_stable_window_secs(&self) -> u64 {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        match &guard.reconnect.policy {
            config::ReconnectPolicy::Auto(limits) => limits.stable_window.as_secs(),
            _ => config::ReconnectAttemptLimits::default()
                .stable_window
                .as_secs(),
        }
    }

    /// Set the Nexus auth URL. Default matches the upstream production
    /// endpoint; override to redirect at a staging cluster.
    #[setter]
    fn set_nexus_url(&self, url: String) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.auth.nexus_url = url;
    }

    /// Current ``auth.nexus_url`` value.
    #[getter]
    fn get_nexus_url(&self) -> String {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.auth.nexus_url.clone()
    }

    /// Set the ``QueryInfo.client_type`` identifier. Default is
    /// ``"rust-thetadatadx"``; override to identify a deployment fleet
    /// in server-side dashboards.
    #[setter]
    fn set_client_type(&self, client_type: String) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.auth.client_type = client_type;
    }

    /// Current ``auth.client_type`` value.
    #[getter]
    fn get_client_type(&self) -> String {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.auth.client_type.clone()
    }

    /// Override the market-data gRPC host. Used by structural tests that
    /// need to point the market-data channel at a known-refused endpoint
    /// to prove the streaming-only surface never opens it; production
    /// code paths should keep the `Config::production()` default.
    #[setter]
    fn set_market_data_host(&self, host: String) {
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.set_market_data_host(host);
    }

    /// Current market-data gRPC host.
    #[getter]
    fn get_market_data_host(&self) -> String {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.market_data_host().to_string()
    }

    /// Set the jitter strategy applied to every reconnect delay.
    /// Accepts ``"full"`` (default) or ``"none"`` (case-insensitive).
    #[setter]
    fn set_reconnect_jitter(&self, mode: &str) -> PyResult<()> {
        let parsed = config::JitterMode::parse(mode).ok_or_else(|| {
            crate::errors::invalid_parameter_err(format!(
                "unknown reconnect_jitter: {mode:?} (expected \"full\" or \"none\")"
            ))
        })?;
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.jitter = parsed;
        Ok(())
    }

    /// Current reconnect jitter mode as a lowercase string.
    #[getter]
    fn get_reconnect_jitter(&self) -> &'static str {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.reconnect.jitter.as_str()
    }

    /// Set the Prometheus exporter port. ``None`` (the default) keeps
    /// the exporter disabled; an ``int`` binds an HTTP listener whose
    /// ``/metrics`` endpoint exposes every counter and histogram.
    ///
    /// Raises ``ValueError`` if the value is outside the ``u16`` range
    /// (``0..=65535``).
    #[setter]
    fn set_metrics_port(&self, port: Option<u32>) -> PyResult<()> {
        let resolved = match port {
            Some(v) => Some(u16::try_from(v).map_err(|_| {
                crate::errors::invalid_parameter_err(format!("metrics_port must be in 0..=65535; got {v}"))
            })?),
            None => None,
        };
        let mut guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.metrics.port = resolved;
        Ok(())
    }

    /// Current ``metrics.port`` setting. ``None`` means the exporter is
    /// disabled; an ``int`` is the bound port.
    #[getter]
    fn get_metrics_port(&self) -> Option<u16> {
        let guard = self.inner.lock().unwrap_or_else(|e| e.into_inner());
        guard.metrics.port
    }

}
