//! Emitters that write generated Rust artifacts into `OUT_DIR` at build time.
//!
//! These feed the crate's `include!()` sites for the endpoint registry, the
//! shared endpoint dispatch runtime, and the three per-kind MDDS
//! `MarketDataClient` extension impls (list, parsed, streaming), consumed by
//! `thetadatadx-rs/src/mdds/endpoints.rs`. The [`generate_all`] entry
//! point is wired from `build_support::run()`.

use std::fmt::Write as _;
use std::path::Path;

use super::super::build_helpers::{call_arg_name, optional_getter_name, required_getter_name};
use super::super::helpers::{
    endpoint_streams_repr_c_ticks, is_method_call_param, is_simple_list_endpoint,
    is_streaming_endpoint,
};
use super::super::model::{GeneratedEndpoint, GeneratedParam, ParsedEndpoints};
use super::super::parser::load_endpoint_specs;
use super::mdds::{
    generate_mdds_list_endpoint, generate_mdds_parsed_endpoint, generate_mdds_streaming_endpoint,
};

/// Loads the endpoint specs and writes every generated Rust artifact into
/// `OUT_DIR`: the registry, the buffered and streaming dispatch runtimes, and
/// the three per-kind `MarketDataClient` extension impls.
pub fn generate_all() -> Result<(), Box<dyn std::error::Error>> {
    let parsed = load_endpoint_specs()?;
    generate_endpoint_registry(&parsed)?;
    generate_endpoint_runtime(&parsed)?;
    generate_endpoint_stream_runtime(&parsed)?;
    generate_mdds_endpoints(&parsed)?;
    println!("cargo:rerun-if-changed=endpoint_surface.toml");
    println!("cargo:rerun-if-changed=proto/mdds.proto");
    // `OUT_DIR` emitter templates consumed via `include_str!` here and in
    // `mdds.rs`. `include_str!` already registers these as compilation-time
    // dependencies, but we also emit `rerun-if-changed` so `cargo build`
    // re-triggers the generator when a template is edited.
    for template in BUILD_OUT_TEMPLATES {
        println!("cargo:rerun-if-changed=build_support/endpoints/render/templates/{template}");
    }
    Ok(())
}

const BUILD_OUT_TEMPLATES: &[&str] = &[
    "mdds/stream_method_header.rs.tmpl",
    "mdds/stub_call_error_arm.rs.tmpl",
    "mdds/metrics_result_block.rs.tmpl",
    "build_out/invoke_generated_endpoint_preamble.rs.tmpl",
    "build_out/invoke_generated_endpoint_stream_preamble.rs.tmpl",
];

fn generate_endpoint_registry(parsed: &ParsedEndpoints) -> Result<(), Box<dyn std::error::Error>> {
    let code = render_endpoint_registry(parsed);
    let out_dir = std::env::var("OUT_DIR")?;
    let dest = Path::new(&out_dir).join("registry_generated.rs");
    std::fs::write(&dest, &code)?;
    Ok(())
}

/// Render the endpoint registry as a Rust source string. Pure helper
/// (no I/O) so unit tests can drive it with synthetic endpoints and
/// assert the emitted source parses.
fn render_endpoint_registry(parsed: &ParsedEndpoints) -> String {
    let mut code = String::new();
    code.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n",
    );
    code.push_str("// (validated against proto/mdds.proto)\n\n");
    emit_registry_enums_and_helpers(&mut code, parsed);
    code.push_str("pub static ENDPOINTS: &[EndpointMeta] = &[\n");

    for endpoint in &parsed.endpoints {
        // Streaming endpoints use chunk-by-chunk callback semantics and are not
        // part of the collect-then-return registry.
        if is_streaming_endpoint(endpoint) {
            continue;
        }
        code.push_str("    EndpointMeta {\n");
        // Strings from the upstream surface spec are embedded via `{:?}`
        // so Rust's Debug impl escapes any `"`, `\`, or newline inside
        // the description without the build emitting uncompilable code.
        writeln!(code, "        name: {:?},", endpoint.name).unwrap();
        writeln!(code, "        description: {:?},", endpoint.description).unwrap();
        writeln!(code, "        category: {:?},", endpoint.category).unwrap();
        writeln!(code, "        subcategory: {:?},", endpoint.subcategory).unwrap();
        writeln!(code, "        rest_path: {:?},", endpoint._rest_path).unwrap();

        if endpoint.params.is_empty() {
            code.push_str("        params: &[],\n");
        } else {
            code.push_str("        params: &[\n");
            for param in &endpoint.params {
                code.push_str("            ParamMeta {\n");
                writeln!(code, "                name: {:?},", param.name).unwrap();
                writeln!(
                    code,
                    "                description: {:?},",
                    param.description
                )
                .unwrap();
                writeln!(
                    code,
                    "                param_type: ParamType::{},",
                    param.param_type
                )
                .unwrap();
                writeln!(code, "                required: {},", param.required).unwrap();
                code.push_str("            },\n");
            }
            code.push_str("        ],\n");
        }

        writeln!(
            code,
            "        returns: ReturnType::{},",
            endpoint.return_type
        )
        .unwrap();
        code.push_str("    },\n");
    }

    code.push_str("];\n");
    code
}

fn emit_registry_enums_and_helpers(code: &mut String, parsed: &ParsedEndpoints) {
    let mut param_types: Vec<&str> = Vec::new();
    let mut return_types: Vec<&str> = Vec::new();
    let mut categories: Vec<&str> = Vec::new();

    for endpoint in &parsed.endpoints {
        if is_streaming_endpoint(endpoint) {
            continue;
        }
        if !categories.contains(&endpoint.category.as_str()) {
            categories.push(endpoint.category.as_str());
        }
        if !return_types.contains(&endpoint.return_type.as_str()) {
            return_types.push(endpoint.return_type.as_str());
        }
        for param in &endpoint.params {
            if !param_types.contains(&param.param_type.as_str()) {
                param_types.push(param.param_type.as_str());
            }
        }
    }

    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    code.push_str("pub enum ParamType {\n");
    for param_type in &param_types {
        writeln!(code, "    {param_type},").unwrap();
    }
    code.push_str("}\n\n");

    code.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq)]\n");
    code.push_str("pub enum ReturnType {\n");
    for return_type in &return_types {
        writeln!(code, "    {return_type},").unwrap();
    }
    code.push_str("}\n\n");

    code.push_str("pub const CATEGORIES: &[&str] = &[\n");
    for category in &categories {
        writeln!(code, "    {category:?},").unwrap();
    }
    code.push_str("];\n\n");

    code.push_str("#[must_use]\n");
    code.push_str("pub fn param_type_to_json_type(pt: ParamType) -> &'static str {\n");
    code.push_str("    match pt {\n");
    for param_type in &param_types {
        let json_type = match *param_type {
            "Float" => "number",
            "Int" => "integer",
            "Bool" => "boolean",
            _ => "string",
        };
        writeln!(code, "        ParamType::{param_type} => {json_type:?},").unwrap();
    }
    code.push_str("    }\n");
    code.push_str("}\n\n");
}

fn generate_endpoint_runtime(parsed: &ParsedEndpoints) -> Result<(), Box<dyn std::error::Error>> {
    let mut code = String::new();
    code.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n",
    );
    code.push_str("// (validated against proto/mdds.proto)\n\n");
    code.push_str(include_str!(
        "templates/build_out/invoke_generated_endpoint_preamble.rs.tmpl"
    ));

    for endpoint in &parsed.endpoints {
        generate_endpoint_dispatch_arm(&mut code, endpoint);
    }

    code.push_str("        _ => Err(EndpointError::UnknownEndpoint(name.to_string())),\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    let out_dir = std::env::var("OUT_DIR")?;
    let dest = Path::new(&out_dir).join("endpoint_generated.rs");
    std::fs::write(&dest, &code)?;

    Ok(())
}

/// Emit `invoke_generated_endpoint_stream` — the server-stream sibling of
/// [`generate_endpoint_runtime`]'s buffered dispatch.
///
/// The buffered dispatch returns the full `EndpointOutput`; the streaming
/// dispatch never materializes it. Each arm builds the SAME typed builder and
/// applies the SAME `EndpointArgs`-sourced optional setters as the buffered
/// arm, then drains the response chunk-by-chunk through the core
/// `request.stream(handler)` primitive. The per-chunk slice is type-erased to
/// `(*const c_void, usize)` at the boundary so one dispatch signature covers
/// every tick shape — the FFI layer reconstructs the typed pointer on the
/// caller side (the chunk pointer is the same `#[repr(C)]` tick the buffered
/// array exposes, so no re-marshaling happens). This dispatch exists solely to
/// serve the C ABI, so it is keyed off [`endpoint_streams_repr_c_ticks`]: only
/// endpoints whose core row is a flat `#[repr(C)]` tick get an arm. The
/// bounded snapshot / calendar lookups and the flat list endpoints have
/// nothing to drain incrementally, and the contract-discovery endpoint carries
/// an owned `String` the zero-copy callback cannot reinterpret.
fn generate_endpoint_stream_runtime(
    parsed: &ParsedEndpoints,
) -> Result<(), Box<dyn std::error::Error>> {
    let mut code = String::new();
    code.push_str(
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n",
    );
    code.push_str("// (validated against proto/mdds.proto)\n\n");
    code.push_str(include_str!(
        "templates/build_out/invoke_generated_endpoint_stream_preamble.rs.tmpl"
    ));

    for endpoint in &parsed.endpoints {
        if endpoint_streams_repr_c_ticks(endpoint) {
            generate_endpoint_stream_dispatch_arm(&mut code, endpoint);
        }
    }

    code.push_str("        _ => Err(EndpointError::UnknownEndpoint(name.to_string())),\n");
    code.push_str("    }\n");
    code.push_str("}\n");

    let out_dir = std::env::var("OUT_DIR")?;
    let dest = Path::new(&out_dir).join("endpoint_stream_generated.rs");
    std::fs::write(&dest, &code)?;

    Ok(())
}

/// Emit one `"name" => { ... }` arm for the streaming dispatch.
///
/// Mirrors [`generate_endpoint_dispatch_arm`]'s parsed-builder path exactly —
/// same required-arg extraction, same optional-setter loop — but terminates
/// with `.stream(handler)` instead of `.await`. The arm owns `handler` (only
/// one arm runs per call), so it moves it into the per-chunk closure the core
/// primitive takes by value.
fn generate_endpoint_stream_dispatch_arm(out: &mut String, endpoint: &GeneratedEndpoint) {
    writeln!(out, "        \"{}\" => {{", endpoint.name).unwrap();

    let method_call_params = endpoint
        .params
        .iter()
        .filter(|param| is_method_call_param(param))
        .collect::<Vec<_>>();
    let builder_params = endpoint
        .params
        .iter()
        .filter(|param| !is_method_call_param(param))
        .collect::<Vec<_>>();

    for param in &method_call_params {
        emit_required_arg(out, endpoint, param);
    }

    let call_args = method_call_params
        .into_iter()
        .map(call_arg_name)
        .collect::<Vec<_>>()
        .join(", ");

    // Always `mut`: the per-call deadline is threaded onto the builder
    // below (and optional setters may also reassign it), so the binding is
    // never left unused.
    writeln!(
        out,
        "            let mut builder = client.{}({call_args});",
        endpoint.name
    )
    .unwrap();

    emit_optional_setters(out, &builder_params);

    emit_builder_deadline(out);

    // Drain row-by-row. The closure hands the decoder-owned slice's data
    // pointer + length to `handler` as type-erased `(*const c_void, usize)`;
    // the slice (and its backing chunk) is freed before the next chunk is
    // fetched, so peak memory tracks a single chunk rather than the whole
    // result. `handler` is moved in — only this arm runs per call.
    // The core primitive surfaces the crate `Error`; convert to
    // `EndpointError` (the dispatch return type) through the same
    // `From<Error>` the buffered arms reach via `?`.
    out.push_str("            builder\n");
    out.push_str(
        "                .stream(move |chunk| handler(chunk.as_ptr().cast::<core::ffi::c_void>(), chunk.len()))\n",
    );
    out.push_str("                .await\n");
    out.push_str("                .map_err(EndpointError::from)\n");
    out.push_str("        }\n");
}

fn generate_mdds_endpoints(parsed: &ParsedEndpoints) -> Result<(), Box<dyn std::error::Error>> {
    let mut list_code = String::new();
    let mut parsed_code = String::new();
    let mut stream_code = String::new();
    let header =
        "// @generated DO NOT EDIT — regenerated by build.rs from endpoint_surface.toml\n// (validated against proto/mdds.proto)\n\n";
    list_code.push_str(header);
    list_code.push_str("impl MarketDataClient {\n");
    parsed_code.push_str(header);
    stream_code.push_str(header);

    for endpoint in &parsed.endpoints {
        if is_simple_list_endpoint(endpoint) {
            generate_mdds_list_endpoint(&mut list_code, endpoint);
        } else if is_streaming_endpoint(endpoint) {
            generate_mdds_streaming_endpoint(&mut stream_code, endpoint);
        } else {
            generate_mdds_parsed_endpoint(&mut parsed_code, endpoint);
        }
    }

    let out_dir = std::env::var("OUT_DIR")?;
    std::fs::write(
        Path::new(&out_dir).join("mdds_list_endpoints_generated.rs"),
        format!("{list_code}}}\n"),
    )?;
    std::fs::write(
        Path::new(&out_dir).join("mdds_parsed_endpoints_generated.rs"),
        &parsed_code,
    )?;
    std::fs::write(
        Path::new(&out_dir).join("mdds_streaming_endpoints_generated.rs"),
        &stream_code,
    )?;

    Ok(())
}

fn generate_endpoint_dispatch_arm(out: &mut String, endpoint: &GeneratedEndpoint) {
    writeln!(out, "        \"{}\" => {{", endpoint.name).unwrap();

    if is_simple_list_endpoint(endpoint) {
        let method_params = endpoint
            .params
            .iter()
            .filter(|param| is_method_call_param(param))
            .collect::<Vec<_>>();
        for param in &method_params {
            emit_required_arg(out, endpoint, param);
        }
        let args = method_params
            .iter()
            .map(|param| call_arg_name(param))
            .collect::<Vec<_>>()
            .join(", ");
        // Honour the tri-state per-call deadline. `Unset` calls the plain
        // method so the configured `request_timeout_secs` default applies;
        // `Disabled` (`with_timeout_ms(0)`) and an explicit `Millis` route
        // through the generated `_with_deadline` overload, where an explicit
        // `Duration::ZERO` disables the deadline and a positive value bounds
        // the call.
        let deadline_args = if args.is_empty() {
            "deadline".to_string()
        } else {
            format!("{args}, deadline")
        };
        out.push_str(
            "            let values = match args.deadline_setting().builder_deadline() {\n",
        );
        writeln!(
            out,
            "                Some(deadline) => client.{}_with_deadline({deadline_args}).await?,",
            endpoint.name
        )
        .unwrap();
        writeln!(
            out,
            "                None => client.{}({args}).await?,",
            endpoint.name
        )
        .unwrap();
        out.push_str("            };\n");
        writeln!(
            out,
            "            Ok(EndpointOutput::{}(values))",
            endpoint.return_type
        )
        .unwrap();
        out.push_str("        }\n");
        return;
    }

    let method_call_params = endpoint
        .params
        .iter()
        .filter(|param| is_method_call_param(param))
        .collect::<Vec<_>>();
    let builder_params = endpoint
        .params
        .iter()
        .filter(|param| !is_method_call_param(param))
        .collect::<Vec<_>>();

    for param in &method_call_params {
        emit_required_arg(out, endpoint, param);
    }

    let call_args = method_call_params
        .into_iter()
        .map(call_arg_name)
        .collect::<Vec<_>>()
        .join(", ");

    if is_streaming_endpoint(endpoint) {
        writeln!(
            out,
            "            let mut builder = client.{}({call_args});",
            endpoint.name
        )
        .unwrap();

        emit_optional_setters(out, &builder_params);

        emit_builder_deadline(out);
        out.push_str("            let mut result = Vec::new();\n");
        out.push_str("            builder\n");
        out.push_str("                .stream(|chunk| result.extend_from_slice(chunk))\n");
        out.push_str("                .await?;\n");
        // The streaming collect path drains per-chunk slices and keeps no
        // response header list, so it carries the full-schema presence (the
        // `all_columns` default) rather than a wire-projected set.
        out.push_str("            let columns = collected_columns(&result);\n");
        writeln!(
            out,
            "            Ok(EndpointOutput::{}(Ticks::new(result, columns)))",
            endpoint.return_type
        )
        .unwrap();
        out.push_str("        }\n");
        return;
    }

    // Parsed (buffered) endpoint. Always bind a mutable builder so the
    // per-call deadline can be threaded onto it even when the endpoint has
    // no optional builder params.
    writeln!(
        out,
        "            let mut builder = client.{}({call_args});",
        endpoint.name
    )
    .unwrap();

    emit_optional_setters(out, &builder_params);

    emit_builder_deadline(out);
    // The buffered builder resolves to `Ticks<T>` (rows + wire column set),
    // which the `EndpointOutput` variant carries through so the FFI
    // `_with_options` out-param can surface the projected column set.
    out.push_str("            let result = builder.await?;\n");
    writeln!(
        out,
        "            Ok(EndpointOutput::{}(result))",
        endpoint.return_type
    )
    .unwrap();
    out.push_str("        }\n");
}

/// Emit the per-call deadline application for a parsed / streaming builder
/// already bound as `mut builder`.
///
/// Threads [`EndpointArgs::deadline_setting`] onto the builder so the three
/// deadline intents are honoured: an unset deadline leaves the builder's
/// configured `request_timeout_secs` default in force (no `with_deadline`
/// call), an explicit zero (`with_timeout_ms(0)`) disables the deadline
/// (the call runs unbounded), and a positive value applies that bound.
fn emit_builder_deadline(out: &mut String) {
    out.push_str(
        "            if let Some(deadline) = args.deadline_setting().builder_deadline() {\n",
    );
    out.push_str("                builder = builder.with_deadline(deadline);\n");
    out.push_str("            }\n");
}

fn emit_required_arg(out: &mut String, _endpoint: &GeneratedEndpoint, param: &GeneratedParam) {
    if param.param_type == "Symbols" {
        writeln!(
            out,
            "            let symbol_values = args.required_symbols(\"{}\")?;",
            param.name
        )
        .unwrap();
        out.push_str(
            "            let symbol_refs: Vec<&str> = symbol_values.iter().map(String::as_str).collect();\n",
        );
        return;
    }

    let getter = required_getter_name(&param.param_type);
    writeln!(
        out,
        "            let {} = args.{getter}(\"{}\")?;",
        param.name, param.name
    )
    .unwrap();
}

/// Emit the optional-parameter setter chain: for each builder param, read it
/// from `args` via its typed optional getter and forward it onto `builder`
/// only when present. Shared by every dispatch-arm emitter so the generated
/// setter block reads identically across the registry, snapshot, and stream
/// paths.
fn emit_optional_setters(out: &mut String, builder_params: &[&GeneratedParam]) {
    for param in builder_params {
        let getter = optional_getter_name(&param.param_type);
        writeln!(
            out,
            "            if let Some(value) = args.{getter}(\"{}\")? {{",
            param.name
        )
        .unwrap();
        writeln!(
            out,
            "                builder = builder.{}(value);",
            param.name
        )
        .unwrap();
        out.push_str("            }\n");
    }
}
