use std::collections::HashMap;
use std::path::Path;

use serde::Deserialize;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    generate_tick_structs()?;
    Ok(())
}

// ─────────────────────────────────────────────────────────────────────────────
//  Code-generate tick structs from endpoint_schema.toml
// ─────────────────────────────────────────────────────────────────────────────

#[derive(Debug, Deserialize)]
struct Schema {
    types: HashMap<String, TickTypeDef>,
}

#[derive(Debug, Deserialize)]
struct TickTypeDef {
    doc: String,
    copy: bool,
    #[serde(default)]
    align: Option<u32>,
    #[allow(dead_code)]
    parser: String,
    #[serde(default)]
    #[allow(dead_code)]
    required: Vec<String>,
    #[serde(default)]
    #[allow(dead_code)]
    price_typed_columns: Vec<String>,
    #[serde(default)]
    #[allow(dead_code)]
    eod_style: bool,
    columns: Vec<ColumnDef>,
}

#[derive(Debug, Deserialize)]
struct ColumnDef {
    #[allow(dead_code)]
    name: String,
    field: String,
    r#type: String,
    /// For `price_type` fields: which price column to extract the type from.
    #[serde(default)]
    #[allow(dead_code)]
    price_source: Option<String>,
}

fn generate_tick_structs() -> Result<(), Box<dyn std::error::Error>> {
    let schema_path = "endpoint_schema.toml";
    let schema_str = std::fs::read_to_string(schema_path)?;
    let schema: Schema = toml::from_str(&schema_str)?;

    let out_dir = std::env::var("OUT_DIR")?;

    // Collect type names and sort for deterministic output.
    let mut type_names: Vec<&String> = schema.types.keys().collect();
    type_names.sort();

    // ── Generate tick_generated.rs (struct definitions) ──────────────────────
    let mut structs = String::new();
    structs.push_str(
        "// Auto-generated by build.rs from endpoint_schema.toml \u{2014} do not edit manually.\n\n",
    );
    structs.push_str("use crate::types::price::Price;\n\n");

    for type_name in &type_names {
        let def = &schema.types[*type_name];
        generate_struct(&mut structs, type_name, def);
    }

    let structs_dest = Path::new(&out_dir).join("tick_generated.rs");
    std::fs::write(&structs_dest, &structs)?;

    // Rerun if schema changes
    println!("cargo:rerun-if-changed={}", schema_path);

    Ok(())
}

/// Generate a single tick struct definition.
fn generate_struct(out: &mut String, type_name: &str, def: &TickTypeDef) {
    // Doc comment — handle embedded \n for multi-line docs.
    for line in def.doc.lines() {
        out.push_str(&format!("/// {}\n", line));
    }

    // Derive
    if def.copy {
        out.push_str("#[derive(Debug, Clone, Copy)]\n");
    } else {
        out.push_str("#[derive(Debug, Clone)]\n");
    }

    // Repr
    if let Some(align) = def.align {
        out.push_str(&format!("#[repr(C, align({align}))]\n"));
    }

    out.push_str(&format!("pub struct {type_name} {{\n"));

    for col in &def.columns {
        let rust_type = match col.r#type.as_str() {
            "i32" => "i32",
            "i64" => "i64",
            "f64" => "f64",
            "String" => "String",
            "price" => "i32",
            "price_value" => "i32",
            "eod_num" => "i32",
            "bool" => "i32",
            other => panic!("unknown column type '{other}' in schema for {type_name}"),
        };
        out.push_str(&format!("    pub {}: {},\n", col.field, rust_type));
    }

    out.push_str("}\n\n");
}
